### ISSUE TITLE
Angaben von Personen zu Tätigkeiten

### ISSUE THREAD

**Issue by marians** [OParl/spec#1]
Die meisten Systeme führen Angaben über Tätigkeiten von Personen (im Sinne von z.B. § 17 Korruptionsbekämpfungsgesetz NRW).

Diese Angaben sind bisher nicht vom Datenmodell abgedeckt.

**Comment by konstin** [comment]
Diese Informationen sind nicht in größerem Umfang maschinenlesbar in Ratsinformationssystemen verfügbar und damit nicht für OParl relevant. Für Freitext-Informationen kann `life` verwendet werden.
