### ISSUE TITLE
Paginierung: Anzahl 100 durch client-initiated paging ersetzen

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#144]
In Abschnitt 6060 wird eine maximale Seitengröße von `100` empfohlen. Der Grund für eine Begrenzung ist klar. Derartige Konstanten sind in Spezifikationen aber offensichtlich nicht ideal. Die Frage ist nun, ob dies durch Mechanismen wie z.B. client-initiated paging vermieden werden kann.

**Comment by the-infinity** [comment]
Ist nun optional Teil der 1.1 Änderungen https://github.com/OParl/spec/pull/384/commits/67fe2c3e826fd4e62ee6f0a9ea786c1994f380ff . Als Pflicht ist es ggf. für spätere Versionen denkbar, jedoch aktuell mit den bestehenden RIS nicht realistisch umsetzbar.
