### ISSUE TITLE
Weitere Datumeigenschaften an Drucksache benötigt

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#151]
Älterer Input der Stadt Bonn:

_Das Feld Datum ist so zu unspezifisch. In Bonn stehen zur Verfügung:_
- [x] Das Erstelldatum von Anträgen und Anfragen
- [ ] Das Eingangsdatum im Büro OB/Ratsbüro
- [x] Das Genehmigungsdatum durch den OB
- [x] das Änderungsdatum

_Die letzten beiden Datumsangaben erscheinen mir unbedingt notwendig. Durch das 
Genehmigungsdatum wird die offizielle 'Freigabe' der Drucksache erkennbar. Das 
Datum der letzten Änderung macht eventuelle redaktionelle Änderungen kenntlich._

**Comment by konstin** [comment]
Mit `created`, `modified` und `publishedDate` sind alle Daten in der Spezifikation abgebildet, die Ratsinformationssysteme zuverlässig angeben können.
