### ISSUE TITLE
Plural und Singular-Form von Begriffen

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#161]
z.B. für den Begriff "Unterausschuss" sollte auch die Plural-Schreibweise "Unterausschüsse" verfügbar gemacht werden können. Es kann an verschiedenen Stellen von Benutzerschnittstellen helfen, wenn beide Formen zur Verfügung stehen.

**Comment by konstin** [comment]
Das Problem wird durch eine einheitliche Nomenklatur (s. z.B. #335 #336) gelöst. Dafür selbst eine Lösung ohne einheitlich Nomenklatur zu schaffen wäre für OParl nicht zielführend.
