### ISSUE TITLE
Abschnitte Initiatoren und Autoren überarbeiten

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#208]

**Comment by eFrane** [comment]
Ich habe den Titel des Issues geändert, damit schneller deutlich wird, worum es geht.

**Comment by the-infinity** [comment]
https://github.com/OParl/spec/commit/5be965a947fb10d2329e15157f2607fb117f6ecf - ein Lösungsvorschlag, der der speziellen Situation bei OParl wohl recht nahe kommt. Ich schließe das jetzt erst mal, wenn doch noch weitere Änderungen gewünscht sind, gerne wieder öffnen.
