### ISSUE TITLE
Einschränkung der JSON-LD-Ausgabe per Spezifikation

### ISSUE THREAD

**Issue by marians** [OParl/spec#216]
In diesem umfangreichen Issue wird eine Diskussion fortgesetzt, die in #157 schon einmal begonnen wurde.

Inzwischen hat mich von Seiten mehrerer Entwickler Feedback erreicht, dass OParl durch JSON-LD zu komplex und unverständlich geworden sei. Dies sei in einem Fall auch Grund dafür gewesen, sich nicht weiter in die Spec-Entwicklung einzubringen. Das halte ich für ein ganz wichtiges Warnsignal, das alleine schon schwer genug wiegt, um die Diskussion wieder aufzunehmen. Und es deckt sich mit meiner eigenen Wahrnehmung.

Nach Einschätzung des Validator-Entwicklerteams kommt noch hinzu, dass es nach aktuellem Stand der Specs erforderlich sei, zur sinnvollen Verarbeitung der OParl-Ausgabe mit einer JSON-LD-Bibliothek zu arbeiten, die die ausgegebenen Daten anhand des JSON-LD-Contexts normalisiert (in die "Expanded Form" übersetzt). Problematisch ist, dass derartige Libraries bisher erst für wenige Programmiersprachen zur Verfügung stehen. Für eine native Client-Entwicklung z. B. auf iOS stellt dies eine immense Hürde dar.
## Ausgabe nach aktuellem Stand der Specs

Das nachfolgende **Beispiel 1** zeigt ein JSON-LD-Objek. Es entspricht keinem existierenden OParl-Objekttyp, ist jedoch so aufgebaut, wie es von der OParl-Spezifikation aktuell für alle Objekte verlangt bzw. empfohlen wird.

**Beispiel 1:**

``` json
{
    "@context": [
        "http://oparl.org/schema/1.0/Test",
        {
            "example": "http://www.example.com/"
        }
    ],
    "@type": "oparl:Test",
    "@id": "example:thisObject",
    "name": ["Testobjekt", "foobar"]
}
```

Das nächste Beispiel 2 zeigt eine Ausgabe, die im Sinne von JSON-LD das gleiche bedeutet, aber die Eigenschaft "name" etwas anders ausgibt:

**Beispiel 2:**

``` json
{
    "@context": [
        "http://oparl.org/schema/1.0/Test",
        {
            "example": "http://www.example.com/"
        }
    ],
    "@type": "oparl:Test",
    "@id": "example:thisObject",
    "name": {
        "@set": ["Testobjekt", "foobar"]
    }
}
```

Das dritte Beispiel zeigt die im Sinne von JSON-LD identische Information in dem, was JSON-LD die _Expanded Form_ nennt:

**Beispiel 3:**

``` json
[
    {
        "@id": "http://www.example.com/thisObject",
        "@type": [
            "http://oparl.org/specs/1.0/Test"
        ],
        "http://schema.org/name": [
            {
                "@value": "Testobjekt"
            },
            {
                "@value": "foobar"
            }
        ]
    }
]
```

Nach JSON-LD drücken alle drei Beispiele das selbe aus. Nach aktuellem Stand unserer Specs sind viele Variationen möglich, deren Angleichung/Normalisierung auf Seite des Clients nicht trivial ist und in jedem Fall erfordert, dass man die JSON-LD-Spezifikation kennt und verstanden hat.
## Lösungsansatz

Der Lösungsansatz, den ich mit dem Validator-Entwicklerteam besprochen habe, sieht vor, die Ausgabe so zu spezifizieren, dass sie valides JSON-LD ergibt, jedoch in einer festgelegten Form auch von reinen JSON-Clients verarbeitet werden kann, die keine Kenntnis der JSON-LD-Spezifikation besitzen. Von solchen reinen JSON-Clients ist zu jedoch zu erwarten, dass sie in Kenntnis der OParl-Spezifikation entwickelt werden.

Das nachfolgende Beispiel 4 zeigt, wie die Ausgabe des oben eingeführten Objekts aussehen müsste, um dies zu erfüllen.

**Beispiel 4:**

``` json
{
    "@context": "http://oparl.org/schema/1.0/Test",
    "@type": "http://oparl.org/schema/1.0/Test",
    "@id": "http://www.example.com/thisObject",
    "name": ["Testobjekt", "foobar"]
}
```

Die Veränderung gegenüber Beispiel 1 sind:
- nur noch der OParl-definierte JSON-LD-Kontext wird in `@context` eingebunden.
- URLs sind nicht mehr mit Präfixen verkürzt (_prefixed_), sondern werden komplett ausgeschrieben.

JSON-Clients könnten die Eigenschaft `@context` einfach ignorieren. Die Eigenschaften `@type` und `@id` könnten sie je nach Bedarf nutzen.

Im Sinne von JSON-LD trägt Beispiel 4 dieselbe Information wie die Beispiele 1, 2 und 3.

Eine Unwägbarkeit der JSON-LD-Ausgabe besteht darin, dass Eigenschaften grundsätzlich mehrere Werte haben können. Für JSON-LD wären die beiden nachfolgenden Beispiele das selbe.

**Beispiel 5:**

``` json
{
    ...
    "name": "Testobjekt"
    ...
}
```

**Beispiel 6:**

``` json
{
    ...
    "name": ["Testobjekt"]
    ...
}
```

Um reine JSON-Clients zu unterstützen, müssen wir hier Eindeutigkeit schaffen, insbesondere um die Möglichkeit abzufangen, dass eine Liste von Objekten über eine externe URL wiedergegeben werden kann.

Nehmen wir das folgende Beispielobjekt mit seiner Eigenschaft `linkedObjects`.

**Beispiel 7:**

``` json
{
    "@context": "http://oparl.org/schema/1.0/Test",
    "@type": "http://oparl.org/schema/1.0/Test",
    "@id": "http://www.example.com/thisObject",
    "linkedObjects": [
        "http://www.example.com/myObjects/1",
        "http://www.example.com/myObjects/2"
    ]
}
```

Die Spezifikation würde dem Client-Entwickler mitteilen, dass die Eigenschaft `linkedObjects` ein Array ("Kardinalität: 0 bis *") ist, deren Einträge die URLs von Objekten eines bestimmten Typs sind.

Um lange Listen nicht als Teil eines Objektes ausgeben zu müssen, wäre jedoch auch die Form wie in Beispiel 8 möglich.

**Beispiel 8:**

``` json
{
    "@context": "http://oparl.org/schema/1.0/Test",
    "@type": "http://oparl.org/schema/1.0/Test",
    "@id": "http://www.example.com/thisObject",
    "linkedObjects": "http://www.example.com/myObjects"
}
```

Der Client erkennt hier (in Beispiel 8), dass als Wert der Eigenschaft `linkedObjects` kein Array, sondern nur ein einzelner String ausgegeben wurde. Der Client soll daraus schließen, dass über diese URL das gesamte Array (optional mit Paginierung) abgerufen werden kann.

**Beispiel 9:**

``` json
{
    "@context": "http://oparl.org/schema/1.0/Test",
    "@type": "http://oparl.org/schema/1.0/Test",
    "@id": "http://www.example.com/thisObject",
    "linkedObjects": [
        "http://www.example.com/myObjects/1"
    ]
}
```

Das Beispiel 9 zeigt im Unterschied dazu, wie die Ausgabe aussehen müsste, wenn die Eigenschaft `linkedObjects` genau einen Array-Eintrag hat, der direkt hier im Objekt ausgegeben werden soll. In diesem Fall muss zur Unterscheidung vom Fall in Beispiel 8 ein Array (eckige Klammern) ausgegeben werden.

Für den Fall, dass der Server eigene Eigenschaften, die nicht in OParl spezifiziert sind, ausliefern soll, würde das gleiche Verfahren wie bisher spezifiziert genutzt. In diesem Fall muss der Server den JSON-LD-Kontext um eigene Angaben (oder Angeben des Server-Anbieters) erweitern. Beispiel 10 zeigt das.

**Beispiel 10:**

``` json
{
    "@context": [
        "http://oparl.org/schema/1.0/Test",
        {
            "risanbieter": "http://www.risanbieter.de/oparl/schema/"
        }
    ],
    "@type": "http://oparl.org/schema/1.0/Test",
    "@id": "http://www.example.com/thisObject",
    "name": ["Testobjekt", "foobar"],
    "risanbieter:myProperty": "123/ab/xy"
}
```

Wie man sieht, befürworten wir in diesem Fall einen Präfix im Eigenschaftsnamen. Dieser wird JSON-Clients nicht behindern. Zweck ist, die Eigenschaft zukunftssicher von den über OParl spezifizierten Eigenschaften zu unterscheiden.

Wie könnten die **Anforderungen** lauten, mit denen wir das in der Spezifikation festlegen?
1. URLs als Werte DÜRFEN NICHT abgekürzt (_prefixed_) werden.
2. Die Ausgabe in einer _expanded Form_, _Flattened Form_ oder _Framed Form_ (vgl. JSON-LD Specs) ist nicht gestattet.
3. Die in dieser Spezifikation definierten Eigenschaften von OParl-spezifischen Objekttypen MÜSSEN in exakt der spezifizierten Schreibweise genutzt werden. Ein Prefixing der Eigenschaftsnamen mit URLs oder URL-Präfixen ist entsprechend nicht erlaubt.
4. Hersteller- bzw. Server-eigene Eigenschaften MÜSSEN hingegen mit einem eigens definierten Präfix versehen werden.
5. Hersteller- bzw. Server-eigene Eigenschaften DÜRFEN KEINEN Doppelpunkt im Namen enthalten.
6. Eigenschaften, die im JSON-Sinne ein Array als Wert haben können, sind ZWINGEND als Arrays auszugeben, auch wenn das Array nur einen Wert hat.
## Alternativen

Wir haben auch die Variante diskutiert, eine alternative reine JSON-Ausgabe zu verlangen. Dies könnte über den Accept-Header gesteuert werdne, den der Client setzen müsste. Die Entsprechung zu Beispiel 1 in einfachem JSON könnte so aussehen:

**Beispiel 11:**

``` json
{
    "type": "http://oparl.org/schema/1.0/Test",
    "id": "http://www.example.com/thisObject",
    "name": ["Testobjekt", "foobar"]
}
```

Hier entfällt die Eigenschaft `@context`, `type` und `id` haben nur das `@`-Zeichen eingebüßt.

Jedoch scheint es, als könnten wir mit dem obigen Ansatz beide Welten zufrieden stellen und damit die Server-Implementierung vereinfachen.

Kommentare sind willkommen!

**Comment by akuckartz** [comment]
Dieses Issue ist zwar geschlossen, aber da der vermeintlich zu hohe Aufwand für openruhr.de als Argument gegen JSON-LD angegeben wurde ist dieser Hinweis zur Nachfolgeplattform hier eventuell dennoch sinnvoll (auch im _doppelten_ Sinn von Linked Data ;-):
https://github.com/okfde/ris-web/issues/6
