### ISSUE TITLE
Semantik von ZWINGEND ist mehrdeutig

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#226]
In mehreren Issues kam inzwischen die Frage auf, was die Angabe ZWINGEND bei einer Property _genau_ bedeutet.

**Comment by lu-j** [comment]
Wenn ich die Diskussion richtig verstanden habe, ging es hauptsächlich darum, was passieren soll, wenn für eine zwingende Eigenschaft kein Wert vorhanden ist. Mittlerweile haben wir uns allerdings darauf geeinigt, dass nur Systemeigenschaften zwingend sein sollen, also Metainformationen, die direkt vom RIS ausgegeben werden, zum Beispiel "id" oder "type" (siehe #292). Für diese Eigenschaft kann immer ein Wert ausgegeben werden. Damit sollte das Problem gelöst sein, daher schließe ich dieses Issue.

**Comment by akuckartz** [comment]
@lu-j Ich begrüße diese neue Lösung. Immerhin war das frühere Ergebnis aus meiner Sicht ein Musterbeispiel für eine Verkomplizierung durch eine überwiegend nicht rational begründete Entscheidung.
