### ISSUE TITLE
Liste verwendeter Spezifikationen

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#230]
"Make a list of normative references."
http://www.w3.org/TR/qaframe-spec/#reference

**Comment by lu-j** [comment]
Als OParl noch auf mehreren Spezifikationen aufgebaut war, wäre eine Liste eine gute Idee gewesen. Mittlerweile basiert OParl nur noch auf HTTP, JSON und verwendet die gängige ISO 8601 Norm für Datumsangaben, aber das trifft auf sehr viele moderne Web-APIs zu. Ansonsten wird voraussichtlich noch GeoJSON verwendet, aber ich denke dafür lohnt sich eine Liste nicht, daher schließe ich das Issue.
