### ISSUE TITLE
Objekte des "removed" Feed

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#233]
Auch - aber nicht nur - vor dem Hintergrund von #231 ist es möglicherweise sinnvoll, wenn Objekte *nicht* vollständig entfernt werden, sondern diese stattdessen jeweils durch ein Objekt mit einer `removed`-Eigenschaft und Zeitstempel als Wert ersetzt werden. Ein solches Objekt kann auch eine Eigenschaft mit dem Grund der Entfernung enthalten, z.B. `reason` (Beispiel: "Gegenwärtig entfernt nach gerichtlicher Entscheidung im Eilverfahren").

Zu klären wäre dann, ob die ursprüngliche Klasse des Objekts verwendet werden soll bzw. was mit den anderen Eigenschaften passiert (insbesondere solchen mit Kardinalität 1 oder "1 bis n").

**Comment by konstin** [comment]
Gelöst mit `deleted` und dokumentiert in Kapitel 2.8
