### ISSUE TITLE
JSON-LD Unterstützung

### ISSUE THREAD

**Issue by lanthaler** [OParl/spec#237]
Anscheinend wurde letzte Woche beschlossen die JSON-LD Unterstützung zu entfernen:

> … eine Entscheidung vom Freitag, wonach OParl nicht auf JSON-LD basieren wird.
> — @akuckartz in https://github.com/OParl/specs/issues/226#issuecomment-48085370

Meine Nachfrage nach den Gründen und der Diskussion die zu dieser Entscheidung führten wurden folgendermaßen beantwortet:

> Ja, die Entscheidung ist gefallen und Grund ist im Allgemeinen der Wunsch nach simpler Client-Implementierung und Validierung. Das hat nicht alleine mit JSON-LD zu tun, aber auch.
> — @marians in https://github.com/OParl/specs/issues/226#issuecomment-48326108

Da JSON-LD 100% valides JSON ist und clients dieses auch als solches direkt verwenden können, bin ich doch sehr verwundert über die Aussage das Client-Implementierung und Validierung durch den Verzicht auf JSON-LD vereinfacht wird.  alls die Spezifikation die genaue JSON Struktur vorschreibt, was sie bei Verzicht auf JSON-LD zweifellos machen muss, gibt es absolut keinen Unterschied für Clients oder Validatoren.

Der Vorteil von JSON-LD besetht darin dass OParl auf einen offiziellen und bereits weit verbreiteten (Google, Microsoft, Yahoo, Yandex, BCC, DBpedia, ...) W3C Standard aufbauen würde anstatt das Rad selbst neu zu erfinden. Links z.B werden von JSON nicht unterstützt. JSON-LD erlaubt es mächtigere Clients zu erstellen, *falls gewünscht*. Es vereinfacht auch Datenintegration, Dokumentation und bietet Erweiterungspunkte für zukünftige Versionen von OParl.

Ich würde deshalb alle Beteiligten nochmal bitten die Entscheidung zu überdenken und stehe natürlich gerne für Fragen zur Verfügung. Meiner Meinung beruht ein Großteil der Entscheidung auf Mißverständnissen von JSON-LD und der Meinung dass, falls JSON-LD eingesetzt wird, Clients auf alle Eventualitäten vorbereitet sein müssen und nur funktionieren falls sie jede beliebige Variation von JSON-LD verstehen.

**Comment by konstin** [comment]
Ich schließe diesen Issue jetzt, da es in absehbarer Zeit keine Unterstützung von JSON-LD in OParl geben wird.
