### ISSUE TITLE
Dokumentation | 5 Schema - Beschreibung aller Objekte

### ISSUE THREAD

**Issue by sterni24** [OParl/spec#239]
Es wäre hilfreich, wenn die Eigenschaften in den Beispielen dieselbe Reihenfolge aufweisen, wie die Reihenfolge der Eigenschaften des jeweiligen Objekts.

Ein weiterer Aspekt ist die Reihenfolge der Eigenschaften. Diese würde ich nach sachlichen Gesichtspunkten anordnen. Z. B. stehen in <code>opral:Organization</code> die Eigenschaften <code>membership</code> und <code>meeting</code> zwischen <code>name</code> und <code>shortname</code>. Die Listenausgaben würde ich weiter nach hinten setzen. Liest sich einfach besser.

**Comment by eFrane** [comment]
Aus meiner Sicht ist das erledigt. Einzelne Beispiele müssen sowieso weiterhin angepasst werden, sofern sich durch andere Issues etwas ändert.
