### ISSUE TITLE
Mehr Übersicht in der Eigenschaften-Beschreibung

### ISSUE THREAD

**Issue by marians** [OParl/spec#242]
Gehen wir mal davon aus, dass nach Verabschiedung von OParl 1.0 noch eine übersichtlichere Version gesetzt wird, in der Layout-Fragen im Detail manuell gelöst werden können. Trotzdem hätte ich gerne auch in den automatisch generierten PDF- und anderen Derivaten mehr Übersicht in der Eigenschaften-Bechreibung. Damit soll auch die Arbeitsversion besser lesbar und verständlicher werden.

Durch die Kombination aus Markdown und Verarbeitung mit pandoc sind die Möglichkeiten hier ein wenig beschränkt. Ich habe experimentiert, inwiefern sich mit Tabellen-Darstellung etwas verbessern lässt. Hier das Ergebnis. Ich würde mich über Feedback freuen, bevor ich das aufs gesamte Schema-Kapitel anwende.

**Markdown vorher:**
```
`oparlVersion`
:   Die URL der OParl-Spezifikation, die von diesem Server unterstützt 
    wird. Der Wert MUSS die URL `http://oparl.org/specs/1.0/` sein.
    Typ: URL.
    Kardinalität: 1.
    ZWINGEND.

`body`
:   Liste der URLs der [`oparl:Body`](#oparl_body)-Objekte, also der 
    Körperschaften, die auf dem System vorliegen. Alternativ kann statt 
    einer Liste eine einzelne URL zum Abruf der Liste angeboten werden.
    Typ: URL des `oparl:Body` Objekts
    Kardinalität: 1 - *.
    ZWINGEND.
```

**PDF-Ausgabe vorher:**

![bildschirmfoto 2014-07-11 um 10 20 49](https://cloud.githubusercontent.com/assets/273727/3550100/518c706c-08d4-11e4-8d7c-f59870441e62.png)

**Markdown nachher:**
```
**`oparlVersion`**

-------------   -------------------------------------------------------
Beschreibung    Die URL der OParl-Spezifikation, die von diesem Server
                unterstützt wird. Aktuell kommt hier nur ein Wert in
                Frage. Mit zukünftigen OParl-Versionen kommen weitere
                mögliche URLs hinzu.
Status          _ZWINGEND_
Typ             URL
Wert            `http://oparl.org/specs/1.0/`
-------------   -------------------------------------------------------

**`body`**

-------------   -------------------------------------------------------
Beschreibung    Liste der Körperschaften (`oparl:Body`-Objekte), die
                auf dem System existieren.
Status          _ZWINGEND_
Typ             Array mit Objekt-URLs oder URL zum Listenabruf
Siehe auch      [`oparl:Body`](#oparl_body), [Objektlisten](#objektlisten)
-------------   -------------------------------------------------------
```

**PDF-Ausgabe nachher:**

![bildschirmfoto 2014-07-11 um 10 47 30](https://cloud.githubusercontent.com/assets/273727/3550366/0747b80a-08d8-11e4-8837-293b1e0bc4dc.png)

Für die ästhetisch sensiblen: Man sieht, dass die Tabellen unterschiedlich breit gerendert werden. Das missfällt mir, wird aber nur die Arbeitsversionen betreffen, nicht die finale, manuell gesetzte.

**Comment by eFrane** [comment]
Mit dem Wechsel auf JSON-Schema hat sich die Formatierung der Schemainformation ein klein wenig von dem hier besprochenen geändert, ist aber nach wie vor tabellarisch. 

Ich denke, die momentane Darstellung ist bis auf weiteres ausreichend, einzig die fehlende gut sichtbare Trennung von Zeilen in der PDF-Ausgabe stört mich ein wenig. Die HTML-Version sieht da z.B. um einiges deutlicher aus.

![Ausschnitt aus der aktuellen PDF-Version](https://cloud.githubusercontent.com/assets/237165/8799262/230ff108-2fa9-11e5-8ff7-5f3b5f49978a.png)

![Ausschnitt aus der (live) HTML-Version](https://cloud.githubusercontent.com/assets/237165/8799263/2340b374-2fa9-11e5-9c9e-0f5c040f8264.png)

**Comment by the-infinity** [comment]
Zumal es mittlerweile auch den Demoserver gibt, der die Struktur zusätzlich beschreibt. Damit kann man das Issue wohl schließen.
