### ISSUE TITLE
AgendaItem > Consultation: Zeigt wirklich jeder Tagesordnungspunkt nur auf eine Beratung?

### ISSUE THREAD

**Issue by marians** [OParl/spec#244]
Aktuell ist dies im Dokument noch als Frage gekennzeichnet. Hier brauchen wir Feedback von den RIS-Herstellern.

Ist es richtig, dass ein bestimmter Tagesordnungspunkt (oparl:AgendaItem) auf genau eine Beratung (oparl:Consultation) zeigen kann? Damit könnte je Tagesordnugnspunkt nur maximal eine Drucksache/Vorlage beraten werden.

@bschalitz @BThie @sterni24

**Comment by lu-j** [comment]
Ich denke die Diskussion hat ergeben, dass es bei einer 1:1 Beziehung bleibt und wir Sonderfälle in OParl 1.0 noch nicht abdecken. Die Idee an den Client zu kommunizieren, dass die Dokumentation der Sitzung abgeschlossen ist und die Tagesordnungspunkte final sind, wird in #279 weiter behandelt.
