### ISSUE TITLE
Eigenschaft oparl:Membership - onBehalfOf (delegation) 

### ISSUE THREAD

**Issue by sterni24** [OParl/spec#249]
In Membership fehlt die Angabe, aus welchen Gruppierungen sich das Gremium zusammengesetzt wird.

<code>delegation</code> können sein:
Fraktionen
Parteigruppierungen
fraktionslose (null)
externe Gremien

-> diese Annahme war falsch, weitere Anmerkungen siehe im nächsten Kommentar.

**Comment by lu-j** [comment]
Mit der Eigenschaft "onBehalfOf" kann man pro Mitgliedschaft darstellen, welche Organization eine Person vertritt.

Das scheinen die RISe aber nicht abbilden zu können. Man kann zu einer Person zwar allgemein die Zugehörigkeit zu einer Organisation speichern, aber nicht pro Mitgliedschaft. Es ist also nicht möglich, dass eine Person in zwei Ausschüssen verschiedene Organisationen vertritt. Daher habe ich die Eigenschaft "onBehalfOf" entfernt um Missverständnisse zu vermeiden. Ich will zur Sicherheit die RIS-Hersteller aber nochmal fragen, ob richtig liege.

**Comment by sterni24** [comment]
Der letzte Kommentar, der zur Löschung der Eigenschaft <Code>onBehalfOf</Code> geführt hat, ist mir entgangen. Wir bilden das gremienspezifisch ab, siehe www.ratsinfomanagement.net unter Gremienstammdaten. In dieser Eigenschaft können Fraktionen oder externe Gremien enthalten sein. Ein Grund mehr, die oparl:Organization zu typisieren, #173.

**Comment by the-infinity** [comment]
Gelöst mit https://github.com/OParl/spec/commit/4c93bcba7a9c5fa02e64e4ee77d8303760f60322.
