### ISSUE TITLE
neue Eigenschaft oparl:Person - Partei

### ISSUE THREAD

**Issue by sterni24** [OParl/spec#250]
Die Diskussion um #249 hat für mich ergeben, bei oparl:Person die Eigenschaft "Partei" abzubilden.

Hierzu auch ein Beispiel: https://alfter.ratsinfomanagement.net/personen/?__=LfyIfvCWq8SpBQj0MiyHaxCYvGJ

**Comment by the-infinity** [comment]
Fixed mit https://github.com/OParl/spec/commit/ebf073db68721c5a8e923c56e2a3208aec389c5c inkl. expliziter Trennung zwischen Partei und Fraktion.
