### ISSUE TITLE
Eigenschaften oparl:Consultation - organization, meeting, agendaItem

### ISSUE THREAD

**Issue by sterni24** [OParl/spec#254]
Da man auch über <code>oparl:Paper</code> Zugriff auf die Objekte von <code>oparl:Consultation</code> hat, ist die Darstellung der Eigenschaften nicht korrekt und unvollständig.

Nachstehende Eigenschaften sind erforderlich:

<code>organization</code> - Kardinalität 1, ZWINGEND
<code>meeting</code> - Kardinalität 0 -1, ZWINGEND
<code>agendaItem</code> - Kardinalität 0 -1, ZWINGEND

Wenn für <code>oparl:Paper</code> ein Objekt <code>oparl:Consultation</code> vorliegt, dann muss es zumindest auf ein <code>oparl:Organization</code> verweisen.
Wenn <code>oparl:Paper</code> terminiert ist, dann muss es zusätzlich auf ein <code>oparl:Meeting</code> verweisen.
Wenn <code>oparl:Paper</code> auf einer Tagesordnung steht, dann muss es darüberhnaus auf ein <code>oparl:AgendaItem</code> verweisen.

Die Kombination aus Kardinalität 0 -1 und ZWINGEND wurde unter #226 bereits ausgiebig diskutiert.

**Comment by lu-j** [comment]
Wenn ich das Issue richtig verstanden habe, ist der Vorschlag, dass zum Consultation-Objekt die Eigenschaft "meeting" hinzugefügt wird, um das zugehörige Meeting-Objekt zu referenzieren. Ich denke, dass ist eine gute Idee, daher habe ich die Eigenschaft hinzugefügt.

Oft gibt es bei einem Consultation-Objekt nämlich folgenden Ablauf: 
1. Zunächst steht nur fest in welchem Ausschuss die Drucksache beraten wird, es ist also nur die "organization"-Eigenschaft vorhanden.
2. Dann steht fest in welcher Sitzung die Drucksache beraten wird, dann ist auch die Eigenschaft "meeting" vorhanden.
3. Sobald die Tagesordnung für die Sitzung festgelegt ist, ist auch die Eigenschaft "agendaItem" vorhanden.

Trotzdem möchte ich nochmal nachfragen, ob ich das Issue richtig verstanden habe.

Was die die Kombination von Kardinalität 0 und ZWINGEND betrifft: wir haben uns in mittlerweile geeinigt, dass nur Systemeigenschaften, die immer von einem RIS ausgegeben werden können, zwingend sein sollen, siehe #292.

**Comment by konstin** [comment]
Wenn ich das richtig verstehe sind die Vorschläge mit der jetzigen Variante von `Consultation` bereits umgesetzt.
