### ISSUE TITLE
Eigenschaft oparl:Location - inversOf fehlt

### ISSUE THREAD

**Issue by sterni24** [OParl/spec#255]
Eine der zentralen Anliegen von OParl ist es (entsprechend den Nutzungsszenarien 3.3 und Kapitel 4.1.2), eine Metasuche über räumliche Bezüge zu ermöglichen.

Wie ist das derzeit in OParl angedacht? 

Fehlt hier die Beziehung von <code>oparl:Location</code> zu <code>oparl:Paper</code> oder? Kann eine <code>oparl:Location</code>auf mehrere <code>oparl:Paper</code> verweisen?

**Comment by the-infinity** [comment]
Backref hinzugefügt in https://github.com/OParl/spec/commit/dedc1ea3f11c6165abdd0a1be522eeafce6ee1e1 . Da das gemäß https://github.com/OParl/spec/issues/292 optional ist, ergibt sich auch kein hoher Implementierungsaufwand, wenn derartige Daten nicht vorhanden sind.
