### ISSUE TITLE
Federführung für `Meeting` und `Consultation`

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#256]
Siehe https://github.com/OpenGovLD/specs/issues/64

**Comment by the-infinity** [comment]
Dieses Thema hat extrem viele Facetten (politische Verantwortung, Verwaltungs-Verantwortung, Gruppe, Person, ...?), so dass das für OParl 1.0 nicht realisierbar ist. Für eine spätere Version kann der Issue dann neu erstellt werden.
