### ISSUE TITLE
Eigenschaften oparl:Location - description / geometry

### ISSUE THREAD

**Issue by sterni24** [OParl/spec#259]
Beide Eigenschaften sollten die Kardinalität von 1 - ZWINGEND aufweisen. Alles andere macht keinen Sinn.

**Comment by the-infinity** [comment]
Angesichts von https://github.com/OParl/spec/issues/292 erübrigt sich die Diskussion nun, da nun alles empfohlen ist. Dies hat natürlich zur Folge, dass man theoretisch sehr sinnlose Objekte angeben kann, dies würde aber auch in diesem Fall der folgenden Direktive entsprechen: "Es soll grundsätzlich empfohlen sein, alle vorhandenen öffentlichen Daten aus der Datenbank auszugeben, sofern keine Datenschutzbestimmungen dagegen sprechen." In diesem Sinne dürfte das Issue gelöst sein.
