### ISSUE TITLE
Nicht RESTful

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#268]
Im Entwurf steht, dass die API RESTful sei. Diese Behauptung ist falsch, da wesentliche Kriterien von REST nicht erfüllt sind.

**Comment by akuckartz** [comment]
Ich wurde von ausserhalb der OParl-Unterstützer auf dieses Issue angesprochen: Die Beschreibung sei etwas spärlich. Der Grund ist einfach. Da seit 7 Monaten kein einziges Issue in diesem Repository mehr bearbeitet wurde spare ich mir inzwischen hier den Aufwand für ausführlichere Beschreibungen.

Da ich aber gefragt wurde: Konkret geht es insbesondere um die Nichteinhaltung der HATEOS-Restriktionen von REST. Keine Spezifikation muss sich daran halten, aber wenn sie das nicht tut, dann soll sie bitte nicht als REST-API o.ä. bezeichnet werden. Eine API die nur `application/json` als Media Type unterstützt _kann_ nicht RESTful sein.

**Comment by sokai** [comment]
+1

→ *Was wäre dann aber ein Lösung?*

**Vorschlag:**
* Immer nur (von JSON-)„API“ schreiben und Kapitel „4.1.3 RESTful“ raus.
* In Kap. „4.8.5 Zustandsloser Dateizugriff“ muss „RESTful“ auch nicht zwingend erwähnt werden und kann also raus.

Grüße vom #opendataday @Berlin

**Comment by akuckartz** [comment]
@sokal Das wäre immerhin eine ehrliche Lösung. Eine andere Lösung besteht in der Rückgängigmachung des "Rückbaus von JSON-LD". Das würde dann eventuell auch eine Art Wiedervereinigung mit OpenGovLD (https://github.com/OpenGovLD/specs) ermöglichen.

**Comment by sterni24** [comment]
Ich verstehe diese Diskussion um des Kaisers Bart nicht mehr. Die OParl-API erfüllt m. E. RESTful Level 2 (siehe auch http://martinfowler.com/articles/richardsonMaturityModel.html). Irgendwann wird es einen Level 4 geben und JSON-LD ist dann ggf. auch nicht mehr RESTful.

**Comment by akuckartz** [comment]
Wie Martin Fowler in dem Artikel am Ende richtig schreibt:

> I should stress that the RMM, while a good way to think about what the elements of REST, is not a definition of levels of REST itself. Roy Fielding has made it clear that level 3 RMM is a pre-condition of REST. Like many terms in software, REST gets lots of definitions, but since Roy Fielding coined the term, his definition should carry more weight than most.

**Comment by lu-j** [comment]
REST ist kein Standard, sondern ein Programmierparadigma und es gibt es verschiedene Vorstellungen, was REST bedeutet und wie es umgesetzt werden sollte. 
Ich zum Beispiel denke bei REST zuerst an eine Schnittstelle, die mehrere HTTP-Methoden unterstützt (GET, POST, PUT, DELETE...). Da man bei OParl aber keinen schreibenden Zugriff hat, wird nur GET verwendet.
Auf dem Workshop haben wir beschlossen, dass in der Spezifikation beschrieben werden soll, welche Eigenschaften von OParl REST konform sind, zum Beispiel mit der Angabe des Levels im Maturity Model. Dann gibt es keine Missverständnisse mehr. Ich denke es ist überhaupt kein Problem, wenn wir OParl nicht mehr allgemein als "RESTful" bezeichnen.

**Comment by lu-j** [comment]
Ich habe das Kapitel "Restful" entfernt und die Anforderung der Zustandslosigkeit erst mal in das "HTTP und HTTPS" Kapitel geschrieben. Das ist zwar nicht der geeignetste Ort für diese Anforderung, aber ich will die Texte der Spezifikation sowieso grundlegend überarbeiten, danach werde ich nochmal schauen wo diese Anforderung am besten hinpasst.

Viele verstehen unter REST, dass die URLs alle im vorhinein bekannt sind, also das Sitzungen zum Beispiel immer unter "/meetings" abrufbar sind. Bei OParl können die URLs aber von jedem RIS selbst bestimmt werden. Ich denke insgesamt ist der Verweis auf REST in der OParl Spezifikation ist eher verwirrend, als hilfreich, daher habe ich ihn entfernt. Das jede Ressource eine eindeutige URL hat und der Zugriff zustandslos sein muss, sind die einzigen REST-Kriterien, die von OParl erfüllt werden, aber ich denke das trifft mittlerweile auf fast alle moderne Web-APIs zu. Die Facebook- oder Github-API erfüllen auch die REST-Kriterien erwähnen das aber ebenfalls nicht in der Dokumentation.

**Comment by akuckartz** [comment]
> Ich habe das Kapitel "Restful" entfernt

Da ich dieses Issue geöffnet hatte: Vor mir aus kann es jetzt geschlossen werden.
