### ISSUE TITLE
JSON Schema

### ISSUE THREAD

**Issue by stefanw** [OParl/spec#27]
Beispiele sind immer sehr gut und anschaulich. Ich würde mich aber dafür aussprechen zusätzlich ein [JSON-Schema](http://json-schema.org/) für die Schema-Validierung von Anfragen zu entwickeln.

Diese können dann auch für die Zertifizierung verwendet werden. Dieses Issue soll eigentlich nur JSON-Schema ins Spiel bringen und abfragen, ob es grundsätzliche Einwände gegen dieses Vorgehen gibt.

**Comment by akuckartz** [comment]
Offenbar hatte ich am 11.6.2014 den Milestone dieses Issue auf "FerneZukunft" versetzt. Warum ist mir nicht mehr klar.

**Comment by lu-j** [comment]
Das Schema ist mittlerweile komplett im JSON-Schema Format gespeichert, weil es die Arbeit an der Spezifikation erleichtert, es ist zum Beispiel möglich automatisch ein ER-Diagramm zu erstellen, siehe #283.
