### ISSUE TITLE
Umlenkung von https nach http ist Bad Practice und eventuell rechtswidrig

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#271]
Einer Anmerkung zu commit https://github.com/jayaree/specs/commit/8bc6440fb5c8f56e2a1089e15383fd60aac360b8 aus PR https://github.com/OParl/specs/pull/270

Es sollte offensichtlich sein wie die Frage dort zu beantworten ist. Eine Umlenkung von https nach http ist ein Musterbeispiel einer Bad Practice. Wer per https zugreift, der darf erwarten, dass der Datenverkehr dann nicht absichtlich unverschlüsselt erfolgt. Ein entsprechendes Vorgehen würde möglicherweise auch gegen Datenschutzgesetze verstoßen.

**Comment by akuckartz** [comment]
Open Data Needs HTTPS Too 
January 26, 2015 
https://konklone.com/post/open-data-needs-https-too

Securing the Web 
W3C TAG Finding 22 January 2015 
https://w3ctag.github.io/web-https/

**Comment by akuckartz** [comment]
Siehe auch:
https://https.cio.gov/

**Comment by lu-j** [comment]
Bei HTTPS Anfragen werden die Daten immer verschlüsselt übertragen oder die Verbindung kommt nicht zustande. Bei einer Umleitung von HTTPS zu HTTP antwortet der Server also verschlüsselt und teilt dem Client mit, dass die angefragte Ressource jetzt unter einer HTTP-URL verfügbar ist. Der Client kann dann selbst entscheiden, ob er der Umleitung folgt. Viele große Internetseiten haben eine Umleitung von HTTPS zu HTTP eingerichtet, daher kann ich mir nicht vorstellen, dass das gegen Datenschutzgesetze verstößt.

Aktuell ist in der Spec vorgeschrieben, dass jedes Objekt eine eindeutige URL als ID haben muss und nur unter dieser ID abrufbar sein sollte. Daher ist aktuell empfohlen, dass beim Abruf einer ähnlichen URL, zum Beispiel mit einem zusätzlichem Slash am Ende oder eben HTTPS statt HTTP, der Server auf die richtige, eindeutige URL umleitet.

Ich bin mit dieser Empfehlung auch nicht zufrieden. Es sollte sowieso nicht vorkommen, dass ein Client eine andere URL aufruft, als die vom Server ausgelieferte und falls doch, ist es meiner Meinung nach besser, wenn der Server mit einer Fehlermeldung antwortet, als mit einer Umleitung. Ich denke, dass das Routing in der Regel sowieso vom Webserver gemacht wird und RISe darauf auch kein Einfluss haben. Außerdem ist es empfohlen, dass ein Server Umleitungen benutzt, wenn er dem Client mitteilen will, dass die OParl API unter einer neuen URL erreichbar ist. Das bedeutet in der Regel, dass sich alle oder ein Teil der IDs geändert haben. Sobald ein Client eine Umleitung sieht, sollte er also seinen kompletten Datenbestand löschen und den Server neu crawlen. Daher sollte der Server nur umleiten, wenn es wirklich notwendig ist. Diese Problematik will ich aber in einem eigenen Issue behandeln.

Ich finde HTTPS auch sinnvoll und viele RISe sind sowohl unter HTTP als auch HTTPS erreichbar, daher sollten wir empfehlen, dass für die OParl-API-URL HTTPS verwendet wird.

**Comment by akuckartz** [comment]
> Viele große Internetseiten haben eine Umleitung von HTTPS zu HTTP eingerichtet, daher kann ich mir nicht vorstellen, dass das gegen Datenschutzgesetze verstößt.

Wenn du mir drei nennst, dann suche ich mir eine davon aus und dann sehen wir, wie lange der Betreiber das noch macht (je "größer" der Betreiber, desto besser ;-)

> Ich bin mit dieser Empfehlung auch nicht zufrieden. Es sollte sowieso nicht vorkommen, dass ein Client eine andere URL aufruft, als die vom Server ausgelieferte und falls doch, ist es meiner Meinung nach besser, wenn der Server mit einer Fehlermeldung antwortet, als mit einer Umleitung.

Ich bin nicht sicher, ob wir hier einer Meinung sind. Ich bin nur gegen Umleitungen von https nach http (genauer: nach http ohne TLS, siehe Hinweis auf TimBL ganz unten). Andere Umleitungen können sinnvoll sein (z.B. im Rahmen von Content Negotiation, aber das ist ein anderes Thema.) Dafür relevant sind aber nur Umleitungen von URLs, die der Server mitgeteilt hat. Andere URLs liegen dann gewissermaßen außerhalb des Universums. Was beim Zugriff darauf passiert kann man durchaus undefiniert lassen. Fehler sind eine Möglichkeit, es kann aber auch gute Gründe für Weiterleitungen geben.

> Außerdem ist es empfohlen, dass ein Server Umleitungen benutzt, wenn er dem Client mitteilen will, dass die OParl API unter einer neuen URL erreichbar ist. Das bedeutet in der Regel, dass sich alle oder ein Teil der IDs geändert haben. Sobald ein Client eine Umleitung sieht, sollte er also seinen kompletten Datenbestand löschen und den Server neu crawlen.

Das ist noch ein anderes Thema. Wenn die IDs URLs sind, dann kann ich davon nur abraten. Siehe u.a. [Cool URIs don't change](http://www.w3.org/Provider/Style/URI.html).

> Diese Problematik will ich aber in einem eigenen Issue behandeln.

Gut.

> Ich finde HTTPS auch sinnvoll und viele RISe sind sowohl unter HTTP als auch HTTPS erreichbar, daher sollten wir empfehlen, dass für die OParl-API-URL HTTPS verwendet wird.

Damit sind wir einer Meinung.

Abschliessend noch ein Hinweis zu einem Kommentar zu dem ich mir noch keine fundierte Meinung gebildet habe: [Web Security - "HTTPS Everywhere" harmful](http://www.w3.org/DesignIssues/Security-NotTheS.html). Der Vorschlag dort läuft darauf hinaus, TLS als Protokoll zu verwenden, aber nicht "https" sondern "http" als URL-Schema. Wenn ich dazu mehr sagen kann melde ich mich noch mal.

**Comment by konstin** [comment]
Wäre es nicht einfach möglich, https verpflichtend zu machen? Damit wäre das Problem mit Umleitungen von https nach http und umgekehrt nicht mehr vorhanden. Für die RIS-Betreiber sollte es afaik auch kein Problem sein, https anzubieten, da keine Inhalte von Drittanbietern eingebunden werden müssen, die nur per http verfügbar sind.

> Abschliessend noch ein Hinweis zu einem Kommentar zu dem ich mir noch keine fundierte Meinung gebildet habe: Web Security - "HTTPS Everywhere" harmful. Der Vorschlag dort läuft darauf hinaus, TLS als Protokoll zu verwenden, aber nicht "https" sondern "http" als URL-Schema. Wenn ich dazu mehr sagen kann melde ich mich noch mal.

Die Idee ist an sich ganz gut, aber https bietet den einfachen Vorteil, dass man sich ohne weitere Tests sicher sein kann, dass man eine gesicherte Verbindung nutzt. Außerdem verhindert es, dass jemand durch einen man-in-the-middle-Angriff eine ungesicherte Verbindung erzwingt, obwohl der Server Verschlüsselung anbietet.

**Comment by akuckartz** [comment]
@konstin Ja, da wären noch Änderungen auch im http-Protokoll notwendig. Das von TimBL dargelegte Problem betrifft vorangig die Umstellung bereits bestehender http-URLs, nicht die Einführung ganz neuer https-URLs.

Ein wenige Tage altes Dokument der W3C Technical Architecture Group (TAG) empfiehlt erneut die Verwendung von https: http://www.w3.org/2001/tag/doc/encryption-finding/ (TimBL hat laut Protokoll an den Diskussionen teilgenommen):
> the TAG strongly supports the use of HTTPS to assure users that the parties they're interacting with are really who they say they are, and that their communications have not been tampered with.

**Comment by lu-j** [comment]
Eine Umleitung von HTTPS auf HTTP ist durchaus üblich, auch die Webseite des
W3C macht das so: [https://www.w3.org](https://www.w3.org) (das "www." in der
URL ist wichtig, sonst kommt keine Verbindung zustande). Das ist meiner Meinung
nach für OParl aber nicht weiter relevant, denn wie ich bereits geschrieben
habe, muss ein Client sowieso auf Umleitungen reagieren, sollte ihnen nicht
automatisch folgen und er kann auch selbst entscheiden, ob er einer Umleitung
auf eine HTTP URL folgen will. Will ein Client nur verschlüsselte Verbindungen
zulassen, reicht es also vor jeder Anfrage zu überprüfen, ob es sich um eine
HTTPS URL handelt.

@akuckartz: Den Abschnitt, den du in diesem Issue kritisiert hast, beschreibt das Szenario,
dass der Server nur HTTP-URLs ausgibt und der Client trotzdem eine HTTPS-URL
anfragt, also eine URL, die wie du es beschrieben hast, außerhalb des
Universums liegt. Solche Szenarien möchte ich undefiniert lassen, daher will
ich den Abschnitt komplett entfernen.

Wenn eine OParl-API die unter HTTPS erreichbar war, nur noch unter HTTP zu
erreichen ist, finde ich eine Umleitung besser, als keine Möglichkeit zu haben,
automatisch über die neue URL informiert zu werden. Dass sich die URL eines RIS
ändert, kommt leider durchaus vor, zum Beispiel haben sich die URLs der
Berliner RISe vor etwa einem Jahr geändert. Das grundsätzliche Thema
Umleitungen, möchte ich aber wie bereits gesagt in einem eigenen Issue
behandeln.

@konstin: Ich finde die Verwendung von HTTPS auch wichtig und hoffe, dass bald
alle RISe unter HTTPS erreichbar sind. Ich vermute allerdings, wenn ein RIS in
die Webseite der Kommune eingebettet ist, ist die Unterstützung von HTTPS etwas
aufwendiger. Die Implementierung von OParl 1.0 soll so simpel und kostengünstig
wie möglich sein, daher sollen auch nur die Anforderungen zwingend sein, die
auch tatsächlich zwingend notwendig sind. Wenn sich die aktuelle Entwicklung
fortsetzt und HTTPS zum Standard wird, dann sollten wir aber für eine zukünftige
Version von OParl auf jeden Fall nochmal in Betracht ziehen, HTTPS zwingend
vorauszusetzen.

**Comment by akuckartz** [comment]
@lu-j Eine Umleitung von HTTPS auf HTTP ist durchaus üblich, auch die Webseite des
 W3C macht das so: https://www.w3.org

1. Good catch! Ein ärgerliches Negativbeispiel. Ich werde das als Problem einreichen.
1. Die Website unterliegt nicht dem deutschen Datenschutzrecht.

> wenn ein RIS in die Webseite der Kommune eingebettet ist, ist die Unterstützung von HTTPS etwas
 aufwendiger.

Ja, ich kenne die Probleme mancher Kommune. Die unterliegen aber deutschem Datenschutzrecht. Vorschlag: Da ihr ja ohnehin einen Abschnitt zu Datenschutz aufnehmen wollt, könnt ihr darin auf die Problematik hinweisen.

**Comment by akuckartz** [comment]
Siehe auch #90

**Comment by konstin** [comment]
> Ich finde die Verwendung von HTTPS auch wichtig und hoffe, dass bald alle RISe unter HTTPS erreichbar sind. Ich vermute allerdings, wenn ein RIS in die Webseite der Kommune eingebettet ist, ist die Unterstützung von HTTPS etwas aufwendiger. Die Implementierung von OParl 1.0 soll so simpel und kostengünstig wie möglich sein, daher sollen auch nur die Anforderungen zwingend sein, die auch tatsächlich zwingend notwendig sind. Wenn sich die aktuelle Entwicklung fortsetzt und standardmäßig HTTPS verwendet wird, dann sollten wir aber für eine zukünftige Version von OParl auf jeden Fall nochmal in Betracht ziehen, HTTPS zwingend vorauszusetzen.

Dass es bei den webseiten der Kommunen verschiedene Probleme bei der Unterstützung von https gibt, ist mir bekannt. Da aber OParl meines Wissens nicht in webseiten integriert werden soll, dürfte es an dieser Stelle keine Probleme geben. Außerdem sollte es bei der Entwicklung einer neuen Schnittstelle nicht schwer sein, einen https-Zugriff einzurichten. Die Implementierung wird damit in einigen Fällen sogar einfacher, da man sich keine Sorgen um Umleitungen oder Resourcen, die unter zwei verschiedenen URLs erreichbar sind, machen muss.

**Comment by the-infinity** [comment]
Habe ich nun als klaren Hinweis in das Kapitel Datenschutz eingearbeitet: https://github.com/OParl/spec/commit/185adb2ee45e79260f4b396225d213d6e45cc77f

**Comment by akuckartz** [comment]
@lu-j Das W3C hat nun auch endlich durchgehend auf https umgestellt: https://www.w3.org/blog/2016/01/w3-org-supporting-https-and-hsts/
