### ISSUE TITLE
Ergebnisse des Workshop vom 1.4.2015 als Issues veröffentlichen

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#273]
In http://oparl.org/2015/03/17/revival-oparl-wird-groesser-und-ist-auf-dem-weg-zu-version-1-0/ wurde zu dem Workshop angekündigt:
> alle Ergebnisse werden transparent via Github kommuniziert.
Ab Mitte April wird es einen Monat lang noch ein letztes Mal die Möglichkeit geben, Stellungnahmen zu geben, um ggf. noch vorhandene kritische Fehler zu beseitigen.

Bisher wurde kein einziges Ergebnis des Workshops veröffentlicht. Wenn man von Änderungen der Historie und der Entfernung von Fragen absieht, dann ist der Spezifikationsentwurf aktuell (21.4.2015) immer noch auf dem Stand von Anfang Juli 2014 .

Siehe auch #272

**Comment by akuckartz** [comment]
Ping. Der Workshop ist inzwischen seit zwei Monaten vorbei...

**Comment by akuckartz** [comment]
Inzwischen gibt es die ersten angekündigten Issues:
https://github.com/OParl/specs/labels/Workshop2015

**Comment by eFrane** [comment]
(Duplikat von #272)

**Comment by akuckartz** [comment]
@eFrane Nein, das sind zwei verschiedene Issues. hier in #273 geht es um _Output_ des Workshop vom 1.4.2015 und bei #272 um schriftlichen _Input_, der nach meinen Informationen von einem Hersteller eingereicht und anschließend berücksichtigt, aber der Öffentlichkeit bisher nicht zugänglich gemacht wurde. Keines der beiden Issues ist bisher erledigt.

Ich bitte also darum, dieses Issue wieder zu öffnen.

/cc @lu-j

**Comment by the-infinity** [comment]
Ist mittlerweile erledigt. Daher: closed.
