### ISSUE TITLE
Feldbenennung Meeting:chairPerson / Meeting:scribe

### ISSUE THREAD

**Issue by eFrane** [OParl/spec#274]
Die Felder `chairPerson` und `scribe` von `Meeting` beziehen sich jeweils nur auf eine `Person`. Ich fände es daher besser, wenn sie dem gleichen Bennenungsschema folgen würden. Ergo entweder `scribe` und `chair` oder eben `scribePerson` und `chairPerson`. Persönlich würde ich die erstere, kürzere Variante bevorzugen.

**Comment by akuckartz** [comment]
Sowohl Vorsitz also auch Protokollführung können sich in einer Sitzung ändern. OpenGovLD wird deshalb weder für `chairPerson`/`chair` noch für `scribe` eine Beschränkung der Kardinalität festlegen.

**Comment by eFrane** [comment]
Es geht mir weniger um die Kardinalität, wobei eine Änderung auf `1..n` oder gar `*` durchaus zu überdenken ist, sondern um die Benennung der Felder. Felder, die die gleiche Kardinalität haben, sollten im Allgemeinen dem selben Namensschema folgen.

**Comment by akuckartz** [comment]
Voraussichtlich wird in `OpenGovLD` die hier vorgeschlagene Umbenennung der Property `chairPerson` -> `chair` durchgeführt werden. Die ursprüngliche Benennung hatte ich letztes Jahr in OParl vorgeschlagen und aufgenommen, finde die kürzere an dieser Stelle jetzt aber auch besser.

**Comment by akuckartz** [comment]
Nebenbei: In `schema.org` gibt es gegenwärtig weder noch, sondern stattdessen https://schema.org/organizer

**Comment by lu-j** [comment]
Ich finde auch chair besser. Allerdings bin ich dafür chairPerson und scribe zu entfernen, darauf wurde sich auch schon in #211 geeinigt. Soweit ich weiß wird der Vorsitzende (und die Stellvertreter) am Anfang der Legislaturperiode gewählt, daher ändert sich der Vorsitz nicht jede Sitzung. Wer der Vorsitzender ist, wird bereits in Membership gespeichert. Wer durch wen auf einer Sitzung vertreten wurde, wollen wir in OParl 1.0 noch nicht speichern. Dass Schriftführer im RIS gespeichert werden, habe ich bis jetzt nur in den Räten der Berliner Bezirke gesehen. Wenn ich das richtig verstanden habe, werden sie aber auch am Anfang der Legislaturperiode gewählt, daher ist das ebenfalls schon in Membership gespeichert.

**Comment by akuckartz** [comment]
Ich habe dazu keine ausgeprägte Meinung.

Zur Info: OpenGovLD strebt eine international brauchbare Lösung für Anwesenheitslisten an (https://github.com/OpenGovLD/specs/issues/76). Dazu gehören auch Rollen wie Vorsitz oder Schriftführung. Das hat gegenwärtig keine besonders hohe Priorität - was sich aber insbesondere im Kontext der Modellierung namentlicher Abstimmungen ändern kann.

**Comment by eFrane** [comment]
Ich bin dagegen, die Felder ganz zu entfernen. Denn, obwohl diese Positionen organisationsgebunden sind, haben wir momentan keine Möglichkeit, bestimmte Felder einer Organisation nur für spezifische Legislaturperioden zu setzen. Auch den Weg über Memberships finde ich schwierig, da die Abfrage der gesuchten Information komplexer als nötig wird. Letzteres heißt natürlich nicht, dass wir die Metadaten aus Membership entfernen sollten.

**Comment by akuckartz** [comment]
> Auch den Weg über Memberships finde ich schwierig, da die Abfrage der gesuchten Information komplexer als nötig wird.

Die Abfrage-Komplexität folgt der gewählten Technik. Mit Linked Data Techniken ist die Formulierung solcher Abfragen jedenfalls fast trivial.

**Comment by sterni24** [comment]
Die Darstellung Vorsitz und Schriftführung in Meeting können meiner Meinung nach entfallen. Eine korrekte Darstellung gehört für mich, wenn überhaupt, in ein eigenständiges Objekt  Anwesenheitslisten. Sonderfälle wie Wechsel in einer Sitzung ab einem bestimmten TOP oder zu einer bestimmten Uhrzeit sind zur Zeit nicht darstellbar. Da hilft auch LD nicht weiter.

Wer es genau wissen möchte, sollte ins Protokoll schauen!

**Comment by lu-j** [comment]
Mittlerweile haben wir uns darauf geeinigt beide Felder zu entfernen und ich habe die Änderungen eingearbeitet. Daher schließe ich dieses Issue.
