### ISSUE TITLE
Unterstützung von HTTP-HEAD Anfragen für Dateianhänge soll nicht erforderlich sein

### ISSUE THREAD

**Issue by lu-j** [OParl/spec#277]
Auf dem Workshop wurde beschlossen:
Aktuell ist die Unterstützung für HTTP-HEAD Anfragen zwingend, obwohl es nicht
für die verbreiteten Cachingverfahren (If-Modified-Since oder ETag) benötigt
wird. Wie in #276 bereits erwähnt, werden Dateianhänge wahrscheinlich nicht vom Webserver, sondern von der RIS-Software ausgeliefert, damit die Zugriffsberechtigung geprüft werden kann. Die Unterstützung von HEAD Anfragen muss vermutlich erst in die RIS-Software implementiert werden, was eine unnötig hohe Anforderung wäre. Daher soll diese Anforderung entfernt werden.

Wir bitten um Feedback!

**Comment by akuckartz** [comment]
Hinweis: Nach aktuellem Stand wird OpenGovLD auf der [Linked Data Platform 1.0 (LDP) Spezifikation](http://www.w3.org/TR/ldp/) aufbauen. Diese enthält in Abschnitt 4.2.6.1 diese Anforderung (ob sinnvoll oder nicht sei dahingestellt):

> LDP servers MUST support the HTTP HEAD method.

**Comment by akuckartz** [comment]
Aus RFC 7231:

> All general-purpose servers MUST support the methods GET and HEAD. All other methods are OPTIONAL.

https://tools.ietf.org/html/rfc7231#section-4.1

Bei HEAD muss von Servern schlicht _weniger_ getan werden als bei GET. Insofern ist für mich nicht nachvollziehbar, weshalb diese Anforderung der http-Spezifikation für ein RIS signifikanten Implementierungs-Aufwand erfordern soll.

**Comment by the-infinity** [comment]
HEAD wird nun nicht mehr erzwungen: https://github.com/OParl/specs/commit/ffe70c2a63719992cc1b3d849c857a966eb2e4b0 . Da Dateien eh nur bei Modifikation dies File-JSON abgerufen werden und auch If-Modified-Since oder ETag optional sind, macht es keinen Sinn mehr, wenn HEAD noch verpflichtend ist.

**Comment by lu-j** [comment]
Ich denke ich habe mit "unnötig hohe Anforderung" oben die falschen Worte gewählt. Ich wollte nicht sagen, dass es besonders schwer ist HEAD-Anfragen zu unterstützen. Ich wollte stattdessen sagen, dass nur die Anforderungen zwingend sein sollen, die auch wirklich notwendig für OParl sind, um unnötige Arbeit zu vermeiden.

Auch was die empfohlenen Anforderungen betrifft, möchte ich die Spezifikation kompakt halten und nur die Anforderungen aufnehmen, die uns wirklich einen Mehrwert bieten. HEAD-Anfragen werden nicht für If-Modified-Since oder ETag benötigt und mir ist kein Szenario eingefallen, bei dem HEAD-Anfragen für Dateidownloads sinnvoll währen. Möchte ein Validator übeprüfen, ob die Dateien auch wirklich verfügbar sind, ist es besser, eine richtige GET-Anfrage zu machen und zumindest die ersten Bytes einer Datei herunterzuladen, als sich nur auf die Antwort einer HEAD-Anfrage zu verlassen. Daher will ich den Abschnitt zu HTTP-HEAD entfernen. Damit will damit ich natürlich nicht sagen, dass HEAD-Anfragen nicht unterstützt werden sollen, sondern nur, dass sie für OParl nicht relevant sind.

**Comment by akuckartz** [comment]
> Daher will ich den Abschnitt zu HTTP-HEAD entfernen. Damit will damit ich natürlich nicht sagen, dass HEAD-Anfragen nicht unterstützt werden sollen, sondern nur, dass sie für OParl nicht relevant sind.

Dann sind wir im _Ergebnis_ einer Meinung, denn eine Spezifikation die http verwendet muss deren Spezifikation weder wiederholen noch sollte sie sie modifizieren. Falls ein Hersteller allerdings erklärt, dass seine Software http unterstütze, diese aber kein HEAD unterstützt, dann könnte er ein Problem bekommen.

**Comment by lu-j** [comment]
Ich denke wir sind uns einig, dass wir HTTP-HEAD nicht als Anforderung in der Spezifikation brauchen. Den Abschnitt zu HTTP-HEAD habe ich bereits entfernt, daher schließe ich das Issue.
