### ISSUE TITLE
Neues Team und konkrete Zielsetzung für OParl 1.0

### ISSUE THREAD

**Issue by lu-j** [OParl/spec#278]
Es gibt gute Neuigkeiten! Zusammen mit @the-infinity und @eFrane werde ich nach langer Pause die Arbeit von @marians fortsetzen und die Spezifikation überarbeiten, da es noch ein paar Probleme im aktuellen Entwurf gibt. Wir haben schon einen Workshop veranstaltet und dort einige Änderungen beschlossen, weitere Informationen gibt es auf http://oparl.org.

Wir wollen OParl 1.0 möglichst einfach halten und weitere Funktionen erst in kommenden Versionen hinzufügen. In der Spezifikation fehlen aktuell die üblichen Abfragemöglichkeiten, es gibt zum Beispiel keine Such- und Sortiermöglichkeit. Wir könnten versuchen diese Funktionen zu integrieren, das würde allerdings einiges an Zeit kosten und den Implementierungsaufwand erhöhen. Diese Funktionen sollen erst in einer zukünftigen Version von OParl integriert werden. Stattdessen wollen wir uns in Version 1.0 darauf konzentrieren, dass es unkompliziert möglich ist, die benötigten Daten aus einem RIS in eine eigene Datenbank zu laden. Die gewünschten Abfragen können dann lokal in der eigenen Datenbank gemacht werden. Mit der OParl API soll es auch wie gehabt möglich sein, den Datenbestand zu updaten.

Wir wollen einen OParl-Server über die Open Knowledge Foundation bereitstellen, der die Daten aus den RIS-Systemen spiegelt und über OParl 1.0 hinausgehende Abfragemöglichkeiten bietet. Der Server kann also von Webentwicklern genutzt werden, die die OParl-Daten nicht in eine eigene Datenbank laden wollen und daher eine erweiterte API brauchen. Mit dem Server wollen wir auch Funktionen ausprobieren, die Bestandteil von zukünftigen OParl Versionen werden könnten.

Folgende Ziele schlagen wir für OParl 1.0 vor:

1.  Es soll möglich sein, alle Objekte oder nur bestimmte Objekttypen (z.B. nur Drucksachen) abzufragen.
2.  Dabei soll es möglich sein den Zeitraum einzugrenzen. Man soll also alle Objekte abfragen können, die nach einem wählbaren Zeitpunkt erstellt oder geändert wurden. Das ist praktisch, falls man zum Beispiel nur die Objekte aus der aktuellen Legislaturperiode braucht.
3.  Es soll möglich sein, die neusten Änderungen abzufragen um den lokalen Datenbestand upzudaten (das lässt sich gut zusammen mit Ziel 2 lösen).
4.  OParl soll leicht und kostengünstig implementierbar sein.

Mit den auf dem Workshop besprochenen Änderungen würden wir diese Ziele schon erreichen. Für alle besprochenen Änderungen werden wir weitere Issues eröffnen, wir freuen uns über Feedback!

**Comment by marians** [comment]
@lu-j Danke dafür, dass Ihr OParl weiter treibt! Und +1 für Pragmatismus und geringeren Funktionsumfang, wenn damit das Release vereinfacht/ermöglicht wird.

**Comment by akuckartz** [comment]
> Für alle besprochenen Änderungen werden wir weitere Issues eröffnen

Das war bereits am 17.3.2015 angekündigt worden. Bisher wurden aber nur für einen kleinen Teil der besprochenen Änderungen Issues eröffnet: 3 Stück. Gleichzeitig wurde #273 fälschlicherweise geschlossen.

**Comment by akuckartz** [comment]
> Wir wollen einen OParl-Server über die Open Knowledge Foundation bereitstellen, der die Daten aus den RIS-Systemen spiegelt und über OParl 1.0 hinausgehende Abfragemöglichkeiten bietet. Der Server kann also von Webentwicklern genutzt werden, die die OParl-Daten nicht in eine eigene Datenbank laden wollen und daher eine erweiterte API brauchen. Mit dem Server wollen wir auch Funktionen ausprobieren, die Bestandteil von zukünftigen OParl Versionen werden könnten.

Das ist zwar verständlich und es mag Gründe geben, warum das sinnvoll ist.

Dennoch wird damit ein objektiver Interessenkonflikt geschaffen. Die _selbe_ Organisation, die die Spezifikation verantwortet, betreibt dann auch einen zentralen Server mit dem Ziel, dass dieser von Webentwicklern genutzt wird. Aufgrund meiner Erfahrungen mit einem Mitglied des Vorstands der OKF DE halte ich es nicht für ausgeschlossen, dass sich dieser Interessenkonflikt möglicherweise auch auswirken wird.

Zudem wurde bisher nicht offen gelegt, was genau die Rolle von _Vitako_ bei OParl ist.

**Comment by eFrane** [comment]
- Die Schließung des Issues war vielleicht etwas voreilig, aber nichtsdestotrotz stehe ich dazu, dass es nicht notwendig ist zwei fast identische Issues zum selben Thema aufzuhaben. Stattdessen wäre es besser, in einem sowohl auf Input als auch auf Auswirkungen auszugehen. 
- Der Server bei der OKF ist - was auch im Text steht - zuvorderst unsere Experimentierwiese um die Entwicklung der Spezifikation vorantreiben zu können. Wer als (Web-)entwickler bedenken hat, diesen Server als Hauptquelle zu nutzen wird nicht davon abgehalten, bei den originalen Quellen Daten zu laden und eigene Infrastruktur aufzusetzen. 

*Zu den anderen Fragestellungen muss sich @lu-j äußern.*

**Comment by akuckartz** [comment]
> Stattdessen wollen wir uns in Version 1.0 darauf konzentrieren, dass es unkompliziert möglich ist, die benötigten Daten aus einem RIS in eine eigene Datenbank zu laden.

Damit hat OParl dann ein Ziel von OpenGovLD übernommen. Sehr schön, auch wenn das erst nach etwa einem Jahr Verzögerung erfolgt. Siehe https://github.com/OpenGovLD/specs/issues/4 und die Diskusssion unter #64 (dieses OParl-Issue ist ein weiteres welches fälschlicherweise geschlossen wurde). Jetzt fehlt nur noch die (unverstümmelte!) Übernahme der Lösung :-)

**Comment by the-infinity** [comment]
1) Vitako ist Unterstützer auf der ausführenden Seite. Irgendwer muss das nun einmal auch in den Städten umsetzen, und wer wäre dafür besser geeignet als ein Netzwerk kommunaler IT-Dienstleister?
2) Bislang ist kein Exportformat definiert, und soweit ich weiß, gibt es auch keine Pläne dazu. Der obrige Satz beschreibt vor allem die Strategie, den Abruf via API schnell und effizient zu machen. Das betrifft v.a. Updates.
3) Natürlich kann auch jeder andere Mensch einen RIS-Server betreiben. Allerdings wüsste ich niemanden abseits der OKF, der Serverkapazitäten und Ressourcen für die Weiterentwicklung bereitstellen könnte, also spielt die OKF eine entscheidende Rolle in dem Prozess.

Ziel ist wirklich Pragmatismus pur + KISS. Das ist im Interesse nahezu aller Beteiligten - der Webentwickler, die daraus Anwendungen machen wollen, der RIS-Hersteller, die OParl implementieren müssen, der Städte, die das Implementieren bezahlen müssen.

**Comment by konstin** [comment]
Schön, dass an diesen Projekt auch wieder gearbeitet wird!

Die Möglichkeit, nach Dokumententypen zu filtern, dürfte zumindest für München Transparent schwer umzusetzten sein, da im Münchner RIS nicht immer ein Dokumententyp angegeben ist.

**Comment by akuckartz** [comment]
> 1) Vitako ist Unterstützer auf der ausführenden Seite. Irgendwer muss das nun einmal auch in den Städten umsetzen, und wer wäre dafür besser geeignet als ein Netzwerk kommunaler IT-Dienstleister?

Das wirft (zumindest bei mir) die Frage auf, warum Vitako im Gegensatz zu anderen Unterstützern (http://oparl.org/ueber-oparl/) gleichrangig mit der OKF DE herausgestellt wird.

> 2) Bislang ist kein Exportformat definiert, und soweit ich weiß, gibt es auch keine Pläne dazu.

Dann habe ich anscheinend Punkt 1 des Ergebnis-Protokolls des Workshops missverstanden. Schade: Dann wird ein Export-Format ein Alleinstellungsmerkmal von OpenGovLD sein.

> Allerdings wüsste ich niemanden abseits der OKF, der Serverkapazitäten und Ressourcen für die Weiterentwicklung bereitstellen könnte,

Eine interessante Aussage - auch und gerade im internationalen Kontext !

**Comment by akuckartz** [comment]
Nun noch grundsätzlichere Kritik. Das Vorhaben zielt gegenwärtig in mehrfacher Hinsicht auf die Schaffung einer Insellösung ab:

- Es ist ein rein nationales Spezifikationsprojekt, internationale Projekte werden nicht berücksichtigt (namentlich Popolo, OpenGovLD, schema.org).

- Es handelt sich um eine Sammlung technischer Sonderlösungen. Anstatt auf in der Linked Open Data Community erarbeitete Lösungen zurückzugreifen oder diese weiter zu entwickeln werden völlig eigene angestrebt. Das führt im Ergebnis sowohl zu Verzögerungen als auch zu Behinderungen der Weiterentwicklung.

Auf einem Workshop des BMI wurde vor ein paar Wochen "kein deutscher Sonderformat-Weg" als eine Anforderung an Open Data Formate festgehalten (https://pad.okfn.org/p/Mitschrift_ODAP_Auftakt_Workshop). Eine andere etwas flapsige Formulierung dafür ist "deutsche Verwaltungssonderlocken". Solche "Sonderlocken" oder "deutschen Sonderformat-Wege" werden nicht dadurch besser, dass sie teilweise oder weitgehend außerhalb der Verwaltung mit Beteiligung und unter der Federführung der OKF DE entstehen. Die Verantwortung dafür liegt nach meiner Überzeugung _nicht_ bei den unmittelbar an dem Projekt beteiligten Personen, sondern vorrangig beim Vorstand der OKF DE. Außerdem zeigt sich hier auch das Phänomen der [Pfadabhängigkeit](https://de.wikipedia.org/wiki/Pfadabh%C3%A4ngigkeit).

**Comment by konstin** [comment]
> Das Vorhaben zielt gegenwärtig in mehrfacher Hinsicht auf die Schaffung einer Insellösung ab:
> Es ist ein rein nationales Spezifikationsprojekt, internationale Projekte werden nicht berücksichtigt (namentlich Popolo, OpenGovLD, schema.org).

Meiner Ansicht wäre selbst eine "Insellösung" schon ein gewaltiger Fortschritt, da es nach meinem Wissen bisher überhaupt keine nutzbare, standartisierte API gibt. schema.org und Popolo stellen für mich keine Alternativen dar, da diese einen anderen Fokus als Ratsinformationssysteme haben. OpenGovLD ist eine nicht mehr wirklich aktive Weiterentwicklung von OParl, die aber auch noch nicht fertig ist.

Außerdem wäre es sehr kompliziert und langwierig, eine Lösung zu entwickeln, die wirklich weltweit anwendbar ist, weshalb ich auch eher für ein einfaches, aber funktionierendes OParl 1.0 bin.

**Comment by akuckartz** [comment]
@konstin Tatsächlich ist die Ausgabe der Daten von Ratsinformationssystemen eine der Hauptanwendungsgebiete von Popolo. Wobei diese Daten fast immer durch Scraper rekonstruiert werden.

OpenGovLD ist konstant aktiv. Allerdings müssen die zahlreichen Ergebnisse des letzten Jahres noch in ein oder mehrere (kurzes!) Dokumente gegossen werden. In den letzten Monaten hatte ich gedacht, dass OParl schneller von der Stelle käme. Inzwischen sieht es für mich so aus, als wenn OpenGovLD noch vorher ein brauchbares Stadium erreichen würde.

Der Begriff "einfach" in Zusammenhang mit Spezifikationen ist vieldeutig. Darauf gehe ich hier aber nicht erneut ein.

> Außerdem wäre es sehr kompliziert und langwierig, eine Lösung zu entwickeln, die wirklich weltweit anwendbar ist

Tatsächlich ist es sogar _einfacher_ eine "einfache" Lösung zu entwickeln, wenn sie möglichst von Anfang an die weltweite Anwendbarkeit zu Ziel hat. Denn dadurch fallen unnötige Einschränkungen und Kanten eher auf und können abgeschliffen werden. Popolo erreicht dies z.B. durch die Verwendung der [Organization Ontology des W3C](http://www.w3.org/TR/vocab-org/). Ein Ziel dieser Ontologie war die Schaffung ebenso einfacher wie mächtiger Ausdrucksmöglichkeiten. Alleine in diese eine Ontologie wurde bereits mehr Aufwand gesteckt als in OParl und OPenGovLD zusammen. Ich hatte sie in der ersten Hälfte des Jahres 2014 in OParl aufgenommen, um verschiedene Probbleme zu lösen. Ich bin gespannt was davon letztendlich übrig bleibt ;-)

**Comment by lu-j** [comment]
@konstin: Wir teilen deine Meinung. Wir wollen OParl 1.0 erst mal so simpel und kostengünstig wie möglich halten. In kommenden Versionen wollen wir aber die Funktionalität von OParl erweitern und dann auch über Themen wie Internationalisierung oder Linked Data nachdenken. Ich werde demnächst auch nochmal ausführlicher auf unsere Ziele für OParl 1.0 eingehen.

Das mit den Dokumenttypen ist ein Missverständnis: es soll die Möglichkeit geben, jeweils eine Listenausgabe für jeden *Objekt*typ abzurufen, nicht *Dokument*typ. Objekttypen in OParl sind zum Beispiel Meeting (=Sitzung), AgendaItem (=Tagesordnungspunkt) oder Paper (=Drucksache/Vorlage). Ein Objekttyp in OParl entspricht in der Regel einer Tabelle in einer relationalen Datenbank.
