### ISSUE TITLE
Markenrechte "OParl"

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#281]
Wem gehört die Marke "OParl" ? Gibt es dazu verbindliche Vereinbarungen oder Aussagen ?

**Comment by the-infinity** [comment]
Nach einigen E-Mails: Es gibt keine Markenanmeldung. Allerdings wird der Begriff OParl aktiv überwacht, so dass notfalls Widerspruch gegen eine Markenanmeldung eingelegt werden könnte.
