### ISSUE TITLE
Kardinalitätsangaben überarbeiten

### ISSUE THREAD

**Issue by lu-j** [OParl/spec#282]
Auf dem Workshop wurde beschlossen:
Die Angabe der Kardinalitäten hat keinen Mehrwert. Falls mindestens ein Wert vorhanden sein muss, ergibt sich das aus der Deklaration "ZWINGEND". Falls auch mehr als ein Wert vorhanden sein kann, ergibt sich das aus dem Datentyp Array. Daher soll die Angabe der Kardinalitäten entfernt werden.

Wir bitten um Feedback!

**Comment by lu-j** [comment]
Der Vorschlag kam auf dem Workshop von mir. Was ich mittlerweile sinnvoll finde, sind Kardinalitäten, so wie sie in der Datenbankmodellierung üblich sind, also "1:1", "1:n", "n:1" und "n:m". Diese Art der Kardinalität kann man aktuell häufig nur aus dem Zusammenhang erkennen, was unpraktisch ist, wenn man zum Beispiel automatisiert ein ER-Diagramm erstellen will (siehe auch #283).

**Comment by akuckartz** [comment]
> Falls auch mehr als ein Wert vorhanden sein kann, ergibt sich das aus dem Datentyp Array. 

That is a problem, not a feature. Während bei JSON-LD und anderen RDF-Serialisierungen die Kardinalität in der Ontologie festgelegt wird, wird sie nach aktuellem Stand in OParl durch die Syntax festgezurrt - was zukünftige Modifikationen erheblich erschwert.

**Comment by eFrane** [comment]
Ich schließe das, weil die implementierenden Issues #283 und #286 bereits geschlossen sind.
