### ISSUE TITLE
Datenmodell im JSON Schema Format speichern

### ISSUE THREAD

**Issue by lu-j** [OParl/spec#283]
Das Datenmodell ist aktuell nicht maschinenlesbar in Markdown geschrieben. Ich will das Datenmodell in das JSON Schema Format übertragen. Aus JSON Schema können wir automatisch ein ER Diagramm oder Markdown Tabellen für das Schema Kapitel generieren lassen. Auch Clients und der Validator können das JSON Schema verwenden. Der Vorteil wäre, dass man bei Änderungen am Datenmodell nur das JSON Schema anpassen muss und den Rest automatisch neu generieren lassen kann. Es ist vor allem eine Arbeitsersparnis, inhaltlich wird sich dadurch nichts an der Spezifikation ändern.

Allerdings kann man mit JSON Schema nicht die Beziehung zwischen zwei OParl Objekten abbilden. Wir können JSON Schema aber mit den folgenden drei Eigenschaften erweitern (eigene Erweiterungen sind in JSON Schema erlaubt):

- **ref**: Objekttyp der referenziert wird
- **backref**: Name der Eigenschaft die vom referenzierten Objekt auf dieses Objekt zurück referenziert (falls vorhanden) 
- **cardinality**: die Kardinalität, habe ich im Beispiel gleich in der Form angegeben, wie ich sie in #282 vorgeschlagen habe.

Hier ein JSON Schema Beispiel für AgendaItem: die "meeting" Eigenschaft referenziert ein Meeting Objekt. Im Meeting Objekt gibt es die die Eigenschaft "agendaItem" die auf AgendaItems zurück referenziert.

    {
        "title": "AgendaItem",
        "properties": {
            "name": {
                "description":"Das Thema des Tagesordnungspunktes.",
                "type": "string"
            },
            "meeting": {
                "description":"Sitzung, der der Tagesordnungspunkt zugeordnet ist.",
                "type": "string",
                "format": "uri",
                "ref": "Meeting",
                "backref": "agendaItem",
                "cardinality": "n:1"
            },
    ...

Das Schema will ich in diesem Repo speichern, aber nochmal zusätzlich im Repo "schema" bereitstellen, das ausschließlich das Schema beinhalten soll und so besser in andere Projekte eingebunden werden kann. Mit Hilfe von git-subtree kann man das "schema" Repo komfortabel mit dem Schema in diesem Repo synchronisieren. Aktuell haben wir schon ein "schema" Repo, das aktuell JSON-LD-Kontexte enthält, daher will ich dieses Repo in "json-ld-context" umbenennen.

**Comment by akuckartz** [comment]
Zumindest zum Teil ist dies ein Duplicate von #27.

> Auch Clients und der Validator können das JSON Schema verwenden.

Ich begrüße es, wenn die Maschinenlesbarkeit von Spezifikationen gefördert wird !

> Allerdings kann man mit JSON Schema nicht die Beziehung zwischen zwei OParl Objekten abbilden. Wir können JSON Schema aber mit den folgenden drei Eigenschaften erweitern (eigene Erweiterungen sind in JSON Schema erlaubt):
    ref: Objekttyp der referenziert wird
    backref: Name der Eigenschaft die vom referenzierten Objekt auf dieses Objekt zurück referenziert (falls vorhanden)
    cardinality: die Kardinalität, habe ich im Beispiel gleich in der Form angegeben, wie ich sie in #282 vorgeschlagen habe.

Ich habe seit Juli 2014 schon drauf gewartet, dass OParl das Semantic Web für sich neu erfindet - bravo ;-)

Allerdings wäre #237 aus mehreren Gründen ein wesentlich nachhaltiger Weg dort hin, denn mit einer Speziallösung für OParl würde eine inkompatible Sackgasse ohne reale Zukunftsperspektive geschaffen.

**Comment by akuckartz** [comment]
Zwei Links für diejenigen, die sich für relevante Aktivitäten der Semantic Web Community im W3C interessieren:

RDF Data Shapes Working Group Charter
http://www.w3.org/2014/data-shapes/charter

SHACL (Shapes Constraint Language) Primer
W3C Editor's Draft
http://w3c.github.io/data-shapes/data-shapes-primer/

**Comment by akuckartz** [comment]
Konkreter: `backref` ähnelt etwas der bereits seit über zehn Jahren in OWL spezifizierten Eigenschaft `owl:inverseOf`.

OpenGovLD geht damit aber noch einfacher um: inverse Properties werden _nicht_ geschaffen, denn sie sind unerwünscht und unnötig, siehe https://github.com/OpenGovLD/specs/issues/127 Dabei wird die JSON-LD Property "@reverse" verwendet. Dies deckt sich auch mit der Position von TimBL, siehe https://github.com/mnot/I-D/issues/39#issuecomment-89789736

**Comment by lu-j** [comment]
Das Schema ist jetzt komplett in JSON-Schema gespeichert. Für die OParl eigenen Eigenschaften, habe ich Präfixe verwendet (Beispiel: "oparl:ref").

@akuckartz: wie ich bereits oben geschrieben habe, wollen wir das JSON-Schema nur intern verwenden um komfortabler an der Spezifikation arbeiten zu können. Mit JSON-LD kann man Linked Data Informationen zu den JSON-Eigenschaften speichern. Dabei ist es möglich, ein JSON-LD Objekt ohne Informationsverlust in verschiedene Formen umzuwandeln. Es ist also nicht dazu gedacht, die genaue Form und Struktur eines JSON-Objekts zu beschreiben und zu validieren. Daher war JSON-LD keine Alternative für uns. Mit den aktuell vorhandenen inversen Referenzen bin ich auch noch nicht zufrieden, dafür werde ich aber ein eigenes Issue öffnen.

**Comment by akuckartz** [comment]
@lu-j Nur als Ausblick: JSON-Schema können prinzipiell zur Festlegung von JSON-LD Serialisierungen (der Syntax) verwendet werden. Darauf kann z.B. in einem JSON-LD Profile (#222) verwiesen werden.

Es gibt aber derzeit auch wieder Diskussionen über "rdf crystalization". Auch dabei geht es um Festlegungen der Serialisierung für Nicht-RDF-Anwender.
