### ISSUE TITLE
Spezielle Datentypen (xsd:string, xsd:dateTime...) ersetzen

### ISSUE THREAD

**Issue by lu-j** [OParl/spec#285]
Auf dem Workshop wurde beschlossen:
Manche Eigenschaften haben spezielle Datentypen, die in anderen Spezifikationen definiert wurden. Zum Beispiel die Eigenschaft "email" eines Person-Objekts hat nicht den Datentyp "string" sondern den Datentyp "foaf:mbox". Das macht die Spezifikation schwerer verständlich. Daher sollen die speziellen Datentypen wieder durch die üblichen JSON-Datentypen ersetzt werden.

Für Zeitangaben soll der weit verbreitete ISO 8601 Standard verwendet werden, auf dem auch xsd:dateTime basiert. Falls bei einer Zeitangabe die Zeitzone nicht explizit angegeben wurde, soll die angegebene Zeit in der deutschen Zeitzone liegen.

Für eine zukünftigen OParl Version soll nochmal geprüft werden, welche bestehenden Standards in OParl integriert werden sollten.

Wir bitten um Feedback!

**Comment by akuckartz** [comment]
`foaf:mbox` etc. sind keine Datentypen, sondern Angaben zur Semantik (hier von `email`) - die jedoch aufgrund der von OParl Anfang Juli 2014 beschlossenen Nicht-Unterstützung von JSON-LD ohne Relevanz sind. Insofern befürworte ich, dass OParl möglichst keine falschen Eindrücke erweckt.

> Falls bei einer Zeitangabe die Zeitzone nicht explizit angegeben wurde, soll die angegebene Zeit in der deutschen Zeitzone liegen.

Wenn noch nicht einmal der Server sagen kann, welche Zeitzone massgeblich ist, weshalb soll das ein Client können? Jedenfalls ist in OpenGovLD als international ausgerichteter Spezifikation die Angabe der Zeitzone verpflichtend.

**Comment by the-infinity** [comment]
Umsetzung Schritt 1 (foaf in Definition entfernen) in https://github.com/OParl/specs/commit/b43ec09678e3e9077c344fefad4912320d5b26ab

**Comment by lu-j** [comment]
Ich habe jetzt alle speziellen Datentypen entfernt.
Ich habe auche das "tel:" Präfix für Telefonnummern entfernt, weil das den Eindruck vermittelt hatte, dass die Telefonnummern maschinenlesbar sind. Das ist aktuell aber nicht immer der Fall, zum Beispiel fehlt häufig die Vorwahl.
Für Emailadressen habe ich das "mailto:" Präfix entfernt, ich denke das ist in der Praxis eher nervig als hilfreich. Ob Emailadressen immer maschinenlesbar sein müssen, oder auch obfuskiert ausgegeben werden dürfen, müssen wir noch entscheiden. Das möchte ich aber im Issue zum Datenschutz-Kapitel (#289) behandeln.

Mit der aktuellen Lösung für Zeitangaben bin ich auch noch nicht zufrieden, daher habe ich den Text dazu noch nicht bearbeitet. Für dieses Thema möchte ich aber ein eigenes Issue öffnen.

**Comment by akuckartz** [comment]
> weil das den Eindruck vermittelt hatte, dass die Telefonnummern maschinenlesbar sind. Das ist aktuell aber nicht immer der Fall, zum Beispiel fehlt häufig die Vorwahl.

Bisher dachte ich, dass es bei OParl um maschinenlesbare Daten ginge ;-) Auch ohne Vorwahl sind Telefonnummern maschinenlesbar. Wenn keine Vorwahl angegeben ist, dann ist es Aufgabe der Betreiber die Daten zu korrigieren. Jedenfalls dürfte die korrekte Vervollständigung durch Betreiber regelmäßig einfacher durchzuführen sein, als für Clients.

**Comment by lu-j** [comment]
Das Ziel von OParl 1.0 ist es, die aktuell gespeicherten Daten eines RIS in Form von JSON herunterladen zu können. Dabei wollen wir noch keine Anforderungen an die Integrität oder Qualität der Daten stellen. Daher wollen wir auch keine Anforderungen an die Telefonnummern stellen.

Eine Telefonnummern mit "tel:" Präfix kann man verlinken. Tippt man dann mit einem Handy auf den Link, dann kann man die Nummer direkt anrufen. Dazu muss die Nummer aber alle Vorwahlen enthalten und sie sollte die Anforderungen von [RFC 3966](https://tools.ietf.org/html/rfc3966) erfüllen. Das habe ich mit maschinenlesbar gemeint. Da aktuelle die Telefonnummern in den RISen noch nicht maschinenlesbar sind, ist ein "tel:"-Präfix eher irreführend als hilfreich. Ich denke es ist nicht weiter schlimm, wenn auch Clients die Telefonnummern nicht vervollständigen und man das manuell vor dem Anrufen der Nummer machen muss.
