### ISSUE TITLE
Neue Ordnerstruktur, Makefile, Derivate nicht mehr im Repo speichern und Repo von "specs" in "spec" umbenennen

### ISSUE THREAD

**Issue by lu-j** [OParl/spec#286]
Ich will ein paar Änderungen vornehmen, die die Arbeit an der Spezifikation erleichtern. Inhaltlich wird sich dadurch nichts an der Spezifikation ändern.

Ich will die Ordnerstruktur wie folgt ändern:
- **examples:** Für die JSON Beispiele. Die sollen nicht mehr direkt in den Markdown-Dateien gespeichert werden, da auch das Schema mit der Umstellung auf JSON-Schema (siehe #283) nicht mehr in Markdown geschrieben ist. Die Dateinamen werden nummeriert. Beispiel: AgendaItem-01.json 
- **ressources:** Für zusätzliche Dateien, die für die Spezifikation gebraucht werden. Zum Beispiel das Latex-Template für die Pandoc PDF-Ausgabe.
- **schema:** Für die JSON Schema-Dateien.
- **scripts:** Der Ordner bleibt wie er ist. Hier kommt zum Beispiel das Skript rein, das aus den JSON Beispielen und dem JSON Schema eine temporäre Markdown Datei generiert, damit die Spezifikation gebaut werden kann.
- **src:** Für die Markdown-Dateien. Die Dateien sollen in den Kapitelnamen umbenannt werden. Damit die Dateinamen mit allen Systemen kompatibel bleiben, sollen slugs aus den Kapitelnamen erstellt werden. Beispiel: "1.1 Was ist OParl in Kürze?" -> "1-1-was-ist-oparl-in-kuerze.md"

Die Dateien "create_documents.sh", "create_temp_pdf.sh" und "create_images.sh" sollen durch ein Makefile ersetzt werden. Damit ist es Möglich, nur bestimmte Formate erstellen zu lassen. Ein Aufruf von beispielsweise "make pdf" erzeugt nur die PDF-Version. Das Makefile kann auch erkennen, ob die Bilder unverändert sind und bereits gerendert wurden und überspringt gegebenenfalls diesen Schritt.

Da die Derivate bisher direkt im Repo gespeichert wurden, ist das Repo mittlerweile 84MB groß geworden. In Zukunft sollen die Derivate bei jeder Änderung automatisch gebaut werden, aber nicht mehr im Repo gespeichert werden, sondern auf oparl.org zum Download bereit stehen. Die HTML Version soll man auch direkt online im Browser lesen können. Auch ältere Versionen der Spezifikation sollen heruntergeladen werden können.

Außerdem soll das Repo von "specs" in "spec" umbenannt werden, da bisher immer die Rede von *der* Spezifikation war und unklar ist, warum für den Repo-Namen die Mehrzahl benutzt wurde. Beim Umbenennen ändert sich auch die URL des Repos, Github richtet aber automatisch eine Weiterleitung auf die neue URL ein, von daher sollte es keine üblen Nebenwirkungen geben.

**Comment by eFrane** [comment]
Das Repository für die Weboberfläche findet sich unter OParl/spec-website, die Webseite wird bis auf weiteres http://spec.oparl.org sein. Die Funktionalität dieser Webseite bezüglich Downloads und sich aktualisierender Onlineversion wird im Laufe der kommenden Woche fertiggestellt.

**Comment by akuckartz** [comment]
> Außerdem soll das Repo von "specs" in "spec" umbenannt werden, da bisher immer die Rede von der Spezifikation war und unklar ist, warum für den Repo-Namen die Mehrzahl benutzt wurde.

Für sich genommen ist das meiner Meinung [bikeshedding](https://en.wikipedia.org/wiki/Parkinson%27s_law_of_triviality). Es sind aber generelle Fragen damit verbunden. Deshalb Feedback dazu:

1. Es hilft nicht, wenn die Benennung eines Ordners (oder Containers) damit zusammenhängt oder damit zusammenhängen soll, wie viele Dateien (oder Objekte) sich darin befinden. Ähnliche Fragen stellen sich auch an anderen Stellen, siehe z.B. https://github.com/OParl/specs/issues/129 aber auch https://github.com/OParl/specs/issues/282#ref-issue-89763892

2. Soll "spec" dann wieder nach "specs" umbenannt werden, wenn eine weitere Spezifikation hinzu kommt?

3. Wieviele Spezifikationen sind OParl 1.0, OParl 1.0.1, OParl 1.1, Oparl 2.0 und OParl-LD 2015 ? Nur eine ?

4. Warum "spec" und nicht "specification"? (Nein, die Diskussion will ich mit der Frage nicht anregen.)

5. Wenn man ein einheitliches Benennungsschema haben möchte, dann empfiehlt sich eventuell die normalerweise kürzere Form, also Singular statt Plural.

**Comment by noxer** [comment]
1. "ressources" bitte zu "resources" machen, es sind nur im Deutschen "Ressourcen".
2. Sieht gut aus, damit kann ich arbeiten.
3. @akuckartz: Kannst du mir bitte den Zweck deines Beitrags erklären? Bist du für die Umbenennung? Dagegen?

**Comment by akuckartz** [comment]
@noxer Nein, mehr Zeit stecke ich in dieses Issue nicht. Die genannte einzelne Benennung ist mir egal. Sie betrifft die Spezifikation zudem nicht.

**Comment by lu-j** [comment]
@noxer: Danke für den Hinweis, habe ich behoben.
@akuckartz: Ich fand "spec**s**.oparl.org" unpassend, daher habe ich mich für "spec.oparl.org" entschieden und dadurch kam mir die Idee das Repo umzubenennen. Auch wenn die Nachfolgerversion von OParl 1.0 herausgekommen ist, bleibt es für mich weiterhin *eine* Spezifikation, von der es dann eine aktuelle und in eine alte Version gibt. Sollten wir eine neue Spezifikation entwickeln, die sich wesentlich von OParl unterscheidet, sollte sie einen eigenen Namen und ein eigenes Repo bekommen.

Ich bin mit allen Änderungen fertig, in den Dateinamen der Markdowndateien musste ich für die Unterkapitelnummer immer explizit zwei Stellen angeben, da im zweistelligen Bereich die Dateien sonst nicht von allen Systemen richtig sortiert wurden. Beispiel für die neue Benennung: "1.1 Was ist OParl in Kürze?" -> "1-**0**1-was-ist-oparl-in-kuerze.md".

Wegen der Umbennenung des Repos ist es Empfohlen die Remote URL im lokalen Repo zu aktualisieren: `git remote set-url origin https://github.com/OParl/spec.git` (siehe https://help.github.com/articles/renaming-a-repository/).
