### ISSUE TITLE
In eigener Sache

### ISSUE THREAD

**Issue by sterni24** [OParl/spec#287]
Seit April 2013 bin ich daran interessiert, eine praxisnahe und letztendlich auch finanzierbare Schnittstelle mit auf die Beine zu stellen. Im Laufe der Zeit, warum auch immer, haben sich die Reihen der aktiven Teilnehmer gelichtet.

Ich betrachte dieses Forum nicht mehr als adäquates Medium, um OParl 1.0 fertigzustellen. Aus diesem Grund nehme ich meinen Vorschlag vom April 2013 wieder auf und bitte darum, die sich aus dem Workshop vom 01.04.2015 beschlossenen Änderungen in die Spezifikation einzuarbeiten und den RIS-Herstellern zur Stellungnahme per E-Mail vorzulegen.

Ich bedanke mich bei allen Beteiligten, die das Ziel von OParl 1.0 konsequent verfolgen, insbesondere @marians, und verabschiede mich von GitHub.

**Comment by akuckartz** [comment]
@sterni24 Ich habe mich Anfang Juli 2014 aus dem OParl-Projekt zurückgezogen und kann und will deshalb nicht für dieses Projekt sprechen.

> Im Laufe der Zeit, warum auch immer, haben sich die Reihen der aktiven Teilnehmer gelichtet.

In meinem Fall gab es mehrere Gründe:
- die Entscheidung zum "Rückbau von JSON-LD", also die _Abwendung von Linked Data_
- die dabei insbesondere durch den damaligen Hauptinitiator angewendete _intransparente Vorgehensweise_
- hinzu kam als weiterer Grund das _Ignorieren relevanter internationaler Spezifikationsprojekte_ wie Popolo 

> Ich betrachte dieses Forum nicht mehr als adäquates Medium, um OParl 1.0 fertigzustellen.

Eine _Begründung_ dieser Einschätzung habe ich bisher nicht gesehen.

> Aus diesem Grund nehme ich meinen Vorschlag vom April 2013 wieder auf und bitte darum, die sich aus dem Workshop vom 01.04.2015 beschlossenen Änderungen in die Spezifikation einzuarbeiten und den RIS-Herstellern zur Stellungnahme per E-Mail vorzulegen.

Dazu verweise ich auf #272 und #273 Mich würde interessieren, was dagegen spricht, dass RIS-Hersteller sich hier auf Github äußern.

Es gibt aber auch die [oparl-tech mailing list](https://lists.okfn.org/mailman/listinfo/oparl-tech). Die ist allerdings fast tot. Der letzte Beitrag kam im Januar 2015 und mit Ausnahme der allerersten mail vom 30.5.2014 stammen alle mails von mir. Ein _klein_ wenig lebendiger ist die [ris mailing list](https://lists.okfn.org/pipermail/ris/).

**Comment by lu-j** [comment]
@sterni24 Schade, dass Sie nicht mehr auf Github aktiv sind...

Vielen Dank für Ihr bisheriges Engagement. Ihre zahlreichen Beiträge und Vorschläge waren eine große Hilfe für OParl!

Ich kann Ihre Entscheidung nachvollziehen. Während es in der Anfangszeit, vor allem im Jahr 2013, noch viele Beteiligte gab, wurden es in letzter Zeit immer weniger. Ich denke es hat mehrere Gründe. Am Anfang gab es einige Workshops und insgesamt mehr Aufmerksamkeit für OParl. Es wurden eher grundlegende Fragen diskutiert, während es heute meist um komplizierte Detailfragen geht, die eine Kenntnis des aktuellen Stands der Spezifikation voraussetzen. Ein weiterer Grund sind sicherlich die anstrengenden Diskussionen um Kleinigkeiten oder zur allgemeinen Ausrichtung des Projekts.

Auch wenn es keine große Beteilung mehr in den Issues gibt, wollen wir weiterhin Github verwenden um unsere Arbeit zu dokumentieren, damit man die Änderungen an der Spezifikation besser nachvollziehen kann.

Wir werden alle Beteiligten per Email auf dem Laufenden halten. Wer ebenfalls Emails von uns bekommen will, kann sich in den Newsletter eintragen: http://oparl.org/newsletter/

Ich denke mit den Ergebnissen vom Workshop ist inhaltlich mittlerweile fast alles geklärt und wird sind auf einem gutem Weg OParl 1.0 bald verabschieden zu können.
