### ISSUE TITLE
SKOS-Objekte entfernen

### ISSUE THREAD

**Issue by lu-j** [OParl/spec#288]
Auf dem Workshop wurde beschlossen:
Aktuell scheint es in den RIS-Systemen noch keine ratsübergreifende Klassifizierungen für Drucksachen, Ämter und Gremien zu geben. Daher können aktuell noch keine SKOS-Objekte genutzt werden, sie sollen aus OParl 1.0 entfernt werden. Wir wollen mit OParl 1.0 erst mal Erfahrungen sammeln und dann überlegen wie sich die Daten am Besten ratsübergreifend klassifizieren lassen.

Wir bitten um Feedback!

**Comment by lu-j** [comment]
Sobald die ersten RISe eine OParl Schnittstelle haben und wir Daten von verschiedenen Kommunen gesammelt haben, werden wir Anfangen die Begriffe zu klassifizieren und Synonyme zu sammeln. Das Ergebnis können wir zum Beispiel als JSON Datei veröffentlichen, die dann von OParl Anwendungen verwendet werden kann. 
Hier ein Beispiel wie so etwas aussehen könnte, die Ergebnisse einer Beratung einer Drucksache werden klassifiziert:

~~~
{
    "beschlossen": ["beschlossen", "mit Mehrheit beschlossen", "ungeändert beschlossen", "ohne Änderungen im Rat beschlossen"...
    "geändert beschlossen": ["geändert beschlossen", "beschlossen in geänderter Fassung", "mit Änderungen beschlossen"...
    "zur Kenntnis genommen": ["zur Kenntnis genommen", "Kenntnis genommen"... 
    "abgelehnt": ["abgelehnt", "mehrheitlich abgelehnt", "im Rat abgelehnt"...
    ...
~~~

Sobald wir eine Klassifizierung erstellt haben, wollen wir überlegen, in wie weit es Möglich ist, dass die Begriffe in einer zukünftigen Version von OParl direkt vom RIS klassifiziert werden.

**Comment by akuckartz** [comment]
> Aktuell scheint es in den RIS-Systemen noch keine ratsübergreifende Klassifizierungen für Drucksachen, Ämter und Gremien zu geben. Daher können aktuell noch keine SKOS-Objekte genutzt werden, sie sollen aus OParl 1.0 entfernt werden. 

Die Verwendung von SKOS-Objekten war *nicht* unter der Voraussetzung eingeführt worden, dass es Gebietskörperschaften übergreifende Klassifizierungen gibt. Sie basierte auf der Feststellung, dass es auch *innerhalb* eines RIS einer Gebietskörperschaft de fakto bereits Klassifizierungen gibt. Diese Klassifizierungen sollten die RIS deshalb entsprechend als SKOS-Objekte ausgeben. Eine gebietskörperschaftenübergreifende Klassifizierung konnte damit *ohne jede Änderung der Spezifikation* erfolgen.

Allerdings setzt SKOS die Verwendung von RDF voraus. Mit dem "Rückbau von JSON-LD" wurde auch SKOS die Grundlage entzogen.

> ...  werden wir Anfangen die Begriffe zu klassifizieren und Synonyme zu sammeln. Das Ergebnis können wir zum Beispiel als JSON Datei veröffentlichen, die dann von OParl Anwendungen verwendet werden kann. ...

Das sieht wie ein weiteres Rad aus, dessen Neuerfindung ansteht. Denn insbesondere für solche Zwecke wurde SKOS geschaffen.

> Sobald wir eine Klassifizierung erstellt haben, wollen wir überlegen, in wie weit es Möglich ist, dass die Begriffe in einer zukünftigen Version von OParl direkt vom RIS klassifiziert werden.

Bei Verwendung von SKOS geht das bereits jetzt.

**Comment by eFrane** [comment]
Das Problem mit der Verwendung von SKOS jetzt ist aber, dass wir nicht wissen, was für Daten in den Feldern überhaupt stehen werden.

**Comment by akuckartz** [comment]
@eFrane Solches Wissen ist auch nicht nötig!

Beispiel: Ein RIS liefert nicht die Werte "beschlossen", "mit Mehrheit beschlossen" und "ungeändert beschlossen" sondern entsprechende URLs zu SKOS-Objekten und - wenn es kann - zusätzlich SKOS-Angaben zu Beziehungen dazwischen, z.B. dass "ungeändert beschlossen" und "mit Mehrheit beschlossen" spezieller (`skos:narrower`) sind als "beschlossen". Die Zeichenketten  "beschlossen", "mit Mehrheit beschlossen" und "ungeändert beschlossen" sind dann in den SKOS-Objekten enthalten.

Ein einzelnes RIS kann eine eigene Menge an SKOS-Objekten auf dem eigenen Server unterhalten - was am nächsten zur bisherigen Praxis wäre. Oder die SKOS-Objekte können sich auf einem Server des RIS-Herstellers, oder eines Bundeslands oder auf oparl.org oder sonstwo befinden und von mehreren RIS verwendet werden. Auch beliebige Mischformen sind technisch kein Problem.

Wesentlich ist, dass es einem Client egal sein kann, woher er die SKOS-Objekte erhält. Damit ist für zukünftige Angleichungen der Klassifizierungen *keine Änderung der Schnittstelle* erforderlich. Und ein Server *kann* Klassifizierungen vornehmen.

Dezentrale Klassifizierungen sind also möglich, sie schliessen aber das Entstehen und die Verwendung zentraler Klassifizierungen nicht aus.

**Comment by lu-j** [comment]
Es stimmt, es ist möglich die SKOS-Objekte auch nach der Verabschiedung von Version 1.0 "nachzuliefern". Trotzdem möchten wir eine Klassifizierung noch nicht mit OParl 1.0 einführen.

Um die Daten in den RISen klassifizieren zu können muss sehr wahrscheinlich die Verwaltungsoberfläche der RISe angepasst werden damit die Kommunen ihre verwendeten Begriffe klassifizieren können. Das ist keine triviale Anforderung, daher wollen wir die Klassifizierung gut planen und erst einführen, wenn wir genau wissen wie wir vorgehen wollen.
Weiterhin denken wir, dass die Information, welche Begriffe wie klassifiziert werden sollen, in einer zukünftigen Version der Spezifikation stehen sollte und nicht außerhalb der Spezifikation auf unserer Website liegen.

**Comment by lu-j** [comment]
Ich habe mittlerweile alle SKOS-Verweise aus der Spec entfernt.

@akuckartz: Mein JSON-Beispiel sollte nur veranschaulichen um was es geht. Wenn es soweit ist, machen wir uns Gedanken in welchem Format wir die Klassifizierungen speichern wollen und dann werden wir uns auch SKOS näher anschauen.
