### ISSUE TITLE
Nur ein Datentyp pro Eigenschaft

### ISSUE THREAD

**Issue by lu-j** [OParl/spec#290]
Auf dem Workshop haben wir beschlossen:
Manche Eigenschaften haben mehr als einen Datentyp. Zum Beispiel resolution von AgendaItem kann einen Text aber auch eine URL zu einem File-Objekt enthalten. Solche Eigenschaften sollten in mehrere Eigenschaften unterteilt werden, damit es nur noch einen Datentyp pro Eigenschaft gibt. In diesem Fall sollte also resolution durch die Eigenschaften resolutionText und resolutionFile ersetzt werden.
Wir immer bitten wir um Feedback!

**Comment by akuckartz** [comment]
Das hatte ich in https://github.com/OParl/specs/issues/212#issue-36054093 bereits vor einem Jahr vorgeschlagen und laut https://github.com/OParl/specs/issues/212#issuecomment-48096344 wurde das kurz danach umgesetzt.

**Comment by the-infinity** [comment]
Fixed in https://github.com/OParl/spec/commit/3ec7ede949fe573d08ab157a1257e4b805e406a5 .
