### ISSUE TITLE
OParl besser crawlbar machen: vollständige Listenausgabe mit interner Listenausgabe für alle Objekttypen und Feeds durch Filter ersetzen

### ISSUE THREAD

**Issue by lu-j** [OParl/spec#291]
Auf dem Workshop haben wir beschlossen:
Es gibt aktuell noch keine komfortable Möglichkeit alle Objekte aus einem OParl-System zu laden (crawlen), daher sollen folgende drei Änderungen vorgenommen werden:

1. Vollständige Listenausgabe für alle Objekttypen
--------------------------------------------------

Vom Body Objekt aus soll es Links zu externen Listen für jeden Objekttyp geben:

```
{
    "id": "http://oparl.example.org/bodies/0",
    "type": "http://oparl.org/schema/1.0/Body",
    "organization": "http://oparl.example.org/bodies/0/organizations/",
    "person": "http://oparl.example.org/bodies/0/persons/",
    "meeting": "http://oparl.example.org/bodies/0/meetings/",
    "agendaItem": "http://oparl.example.org/bodies/0/papers/",
    "paper": "http://oparl.example.org/bodies/0/papers/",
    "file": "http://oparl.example.org/bodies/0/files/",
    "consultation":  "http://oparl.example.org/bodies/0/consultation/",
    "location":  "http://oparl.example.org/bodies/0/location/",
    "membership":  "http://oparl.example.org/bodies/0/membership/",
    "legislativeTerm":  "http://oparl.example.org/bodies/0/legislativeTerm/",
    ...
```

In den Listen sollen die Objekte immer in vollständiger Form ausgegeben werden (also nicht nur die IDs), der Parameter listformat=complete entfällt somit. Es ist empfohlen Paginierung zu verwenden. Beispiel für die vollständige Paper-Liste:

```
    {
        "items": [
            {
                "id": "http://oparl.example.org/bodies/0/papers/1",
                "type": "http://oparl.org/schema/1.0/Paper",
                "name": "Antwort auf Anfrage 1/2014",
                "mainFile": "http://oparl.example.org/files/7",
                "publishedDate": "2014-01-04T16:42:02+02:00",
                ...
            },
            {
                "id": "http://oparl.example.org/bodies/0/papers/2",
                "type": "http://oparl.org/schema/1.0/Paper",
                "name": "Radwege ausbauen",
                "mainFile": "http://oparl.example.org/files/12",
                "publishedDate": "2014-01-05T13:05:00+02:00",
                ...
            },
            {
                "id": "http://oparl.example.org/bodies/0/papers/3",
                "type": "http://oparl.org/schema/1.0/Paper",
                "name": "Neue Parkbänke für den Stadtpark",
                "mainFile": "http://oparl.example.org/files/14",
                "publishedDate": "2014-01-05T14:31:12+02:00",
                ...
            },
            ...
        ],
        "nextPage": "http://oparl.example.org/bodies/0/papers/?skip_id=99"
    }
```

2. Standardgemäß interne Listenausgabe verwenden
---------------------------------------------

Aktuell darf der Server jede Liste in eine externe Liste auslagern.

Beispiel: die participants aus einem Meeting-Objekt als externe Liste:

```
{
    "items": [
        {
            "id": "http://oparl.example.org/meetings/281",
            "type": "http://oparl.org/schema/1.0/Meeting",
            "name": "1. Sitzung des Finanzausschusses",
            "participant": "http://oparl.example.org/meetings/281/participants/",
            ...
        },
    ...
```

Falls externe Listen verwendet werden, muss ein Client pro Objekt zusätzliche HTTP-Anfragen machen um die externen Listen abzufragen, was bei vielen Objekten im System zu sehr vielen HTTP-Anfragen führen würden.

Stattdessen soll immer die interne Listenausgabe verwendet werden:

```
{
    "items": [
        {
            "id": "http://oparl.example.org/meetings/281",
            "type": "http://oparl.org/schema/1.0/Meeting",
            "name": "1. Sitzung des Finanzausschusses",
            "participant": [
                "http://oparl.example.org/person/10",
                "http://oparl.example.org/person/22",
                "http://oparl.example.org/person/12",
                "http://oparl.example.org/person/99",
                "http://oparl.example.org/person/73",
                "http://oparl.example.org/person/83",
                "http://oparl.example.org/person/78",
                "http://oparl.example.org/person/94",
                "http://oparl.example.org/person/98",
                "http://oparl.example.org/person/34",
                "http://oparl.example.org/person/52",
                "http://oparl.example.org/person/57"
            ],
            ...
        },
        ...
```

Ein Client kann jetzt die Liste der Meetings crawlen ohne zusätzliche HTTP-Anfragen pro Objekt machen zu müssen. Durch URLs in der participant-Liste kann gespeichert werden, welche Personen-IDs mit dieser Sitzung verknüpft sind (Fremdschlüssel). Ein Client sollte aus Performancegründen diese URLs nicht einzeln abfragen. Stattdessen sollte der Client gleich die vollständige Liste mit allen Personen-Objekten abfragen, um viele Objekte mit einem Request zu erhalten.

Für manche Clients, zum Beispiel Tablet-Apps, könnte es jedoch ungünstig sein, zuerst die vollständige Liste mit allen Personen-Objekten laden zu müssen, bevor sie die Teilnehmer für eine Sitzung anzeigen können. Hier eignen sich externe Listen besser. Eine Lösungsmöglichkeit wäre, wenn sich die externe Listenausgabe mit einem Parameter, zum Beispiel "`?listformat=external`", aktivieren ließe.

Anmerkung: Nach dem Workshop ist dabei allerdings noch ein Problem aufgefallen. Möchte ein Client die Mitglieder eines Organization-Objekts abfragen, ebenfalls ohne vorher die vollständige Liste mit allen Personen-Objekten laden zu müssen, helfen externe Listen allein noch nicht. Das Problem ist, dass die Organization-Objekte nicht direkt, sondern über Membership-Objekte mit den Personen-Objekten verknüpft sind. Man könnte dann zwar eine externe Liste mit Membership-Objekten abfragen, müsste von dort aber die Personen-Objekte einzeln abfragen. Über dieses Problem soll weiter nachgedacht werden.

3. Feeds durch Filter ersetzen
---------------------------

Feeds sind schwer zu implementieren, vor allem mit stabiler Paginierung. Feeds sollen wie folgt ersetzt werden:

Jedes Objekt soll die Eigenschaften created und modifed haben. Es soll möglich sein, mit einem Filter in den Listen nur Objekte anzeigen zu lassen, die nach einem wählbaren Zeitpunkt erstellt oder geändert wurden. Die Abfrage dazu könnte so aussehen:

    http://oparl.example.org/bodies/0/papers/?modified_after=2015-04-20:15:27+02:00

Das ermöglicht es den Datenbestand zu updaten. Außerdem wird es dadurch ermöglicht, Objekte aus einem bestimmten Zeitraum abzufragen, falls man ältere Objekte nicht benötigt.

Wir immer bitten wir um Feedback!

**Comment by akuckartz** [comment]
Entsprechende Lösungen die auf aktuellen Linked Data-Techniken basieren werde ich demnächst hier darstellen.

(Nebenbei: dies sind eigentlich mehrere Issues und nicht nur eines.)

**Comment by lu-j** [comment]
@akuckartz: Ich wollte für dieses Thema lieber nur ein Issue haben, da für mich alle drei Punkte zusammengehören, weil sie festelegen, wie die OParl-Daten abgefragt werden sollen.

Es ist noch nicht geklärt, was mit den gelöschten Objekten passieren soll. Ein Feed mit gelöschten Objekten für alle Objekttypen ist sowohl für Server als auch für Clients umständlich zu implementieren. Ich denke, falls ein RIS speichert welche Objekte gelöscht wurden, dann wird das vermutlich so realisiert, dass das Objekt in der Datenbank bleibt, aber alle gespeicherten Werte gelöscht werden. So sollten wir es auch in OParl lösen. Wenn ein Objekt gelöscht wird, sollte der "modified"-Timestamp aktualisiert werden (damit bei der nächsten Synchronisation mit einem Client dieses Objekt berücksichtigt wird) und alle Eigenschaften bis auf "id" und "type" entfernt werden. Ich denke es ist sinnvoll, wenn zusätzlich das Objekt explizit als gelöscht markiert wird. Beispiel:

~~~
{
    "id": "https://oparl.example.org/agendaitem/3271",
    "type": "http://oparl.org/schema/1.0/AgendaItem",
    "modified": "2015-07-23T12:05:27+02:00",
    "deleted": true
}
~~~

Wir sollten auch zur Sicherheit die RIS-Hersteller fragen, ob sie diese Lösung leicht implementieren können.

Außerdem fände ich sinnvoll, wenn die Body-Objekte auch in einer Liste ausgegeben werden. Das ist konsistenter und sinnvoll für Spiegel-Server die Daten von mehreren RISen gesammelt bereitstellen und somit viele Body-Objekte gespeichert haben. Das System Objekt soll also die Liste der Body-Objekte verlinken und nicht mehr jedes Body-Objekt einzeln verlinken.

**Comment by akuckartz** [comment]
> Außerdem fände ich sinnvoll, wenn die Body-Objekte auch in einer Liste ausgegeben werden. Das ist konsistenter und sinnvoll für Spiegel-Server die Daten von mehreren RISen gesammelt bereitstellen und somit viele Body-Objekte gespeichert haben. Das System Objekt soll also die Liste der Body-Objekte verlinken und nicht mehr jedes Body-Objekt einzeln verlinken.

Die Beschränkung auf einen einzigen `Body` gehörte zu dem, was ich an anderer Stelle als "unnötige Einschränkung" bezeichnet hatte. Ich bin also *für* die Aufhebung dieser Beschränkung.

Der Umgang mit gelöschten Objekten ist u.a. aus rechtlichen Gründen ein wichtiger Aspekt aber eben nicht trivial. Ich melde mich dazu voraussichtlich demnächst.

**Comment by akuckartz** [comment]
Siehe auch #233

**Comment by the-infinity** [comment]
Vorschlag mit https://github.com/OParl/spec/commit/2ce08aacf5cc453b1bf7c7f9069f38a4e71d12ee (gelöschte Objekte) und https://github.com/OParl/spec/commit/c7943399d6697ff978033360d3aafc4f6717e291 (list styles). Gerne Korrekturen einpflegen. :)

**Comment by konstin** [comment]
2ce08aa finde ich technisch gesehen gut, in der Praxis gibt es aber oft das Problem, dass einige Daten für ältere Dokumente nicht mehr bestimmt werden können. Darunter fallen z.B. das Datum der Löschung eines Dokuments oder der letzten Änderung eines Antrags.

Das Problem wirkt sich auch auf c794339 aus, der eine Suche nach Datum damit nicht mehr verlässlich durchgeführt werden kann.

Eine mögliche Lösung wäre die Angabe eines Datums durch den server, vor dem die Informationen z.B. zu `modified` nicht präzise sind.

**Comment by the-infinity** [comment]
Yep, es wird irgendwie eine Reihe sinnloser Angaben in den Altbeständen geben. Von den RIS-Herstellern weiss ich, dass die das so lösen, dass sie einfach modified und created auf den Import- / Migrationszeitpunkt setzen. Das würde dann am Ende nur eine eher sinnlose Liste in den Altbeständen machen, ein Update eines bestehenden Datenbestandes funktioniert aber, weil ab Zeitpunkt X modified ja korrekt ausgegeben wird. Und die Altbestände scraped man ja eh komplett.

Der Vorschlag, dass modified nicht präzise ist, wird leider wenig bringen, da die RIS das selbst nicht wissen. Die Daten werden beim Import halt alle auf modified now gesetzt. Die speichern also nicht, dass das ungenau ist.

**Comment by konstin** [comment]
Diese Vorgehensweise wird aber z.B. in dem Fall problematisch, in dem ein Nutzer weiß, das ein bestimmtes Dokument in einem bestimmten Zeitraum erstellt wurde, und deshalb nach diesem Zeitraum sucht. Der client bekommt aber vom server die falschen Daten, weshalb der Nutzer das Dokument nicht finden kann. Genauso wird das Erstellen von Statistiken und (automatischen) Analysen wird damit unmöglich. Es sollte schließlich ganz allgemein aus einer vielzahl aus einer Vielzahl an Gründen vermieden werden, dem client bewusst falsche Daten zu liefern.

**Comment by the-infinity** [comment]
Das Problem ist: wie willst du das sonst lösen? Der Altdatenbestand ist nun mal schlicht fehlerhaft, die Infos fehlen schlichtweg. Lösung: gar nicht ausgeben? Oder ... ?

**Comment by konstin** [comment]
Im zweifelsfall einfach nichts ausgebenscheint doch noch die beste Möglichkeit zu sein. Alternativ könnte ein server Grenzen angegeben, nach denen eine korrekte angegabe nicht möglich ist, sodass die clients darauf entsprechend reagieren können.

**Comment by the-infinity** [comment]
Das Problem ist nur, dass da ja Werte in den Datenbanken der RIS drin stehen. Die sind falsch. Aber es würde extrem viel Arbeit machen, die falschen Werte zu identifizieren.
Was aber tatsächlich Sinn machen würde, wäre den Start der API pro Body. Denn es wird bei den Altdatenbeständen bis zum API-Start immer im Detail Fehler geben, z.B. weil einige Objekte in den bestehenden RIS nicht existieren und so auch keine validen Werte da sein können.
Kurzum: Im Body könnte man also zusätzlich angeben "oparl_since", und ab diesem Zeitpunkt kann man dann sicher davon ausgehen, dass die Daten valide sind. Wäre das eine Lösung?

**Comment by akuckartz** [comment]
Der Umgang mit Zeitstempeln von/für Altdaten könnte ein separates Issue wert sein. Für mich stellen sich dazu insbesondere zwei Fragen:
- Wie ist die Semantik der Properties _genau_ definiert ?
- Können aus vorhandenen Zeitstempeln zu dieser Semantik passende Werte berechnet werden?

**Comment by the-infinity** [comment]
1) Welcher Properties?
2) meistens sehr ungefähre Werte bis gar keine Werte. Man kann ab und an vom Termin ausgehend eine ungefähre Modified-Zeit erreichen. Wann Created war, ob es nach der Sitzung noch eine Änderung gab etc ist alles nicht nachvollziehbar. Außerdem gibt es da keine einheitliche Regel, wie man mit Altdaten umgehen soll, so dass es da je nach Instanz unterschiedliche Behandlungen gibt. Es wird somit zwangsweise an der einen oder anderen Stelle blödsinnige Altdaten geben, das ist unvermeidbar.

**Comment by konstin** [comment]
zu 2) Es gibt auch z.T. "stille Löschungen", bei denen Dokumente einfach ohne einen Hinweis gelöscht werden, was ein nachträgliches setzten des richtigen `modified` unmöglich macht .

**Comment by the-infinity** [comment]
Der von @konstin angesprochene Punkt kann erst ab der Einführung von OParl beachtet werden, ja (und dürfte dem einen oder anderen RIS-Hersteller eh "Spaß" machen). Vor oparl_since dürften vielfach schlicht die Daten fehlen in der Original-Datenbank.

**Comment by the-infinity** [comment]
... habe oparlSince nun hinzugefügt: https://github.com/OParl/spec/commit/0f9909d48815679c7a316cef0b0eb946b79928be

**Comment by lu-j** [comment]
Mit dem aktuellen Entwurf gibt es noch ein Problem. Es kommt durchaus vor, dass vor einer Sitzung Tagesordnungspunkte gelöscht werden, zum Beispiel, wenn an dem Tagesordnungspunkt eine Drucksache beraten werden sollte, die Drucksache aber zurückgezogen wurde. Ich denke dann wird oft auch das zugehörige Consultation-Objekt gelöscht, da die Drucksache ja nicht mehr beraten wird. Ein RIS muss also in der Lage sein, die gelöschten Objekte auszugeben, damit der Datenbestand richtig synchronisiert werden kann. Dazu sind aber nicht alle RISe in der Lage, da sie zum Teil Objekte vollständig aus der Datenbank löschen und somit auch die Information, welche Objekte gelöscht wurden, verloren geht.
Für dieses Problem gibt es eine einfache Lösung. Die Tagesordnungspunkte können zusammen mit der Sitzung ausgegeben werden, als eingebettete Objekte. Wenn ein Tagesordnungspunkt gelöscht wird, muss der modified Zeitstempel der Sitzung aktualisiert werden. Ein Client speichert dann einfach das aktualisierte Sitzungs-Objekt inklusive der Tagesordnungspunkte erneut ab, nicht mehr vorhandene Tagesordnungspunkte werden somit gelöscht. Hier ein Beispiel, wie dann ein Sitzungs-Objekt aussieht:

```json
{
    "id": "https://oparl.example.org/meeting/281",
    "type": "http://oparl.org/schema/1.0/Meeting",
    "name": "4. Sitzung des Ausschusses für Stadtentwicklung",
    "start": "2012-10-14T16:00:00+01:00",
    "end": "2012-10-14T20:00:00+01:00",
    "agendaItem": [
        {
            "number": "1",
            "name": "Eröffnung der Sitzung",
            "public": true
        },
        {
            "number": "2",
            "name": "Feststellung der Tagesordnung",
            "public": true
        },
        ...
    ],
    "modified": "2014-08-08T14:05:27+01:00",
    ...
}
```

Mit den anderen Objekten kann man genauso vorgehen: die Beratungen (Consultations) können zusammen mit der Drucksache (Paper), die Mitgliedschaften (Memberships) zusammen mit dem Ratsmitglied (Person) und die Legislaturperioden (LegislativeTerms) zusammen mit der Körperschaft (Body) ausgegeben werden. Auch die File- und Location-Objekte können eingebettet ausgeben werden. Hier für jeden Objekttyp ein Beispiel:


```json
System:
bleibt wie es ist


Body:
{
    "id": "https://oparl.example.org/bodies/1",
    "type": "http://oparl.org/schema/1.0/Body",
    "system": "https://oparl.example.org/",
    "contactEmail": "ris@beispielstadt.de",
    "name": "Beispielstadt",
    "organization": "https://oparl.example.org/bodies/1/organizations/",
    "person": "https://oparl.example.org/bodies/1/people/",
    "meeting": "https://oparl.example.org/bodies/1/meetings/",
    "paper": "https://oparl.example.org/bodies/1/papers/",
    "legislativeTerm": [
        {
            "name": "15. Wahlperiode",
            "startDate": "2012-07-14",
            "endDate": "2017-07-13"
        },
        {
            "name": "14. Wahlperiode",
            "startDate": "2007-07-14",
            "endDate": "2012-07-13"
        }
    ],
    "modified": "2012-07-18T14:28:31.568+0100"
}


Person:
{
    "id": "https://oparl.example.org/person/29",
    "type": "http://oparl.org/schema/1.0/Person",
    "body": "https://oparl.example.org/bodies/1",
    "name": "Max Mustermann",
    "formOfAddress": "Ratsherr | Ratsfrau",
    "gender": "male",
    "membership": [
        {
            "organization": "https://oparl.example.org/organizations/34",
            "role": "Ausschussmitglied",
            "votingRight": true,
            "startDate": "2012-07-14T00:00:00+02:00"
        },
        {
            "organization": "https://oparl.example.org/organizations/12",
            "role": "Ausschussmitglied",
            "votingRight": true,
            "startDate": "2012-07-14T00:00:00+02:00"
        },
        {
            "organization": "https://oparl.example.org/organizations/23",
            "role": "stellv. Ausschussvorsitzender",
            "votingRight": true,
            "startDate": "2012-07-14T00:00:00+02:00"
        }
    ],
    "modified": "2012-08-16T14:05:27+02:00"
}


Organization:
{
    "id": "https://oparl.example.org/organization/34",
    "type": "http://oparl.org/schema/1.0/Organization",
    "body": "https://oparl.example.org/bodies/1",
    "name": "Ausschuss für Stadtentwicklung",
    "startDate": "2012-07-17T10:00:00+02:00",
    "modified": "2012-07-17T10:00:00+02:00"
}


Meeting:
{
    "id": "https://oparl.example.org/meeting/281",
    "type": "http://oparl.org/schema/1.0/Meeting",
    "name": "4. Sitzung des Ausschusses für Stadtentwicklung",
    "start": "2012-10-14T16:00:00+01:00",
    "end": "2012-10-14T20:00:00+01:00",
    "room": "Sitzungsraum 204",
    "streetAddress": "Musterstraße 5",
    "postalCode": "11111",
    "locality": "Musterort",
    "organization": [
        "https://oparl.example.org/organization/34"
    ],
    "invitation": {
        "name": "Einladung",
        "modified": "2012-10-10T14:00:00+01:00",
        "accessUrl": "https://oparl.example.org/files/57739.pdf"
    },
    "resultsProtocol": {
        "name": "Protokoll",
        "modified": "2012-10-15T15:00:00+01:00",
        "accessUrl": "https://oparl.example.org/files/57742.pdf"
    },
    "agendaItem": [
        {
            "number": "1",
            "name": "Eröffnung der Sitzung",
            "public": true
        },
        {
            "number": "2",
            "name": "Feststellung der Tagesordnung",
            "public": true
        },
        {
            "number": "3.1",
            "name": "Neuer Zebrastreifen für die Waldstraße",
            "public": true,
            "paper": "https://oparl.example.org/paper/74",
            "result": "Geändert beschlossen",
            "resolution": "Der Beschluss weicht wie folgt vom Antrag ab: ...",
            "auxiliaryFile": {
                "name": "Kartenausschnitt",
                "date": "2013-01-04T07:50:13+01:00",
                "accessUrl": "https://oparl.example.org/files/57781.pdf"
            }
        }
    ],
    "modified": "2012-10-15T15:00:00+01:00"
}


Paper:
{
    "id": "https://oparl.example.org/paper/74",
    "type": "http://oparl.org/schema/1.0/Paper",
    "body": "https://oparl.example.org/bodies/1",
    "name": "Neuer Zebrastreifen für die Waldstraße",
    "reference": "1234/2014",
    "publishedDate": "2012-10-05T12:00:00+01:00",
    "paperType": "Antrag",
    "mainFile": {
        "name": "Vorlage",
        "date": "2014-04-04T16:42:02+02:00",
        "accessUrl": "https://oparl.example.org/files/57781.pdf"
    },
    "consultation": [
        {
            "meeting": "https://oparl.example.org/meeting/243",
            "organization": "https://oparl.example.org/organization/96",
            "authoritative": false,
            "role": "Beschlussfassung"
        }
    ],
    "location": [
        {
            "description": "Waldstraße, Beispielstadt",
            "geometry": {
                "type": "Point",
                "coordinates": [7.03291, 50.98249]
            }
        }
    ],
    "modified": "2012-10-15T12:00:00+01:00"
}

```

**Vorteile:**

1. Es müssen nur noch die gelöschten Objekte für Sitzungen, Ratsmitglieder, Gremien und Drucksachen ausgegeben werden. Objekte dieser Objekttypen werden allerdings sehr selten gelöscht. Nicht mehr aktive Ratsmitglieder und Gremien bleiben in der Datenbank, auch zurückgezogene Drucksachen bleiben gespeichert. Nicht stattgefundene Sitzungen könnten allerdings von RIS-Benutzern gelöscht werden. Ich vermute aber, dass das von Seiten der RIS-Hersteller so nicht gedacht ist, und dass auch nicht stattgefundene Sitzungen eigentlich in der Datenbank bleiben sollen. Hierzu sollten wir nochmal die RIS-Hersteller fragen. Wenn ein RIS keine gelöschten Objekte ausgeben kann, ist es also vermutlich nicht besonders tragisch. Zu der Ausgabe von gelöschten Objekten kommt auch folgende Alternative in Frage (falls tatsächlich nur sehr selten etwas gelöscht wird): Ein Client könnte die Anzahl der Objekte in der Datenbank, mit den vorhandenen lokalen Objekten abgleichen und falls es lokal mehr Objekte gibt, den Datenbestand neu Synchronisieren.

2. Das Datenmodell ist übersichtlicher. Neben System und Body gibt es nur vier weitere Objekttypen: Person, Organization, Meeting und Paper. Die JSON-Objekte gleichen dann auch der HTML-Ausgabe, dort werden ja auch die Tagesordnungspukte mit der Sitzung, die Beratungen mit der Drucksache und so weiter ausgegeben.

3. Für die AgendaItem-, Consultation-, Membership-, LegislativeTerms-, File- und Location-Objekttypen muss kein eigener `modified`-Zeitstempel ausgegeben werden. Ich denke, es gibt durchaus RISe, die nicht für alle Objekttypen eigene Zeitstempel speichern. Nur für die Person-, Organization-, Meeting- und Paper-Objekttypen muss ein `modified`-Zeitstempel ausgegeben werden.

4. Es gibt Anwendungsfälle, in denen diese Modellierung für Clients praktischer ist, zum Beispiel kann man die JSON-Objekte in dieser Form direkt in dokumentorientierten Datenbanken oder Searchengines (z.B. Elastic Search) abspeichern.

**Nachteile:**

1. Wenn ein Client die OParl-Daten in einer relationalen Datenbank abspeichern will, ist diese Modellierung eher unpraktisch. Bei meinem ursprünglichen Vorschlag konnten die Objekte direkt in einer relationalen Datenbank gespeichert werden. Bei diesem Vorschlag, muss man über die eingebetteten Objekte iterieren und sie mit einem Fremdschlüssel in einer eigenen Tabelle speichern. Ich denke der Aufwand ist aber nicht zu groß.

2. Redundanz, falls dasselbe File- oder Location-Objekte in mehreren Objekten eingebettet wird. Ich denke, dass eine Datei mehrfach verwendet wird, ist eher eine Ausname. Ein und dasselbe Location-Objekt könnte durchaus häufiger verwendet werden, der Overhead sollte aber kein Problem sein.

Ich denke, die Vorteile überwiegen, was meint ihr?

Es könnte sinnvoll sein, dass auch die eingebetteten Objekte IDs bekommen. Die eingebetteten Objekte müssen aber nicht einzeln abrufbar sein. Ich mach mir noch Gedanken, was hier eine gute Lösung sein könnte.
Zu der Problematik mit den Zeitstempeln in alten Daten werde ich mir auch noch Gedanken machen.

**Comment by the-infinity** [comment]
Ich sehe da tatsächlich noch ein sehr weiteres relevantes Problem: wenn ein RIS-Hersteller die OParl-Objekte konsequent umsetzt, wird es sehr aufwändig für ihn. Dann muss er nämlich bei jeder Änderung der eines Tagesordnungspunktes auch gleich immer modified von Meeting ändern, weil ansonsten der Tagesordnungspunkt nicht ausgegeben wird bei dem Abfrage nach Änderungen. Das fände ich unglücklich, weil wir damit aufgrund von Vereinfachung für die RIS-Hersteller jetzt uns ganz erhebliche Probleme für die Zukunft einhandeln, schlichtweg, weil die modified-Werte dann eben schlicht nicht korrekt sind - es ist im Nachhinein ja nicht mehr zu sagen, ob das modified des Meetings nun tatsächlich ein modified des Meetings und nicht des AgendaItems ist.

**Comment by konstin** [comment]
Eine deutlich einfachere Lösung ohne Sonterregelungen wäre es, wenn die RIS-Hersteller Tabellen mit den relevanten Informationen über die gelöschten Objekte Speichern. Das vermeidet auch das Problem, dass clients nicht alle Objekte eines Typ abrufen können, ohne gleichzeitig auch alle Objekte abzurufen, die diesen Typ enthalten könnten. Außerdem werden so Duplakate verhindert, da mehrere Objekte das gleiche Objekt enthalten könnten, ohne dass diese mit Hilfe der ID als gleich erkannt werden können.

**Comment by lu-j** [comment]
Mittlerweile haben wir uns gemeinsam darauf geeinigt, dass wir die Modellierung mit den eingebetteten Objekten ausprobieren wollen.

Was die modified-Werte betrifft, ändert sich eigentlich nichts am aktuellen Stand: im aktuellen Datenmodell gibt es im Meeting-Objekt eine Liste der Ids der Tagesordnungspunkte und wenn ein Tagesordnungspunkt gelöscht wird, ändert sich auch das Meeting-Objekt und der modified-Zeitstempel des Meeting-Objekts sollte auch aktualisiert werden. Das selbe gilt auch für die anderen Objekte. Ich vermute in den meisten RISen werden sowieso keine eigenen Zeitstempel für jeden einzelnen Tagesordnungspunkt (bzw. Beratung oder Mitgliedschaft) gespeichert. Wir können natürlich die modified-Zeitstempel für die eingebetteten Objekte als optionale Eigenschaften weiter beibehalten, falls es doch RISe gibt, die die Zeitstempel speichern. Hierzu will ich die RIS-Hersteller befragen.

Es kann natürlich passieren, dass ein Client nur das Sitzungs-Objekt, aber nicht die Tagesordnungspunkte braucht. Ich denke der Overhead ist aber vernachlässigbar. Schon bei einer gewöhnlichen HTML-Seite mit ein paar Bildern, werden vermutlich größere Datenmengen übertragen. Dass das selbe Objekt mehrmals in andere Objekte eingebettet wird, kann eigentlich nur bei Location- oder File-Objekten passieren. Da die Location-Objekte sehr klein sind, ist es nicht weiter schlimm, wenn man sie redundant speichert. Dass die selbe Datei zwei mal in verschiedenen Vorlagen als Anlage verwendet wird, kommt vermutlich eher selten vor, falls doch, werden im RIS vermutlich sowieso zwei File-Objekte für die selbe Datei gespeichert. Für File-Objekte ist es sehr sinnvoll, dass sie einen modified-Wert haben, dann muss man nur geändert Dateien neu herunterladen. Die File-Objekte brauchen auch eine Art Id, damit man die bereits heruntergeladenen Dateien wieder richtig zuordnen kann. Hier könnte man aber auch die Download-URL benutzen. Trotzdem könnte es sinnvoll sein, dass auch eingebettete Objekte ihre Id behalten. Das könnte zum Beispiel bei Problemfällen beim Debugging helfen. Ich will weiter überlegen, wie wir das am Besten lösen können.

**Comment by konstin** [comment]
> Trotzdem könnte es sinnvoll sein, dass auch eingebettete Objekte ihre Id behalten. Das könnte zum Beispiel bei Problemfällen beim Debugging helfen. Ich will weiter überlegen, wie wir das am Besten lösen können.

Die ID sind auch praktisch, wenn man z.B. einfach nur ein schnell eine Datei abrufen will, ohne den Umweg über paper zu gehen.

**Comment by the-infinity** [comment]
Die von @lu-j angesprochene Lösung findet sich auch bereits auf Politik Bei Uns wieder: https://politik-bei-uns.de/oparl . Mitsamt IDs.

**Comment by the-infinity** [comment]
Wurde durch den Fix von @lu-j erledigt.
