### ISSUE TITLE
Mehr als ein System Objekt zulassen, um als Server verschiedene OParl Versionen parallel anbieten zu können

### ISSUE THREAD

**Issue by lu-j** [OParl/spec#293]
Da es in ferner Zukunft eine inkompatible OParl Version 2.0 geben könnte, sollte es die Möglichkeit geben, dass ein Server beide Versionen parallel unter verschiedenen URLs anbietet. Unklar ist jedoch wie die URLs an den Client kommuniziert werden können.

Auf dem Workshop gab es die Idee, in diesem Fall zwei System Objekte auszugeben. Ein System Objekt für OParl Version 1 und ein System Objekt für OParl Version 2, die dann auf jeweils unterschiedliche Body URLs verweisen (zum Beispiel http://oparl.example.org/v1/bodies/1 und http://oparl.example.org/v2/bodies/1).

Mir gefällt die Idee sehr gut. Die Änderung bewirkt, dass der API-Endpunkt eine Liste aller System-Objekten ausgeben muss. Diese Liste wird in den meisten Fällen nur ein einziges System Objekt für die zu diesem Zeitpunkt aktuelle OParl-Version enthalten. Kommt aber eine neue nicht rückwärtskompatible OParl Version heraus, kann ein Server sie parallel anbieten ohne warten zu müssen, bis alle Clients die neue Version unterstützen. Auch Testphasen kann man so realisieren, ein Server kann beispielsweise parallel zur Version 1.0 eine 2.0-beta anbieten.

**Comment by akuckartz** [comment]
Allgemein zur Versionierung von Schnittstellen (und REST), ein Zitat von Roy T. Fielding aus einem Interview vom Dezember 2014:

> Either, (a) the version is eventually changed and all of the components written to the prior version need to be restarted, redeployed, or abandoned because they cannot adapt to the benefits of that newer system, or (b) the version is never changed and is just a permanent lead weight making every API call less efficient.

> A lot of developers throw up their hands in disgust at this point and claim that I just don’t understand their problem. Their systems are important. They are going to change. New features are going to be provided. Data is going to be rearranged. They need some way to control how old clients can coexist with new ones.

> Naturally, that is where I have to explain why "hypermedia as the engine of application state" is a REST constraint. Not an option. Not an ideal. Hypermedia is a constraint. As in, you either do it or you aren’t doing REST. You can’t have evolvability if clients have their controls baked into their design at deployment. Controls have to be learned on the fly. That’s what hypermedia enables.
http://www.infoq.com/articles/roy-fielding-on-versioning

**Comment by lu-j** [comment]
Ich habe den Vorschlag wie oben beschrieben eingearbeitet.
