### ISSUE TITLE
Neue Eigenschaft für Meeting: Raumangabe

### ISSUE THREAD

**Issue by lu-j** [OParl/spec#294]
Auf dem Workshop haben wir beschlossen:
Wir wollen die neue Eigenschaft "meetingRoom" für Meeting-Objekte aufnehmen. In "meetingRoom" soll angegeben werden in welchem Raum die Sitzung stattfindet/stattgefunden hat. Diese Eigenschaft ist in der Regel auch in den RISen vorhanden.
Wie immer freuen wir uns über Feedback!

**Comment by konstin** [comment]
+1

**Comment by akuckartz** [comment]
Siehe auch https://github.com/schemaorg/schemaorg/issues/545

**Comment by akuckartz** [comment]
Zwei Anmerkungen:

# Das "meeting" in `meetingRoom` ist aufgrund der Zuordnung zu einem Meeting redundant. In dem für Locations relevanten INSPIRE Dokument wird `roomName` spezifiziert.

#Sitzungen benötigen auch weitere Adress-Infomationen, letztendlich also eine Adresse. Gleichzeitig gibt es eine Spezifikation für Location - in der aber Adressangaben bisher nicht vorgesehen sind. Man könnte deshalb alternativ auch Location entsprechend erweitern und von Meeting auf Location verweisen.

**Comment by konstin** [comment]
Eine echte Adresse ist aber schwierig, wenn als Ort nur „großer Sitzungssaal“ angegeben ist

**Comment by eFrane** [comment]
Locationobjekte sind Orte, die eine definierte Adresse haben, "großer Sitzungssaal" wie @konstin gerade schon eingeworfen hat, ist ein wunderbares beispiel für ein glaubwürdiges Datum dieses Feldes, was nicht als valide Adresse geschrieben werden kann. Demnach gehört das auch nicht in das Locationobjekt sondern sehr wohl in eine Eigenschaft von Meeting.

Allerdings finde ich `roomName` auch eine bessere Bezeichnung für diese Eigenschaft als `meetingRoom`. Vielleicht auch schlicht und einfach nur `room`.

**Comment by akuckartz** [comment]
Sitzungen von Stadträten und Ausschüssen finden regelmäßig an "definierten Adressen" statt. Und diese Adressen können prinzipiell auch von RIS ausgegeben werden. Dass "großer Sitzungssaal" für sich genommen keine global eindeutige Adresse ist, ändert nichts an seiner Eigenschaft als Angabe einer Location.

**Comment by lu-j** [comment]
Die Adresse des Sitzungsortes kann bereits gespeichert werden, im Meeting-Objekt gibt es schon Eigenschaften für Straße und Hausnummer, Postleitzahl und Ort. Das Location-Objekt ist für Geodaten gedacht, vielleicht wäre Geolocation ein besserer Name für diesen Objekttyp. Wir könnten zwar überlegen, ob wir alle Adressen in einem Location-Objekt speichern wollen, ich kann mir aber vorstellen, dass ein RIS Adressdaten nicht immer in einer eigenen Tabelle speichert. Zum Beispiel bei den Personendaten ist die Anschrift vermutlich direkt in der Personen-Tabelle gespeichert. Wenn für OParl alle Adressdaten aber getrennt als Location-Objekte ausgegeben werden müssen, ist das etwas aufwendiger zu implementieren. Aktuell sind die Adresseigenschaften auch noch etwas inkonsistent. Die Probleme mit den Adressdaten möchte ich aber in einem eigenen Issue behandeln.

Ich denke "meetingRoom" wurde gewählt, weil es auf englisch Sitzungsraum bedeutet. Dass der Objekttyp selbst auch Meeting heißt, ist natürlich ungünstig. "room name" scheint im Englischen kaum verwendet zu werden und ich konnte es auch nicht in Wörterbüchern finden. Auch haben nicht alle Räume einen richtigen Name, ich denke es wird auch oft eine Ortsbeschreibung angegeben, zum Beispiel "Seminarraum im 1. OG" Ich denke vorerst ist "room" wahrscheinlich der beste Name für die Eigenschaft. Wenn das Schema fertig ist, sollten wir sowieso nochmal schauen, ob die Namen der Eigenschaften gut zusammenpassen.

**Comment by konstin** [comment]
Ich fände es zumindest für Version 1.0 am sinnvollsten, einfach zu `Meeting` die Eigenschaft `room` hinzu zu fügen, wobei `room` nicht zwangsweise eine reale Raumnummer sein muss, sondern auch einfach eine Ortsbeschreibung sein kann (also z.B. "Großer Sitzungssaal"). Damit würde sich im Beispiel aus der Spezifikation einfach nur
```json
"streetAddress": "Musterstraße 5, Raum 136",
```
in
```json
"streetAddress": "Musterstraße 5",
"room": "Raum 136",
```
verändern.

Ideal wäre es, ein eigenes Objekt "EventLocation" zu definieren, das einen Versammlungsort eindeutig kennzeichnet. Damit könnte man sich dann z.B. sehr einfach alle Veranstaltungen anzeigen lassen, die in einem Raum stattfinden. Da ich aber vermute das in fast jedem RIS der Ort aber nur als Text gespeichert wird, dürfte das nur sehr schwer zu implementieren sein.

**Comment by lu-j** [comment]
@konstin: genauso habe ich mir das auch vorgestellt und mittlerweile auch so umgesetzt.
Da eine Sitzung meistens am gleichen Ort stattfindet, wird der Ort vermutlich nicht für jede Sitzung erneut eingegeben. Stattdessen wird man wahrscheinlich aus einer Liste bereits verwendeter Orte auswählen können. Zumindest scheinen auf den ersten Blick in den RISen für die selben Orte auch die selben Strings verwendet zu werden. So kann man alle Veranstaltungen abfragen, die in dem selben Raum stattfinden. Ich denke, dass sich ein eigener Objekttyp wie "EventLocation" nur lohnt, wenn in den RISen zu den Orten noch weitere Informationen gespeichert werden.
