### ISSUE TITLE
GeoJSON statt WKT verwenden

### ISSUE THREAD

**Issue by lu-j** [OParl/spec#295]
Auf dem Workshop haben wir beschlossen, dass geprüft werden soll ob sich GeoJSON besser eignet, als das aktuell verwendete Well-Known-Text-Format (WKT).

Ich denke GeoJSON ist für OParl besser als WKT geeignet.

GeoJSON ist ein sehr simples Format, man kann lediglich Punkte, Linien und Polygone speichern. WKT ist um einiges mächtiger, es ermöglicht auch 3D Objekte oder Kreise zu speichern, aber ich vermute der Funktionsumfang von GeoJSON wird uns reichen.

Im Gegensatz zu WKT, kann GeoJSON ohne Plugin von den gängigen Webkarten wie OpenLayers, Leaflet, Google Maps, Bing Maps oder Mapbox eingelesen werden. MySQL und PostGIS unterstützen sowohl WKT als auch GeoJSON, was praktisch ist, wenn man geospatial queries in der Datenbank machen möchte. Microsoft SQL Server (der vermutlich bei manchen RISen zum Einsatz kommt) unterstützt bisher nur WKT und GML.

Hat man nur Geopunkte gespeichert, sollte es aber kein Problem sein, GeoJSON manuell zu erzeugen. Hier ein Beispiel für einen Geopunkt in GeoJSON:

~~~
{ 
  "type": "Point", 
  "coordinates": [13.398202657699585, 52.52086918882907] 
}
~~~

Mit GeoJSON kann man zusätzliche Informationen zu den Geokoordinaten speichern, allerdings werden diese nicht von GeoJSON standardisiert. Es gibt von Mapbox den [simplestyle](https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0) Standard, der es unter anderem ermöglicht Flächen unterschiedlich einzufärben und sie mit Hinweistexten zu versehen. Simplestyle ist allerdings noch nicht weit verbreitet und ich vermute in OParl werden zunächst sowieso nur Punkte und Polygone ohne Styling gespeichert. Einen Beschreibungstext kann man bereits im Location Objekt speichern. Für kommende Versionen von OParl könnten wir können wir noch mal schauen, ob es bis dahin einen verbreiteten Styling-Standard gibt, den wir aufnehmen können.

Der GeoJSON Standard ist im Jahr 2008 in Version 1.0 erschienen und hat sich seitdem nicht verändert. Allerdings wird aktuell ein RFC zu GeoJSON geschrieben, dabei wird sich aber voraussichtlich nicht viel am Standard ändern.

So weit ich weiß sind aktuellen in keinem der großen RISe Geokoordinaten gespeichert. Das Thema ist also erst mal nur relevant für Server, die RIS-Daten sammeln, nachträglich georeferenzieren und im  OParl-Format ausgeben. Ich denke für dieses Szenario ist GeoJSON besser als WKT geeignet.

Ich könnte mir vorstellen, dass die RIS Systeme in Zukunft auch mit den Geoportalen zusammenarbeiten. Die Geoportale geben die Daten in der Regel in Form von GML aus und verwenden für die Koordinaten oft nicht das für Webkarten übliche WGS-84 Referenzsystem (das auch für die GPS-Koordinaten genutzt wird). Wenn es so weit ist, sollten wir schauen ob die RISe oder die Geoportale die Daten in GeoJSON mit WGS-84 Referenzsystem umrechnen können, oder ob wir auch GML und weitere Referenzsysteme erlauben sollten. Für OParl 1.0 sollten wir meiner Meinung nach nur GeoJSON und WGS-84 erlauben.

**Comment by akuckartz** [comment]
Siehe auch https://github.com/schemaorg/schemaorg/issues/113 https://github.com/OpenGovLD/specs/issues/10 https://github.com/OpenGovLD/specs/issues/66 #103 und #143

**Comment by eFrane** [comment]
Warum sollten wir Restriktionen für die Repräsentation der Koordinaten einführen? Die GeoJSON Spezifikation [schreibt eindeutig vor](http://geojson.org/geojson-spec.html#coordinate-reference-system-objects), dass standardmäßig von WGS-84 ausgegangen wird und bei Abweichungen die Angabe eines `crs`-Keys für das verwendete Referenzsystem möglich ist. Wir sollten dementsprechend vielleicht eher verlangen, dass die Angabe des Referenzsystems zwingend ist, sofern nicht WGS-84 verwendet wird.

**Comment by akuckartz** [comment]
> MySQL und PostGIS unterstützen sowohl WKT als auch GeoJSON, was praktisch ist, wenn man geospatial queries in der Datenbank machen möchte. Microsoft SQL Server (der vermutlich bei manchen RISen zum Einsatz kommt) unterstützt bisher nur WKT und GML.

Also ist WKT das einzige Format, welches bei einem Großteil der gegenwärtig üblicherweise verwendeten Datenbanken unterstützt wird. Sowohl Leaflet als auch OpenLayers können z.B. mittels https://github.com/mapbox/leaflet-omnivore mit WKT umgehen.

> So weit ich weiß sind aktuellen in keinem der großen RISe Geokoordinaten gespeichert. Das Thema ist also erst mal nur relevant für Server, die RIS-Daten sammeln, nachträglich georeferenzieren und im OParl-Format ausgeben.

Wenn ich das richtig verstehe, dann soll durch den vorgeschlagenen Schwenk von WKT zu GeoJSON also _nicht_ etwa die jetzige oder absehbare Arbeit von RIS-Herstellern erleichtert werden, sondern die von Herstellern von aggregierenden Systemen - sogar wenn die Arbeit für RIS-Hersteller dadurch tendentiell erschwert wird. Ich halte das zwar nicht prinzipiell für falsch, aber es entspricht nicht dem Eindruck der bisher zur Zielsetzung von "OParl 1.0" vermittelt wurde.

**Comment by eFrane** [comment]
Es ist schon richtig, dass GeoJSON eventuell etwas mehr Implementationsarbeit bedarf, als WKT, aber die Zielsetzung der Einfachheit von OParl ist auch auf die Nutzer gemünzt und GeoJSON entwickelt sich mehr und mehr zum de-facto Standard für die plattformübergreifende Darstellung von Geodaten. 

Zudem wäre es auch im Sinne des JSON-Formates unseres Datenmodelles, Geodaten auch als JSON auszugeben.

**Comment by the-infinity** [comment]
Einerseits: die meisten RIS-Hersteller haben zur Zeit noch gar keine Geodaten. Andererseits ist GeoJSON extrem einfach zu implementieren. Und wir waren uns auf dem Workshop recht einig, dass GeoJSON die bessere Wahl wäre, die auf dem Workshop beschlossene Recherche bestätigte dies. Die Diskussion hier geht in dieselbe Richtung, und auch ich bin klar für GeoJSON. In diesem Sinne: eingebaut in https://github.com/OParl/spec/commit/0f300c64148c93bb142a41267df628820617ae76 .

**Comment by akuckartz** [comment]
Das Open Geospatial Consortium hat im August 2015 den inklusive Anlagen 146 Seiten langen Bericht [Testbed 11 Implementing JSON/GeoJSON in an OGC Standard Engineering Report] (https://portal.opengeospatial.org/files/?artifact_id=64595) veröffentlicht.
