### ISSUE TITLE
Defekte Links in Kapitel 4.5

### ISSUE THREAD

**Issue by konstin** [OParl/spec#297]
Die pdf-Version sieht folgendermaßen aus:

> Sämtliche JSON-Ausgabe MUSS in UTF-8 ohne Byte Order Mark (BOM) geschehen. Dies
entspricht [RFC 7159 Section 8.1https://tools.ietf.org/html/rfc7159#section-8.1].
Gemäß [RFC 7159 Section 7https://tools.ietf.org/html/rfc7159#section-7] DARF
UTF-8 String-Escaping verwendet werden. XML- / HTML-String-Escaping DARF NICHT
verwendet werden.

An dieser Stelle halt wohl eine der Zahlen das Erstellen einer Fußnote verhindert.

**Comment by eFrane** [comment]
Danke!

Da war die Markdown Syntax inkorrekt. 

Ich habe das in 41401fe behoben.
