### ISSUE TITLE
Zusätzliche Information bei Paginierung: Anzahl der Seiten und momentane Seitenzahl

### ISSUE THREAD

**Issue by konstin** [OParl/spec#298]
Es wäre sinnvoll, noch ein Attribut zu den Listenseiten hinzuzufügen, das die Gesamtzahl der Listenseiten angibt und noch eines, das die Nummer der momtanen Seite angibt. Damit kann z.B. ein client die Anzahl der noch ladenden Listenseiten anzeigen.

**Comment by eFrane** [comment]
Das ist in der momentanen Implementierung des [Demoservers](http://demoserver.oparl.org/api/v1/person?format=html&only=meta) der Fall. Wie genau das Format endgültig aussieht müssen wir noch erarbeiten, aber in jedem Falle stimme ich zu, dass die von dir genannten zusätzlichen Angaben sinnvoll wären.

**Comment by akuckartz** [comment]
Zum Vergleich: Hydra sieht zwei Properties "totalItems" und "itemsPerPage" vor. Die Gesamtzahl der Seiten ergibt sich aus den beiden Werten.

Wenn Seiten sequentiell beginnend mit der ersten Seite abgerufen werden, dann kann die Nummer der jeweiligen Seite von einem Client mit Hilfe eines Zählers auf einfache Weise festgestellt werden.

**Comment by eFrane** [comment]
Warum aber sollte man Clients Rechenarbeiten auferlegen - und damit die API in der Benutzung verkomplizieren - wenn das auch die Server übernehmen können, für die durch die direkte Datenbankverbindung jedwede notwendige Abfrage zu Paginierung trivial ist.

Ich möchte mich jetzt damit nicht gegen die Art und Weise, wie Hydra das Problem löst aussprechen, aber die Lösung steht meiner Ansicht nach im Widerspruch zu unserem Ziel einer möglichst einfachen Benutzung.

+ Dieses Issue hängt auch mit #291 (Listenausgaben) zusammen.

**Comment by akuckartz** [comment]
> Warum aber sollte man Clients Rechenarbeiten auferlegen - und damit die API in der Benutzung verkomplizieren - wenn das auch die Server übernehmen können, für die durch die direkte Datenbankverbindung jedwede notwendige Abfrage zu Paginierung trivial ist.

Die API wird verkompliziert. Denn solche Eigenschaften MÜSSEN, damit sie von Clients verwendet werden können, von Servern implementiert werden. Wenn solche Eigenschaften nur implementiert werden SOLLEN, dann können Clients sich nicht darauf verlassen. Wenn sie sich nicht darauf verlassen können, dann müssen sie eine Fallunterscheidung vornehmen und entweder keine solche Informationen anzeigen oder doch rechnen. Die Fallunterscheidung ist vermutlich etwas  komplexer als die Rechenoperation (+1).

Außerdem: Für interaktive Clients mögen solche Daten möglicherweise relevant sein. Angesichts der formulierten Zielsetzung der Spezifikation sehe ich für Clients aber keinen ausreichenden Nutzen.

**Comment by the-infinity** [comment]
Ich wäre klar gegen ein MÜSSEN, weil es sicherlich obskure Konstrukte geben wird, um die API zu erstellen. Einige Objekte liegen ja z.B. so gar nicht in der Urspungs-Datenbank vor, sondern werden durch JOINs zusammengebaut, andere liegen in mehreren Tabellen / als mehrere Objekttypen vor, ... etc. Ein OPTIONAL als Angebot, so dass da kein Wildwuchs entsteht, wenn man das Feature anbieten will, wäre dagegen sehr sinnvoll.

**Comment by lu-j** [comment]
Der erste Sync kann schon einige Zeit dauern, wenn man danach aber täglich synchronisiert, sollte das nur wenige Sekunden dauern. Daher ist eine Ladeanzeige nicht so wichtig.

Was ich aber sinnvoll finde, ist eine Ausgabe der Anzahl der gefundenen Objekte, also die Anzahl der Objekte auf allen Seiten. Darüber kann man sowohl eine Ladeanzeige realisieren, aber auch Synchronisierungsfehler entdecken oder feststellen, dass ein Server Objekte gelöscht hat, auch wenn der Server nicht in der Lage ist, gelöschte Objekte auszugeben. Beispiel: ein Client hat die Objekte der letzten fünf Jahre gespeichert. Er fragt zur Kontrolle die Objekte ab, die in den letzten fünf Jahren geändert (bzw. erstellt) wurden. Wenn die Anzahl der gefundenen Objekte geringer ist, als die Anzahl der Objekte in der eigenen Datenbank, sind Objekte gelöscht worden (oder es gab eine fehlerhafte Synchronisierung). Der Client kann jetzt den Datenbestand neu synchronisieren. Wenn es selten vorkommt, dass Objekte gelöscht werden, ist das eine akzeptable Lösung. Es wäre natürlich trotzdem besser, wenn Server die gelöschte Objekte ausgeben können.

Wir können dann auch überlegen, ob wir die zwingende Anforderung entfernen sollten, dass alle Seiten gleich viele Objekte haben müssen (bis auf die letzte Seite, die darf natürlich auch weniger Objekte haben). Für Clients hätte das keinen großen Nachteil, es gibt Serverimplementierern aber mehr Freiheit. Zum Beispiel in diesem Fall: in OParl sind sowohl Gremien, als auch Fraktionen Organization-Objekte. Wenn man Fraktionen und Gremien jedoch in zwei verschiedenen Tabellen speichert, kann man die Tabellen einfach nacheinander ausgeben: auf der ersten Seite gibt man die Gremien aus, auf der zweiten Seite die Fraktionen. Sollte es mehr jedoch mehr Fraktionen als Gremien geben, hätte die zweite Seite mehr Objekte als die Erste, was ein Verstoß gegen die Anforderung wäre. Man könnte natürlich die Objekte zählen und ausrechnen, wie viele Objekte auf der ersten Seite mindestens ausgegeben werden müssten und dann auf der ersten Seite gegebenenfalls sowohl Fraktionen als auch Gremien ausgeben, allerdings fände ich das unnötig kompliziert. Was denkt ihr?

**Comment by konstin** [comment]
> Wir können dann auch überlegen, ob wir die zwingende Anforderung entfernen sollten, dass alle Seiten gleich viele Objekte haben müssen (bis auf die letzte Seite, die darf natürlich auch weniger Objekte haben).

Das halte ich für eine gute Idee, clients bringt die Information, dass alle Seiten gleich viele Einträge sowieso praktisch nichts.

> Was ich aber sinnvoll finde, ist eine Ausgabe der Anzahl der gefundenen Objekte, also die Anzahl der Objekte auf allen Seiten. Darüber kann man sowohl eine Ladeanzeige realisieren, aber auch Synchronisierungsfehler entdecken oder feststellen, dass ein Server Objekte gelöscht hat, auch wenn der Server nicht in der Lage ist, gelöschte Objekte auszugeben.

Kann man das nicht `numberOfPages` * `itemsPerPage` ziemlich gut berechnen. `numberOfPages` widerspricht zwar eigentlich dem Prinzip der stabilen Paginierung, was man aber (hoffentlich) mit dem Hinweis lösen kann, dass sich `numberOfPages` während dem Laden ändern kann.

Für das Problem stabile Paginierung vs. die Möglichkeit, die Anzahl an Einträgen vorherzusagen, würde ich eine andere Lösung vorschlagen, die meiner Ansicht einige Vorteile gegenüber der jetzigen bietet: Clients müssen bei Anfragen für Seiten von paginierten Listen immer einen Zeitstempel für `created` angeben, den sie bei der ersten Anfrage der Liste erhalten. Der Server gibt dann nur Objekte aus, die vor der angebenen Zeit erstellt wurden. Damit wird verhindert, dass zwischenzeitlich hinzugefügte Objekte zu "verschobenen" Listen führen. Das Entfernen von Objekten braucht dabei nicht berücksichtigt zu werden, wenn man zusätzlich festlegt, dass gelöschte Objekte immernoch in der Liste auftauchen müssen.

Mit dieser Methode braucht man bei der Implementierung keine Umwege über die ID mehr zu machen und kann gleichzeitig genaue Vorraussagen über die Anzahl an Objekten treffen.

**Comment by the-infinity** [comment]
> Damit wird verhindert, dass zwischenzeitlich hinzugefügte Objekte zu "verschobenen" Listen führen.

Die wohl simpelste Lösung ist das, was ich nun in der URL bei Politik Bei Uns gemacht habe: Einfach einen Filter auf modified. Vorteil: die Liste bleibt verhältnismäßig stabil. Nachteil: wenn währenddessen Daten aktualisiert wurden, bekommt man aktualisierte Objekte nicht mit. Dies würde aber auch bei einem übergebenen created Wert nicht geändert werden, meine Ausgabe wäre bei neuen Objekten exakt identisch. Andere Möglichkeit: sortieren nach created - aber das wäre arg unglücklich, weil man dann Modifikationen in der Vergangengeit schlicht nicht mitbekommt.
So richtig schön ist das alles nicht ... aber modified-Sortierung dürfte noch am einfachsten sein.

**Comment by the-infinity** [comment]
Um das nochmal aufzunehmen:
> wenn man zusätzlich festlegt, dass gelöschte Objekte immernoch in der Liste auftauchen müssen.
Das wird nicht möglich sein. Leider. Zumindest nicht zwingend.
Und insgesamt: ich glaube nicht, dass wir irgendeine Eigenschaft neben nextPage zwingend machen sollten. Wir scheinen uns ja auch einig zu sein, dass itemsPerPage nicht immer stabil sein muss.

**Comment by the-infinity** [comment]
ItemsPerPage nun optional: https://github.com/OParl/spec/commit/8c1e72a1251d4557ba4d7dd44b94076f3ea47a98 . Damit closed.
