### ISSUE TITLE
Zentrale Liste mit Systemen, die Oparl anbieten

### ISSUE THREAD

**Issue by konstin** [OParl/spec#302]
Sobald die erste Version von OParl freigegeben wird, sollten an einer Stelle, z.B. auf oparl.org, der Name, die web-URL und die OParl-URL aller Systeme gesammelt werden, die OParl anbieten. Die Liste sollte auch maschienlesbar zur Verfügung stehen, z.B. damit Nutzer in einem client direkt ihre Kommune auswählen können, ohne erst die OParl-URL herausfinden zu müssen.

**Comment by eFrane** [comment]
Das ist schon seit langem in Planung und wird umgesetzt, sobald der Standard verabschiedet ist. Damit soll auch einhergehen, dass alle OParl-Systeme an zentraler Stelle gespiegelt werden.

**Comment by eFrane** [comment]
Ich verschiebe das mal in Richtung OParl 1.1, da ja die Grundvoraussetzung "veröffentlichter Standard" gegeben ist.

**Comment by eFrane** [comment]
Der Anfang dieser Liste findet sich hier https://github.com/OParl/resources/blob/master/Implementierungen.md

**Comment by eFrane** [comment]
Unter https://dev.oparl.org/endpunkte ist eine Liste der bekannten Oparl-Endpunkte einsehbar. Diese Liste kann durch Bearbeiten von `endpoints.yml` in [OParl/resources](https://github.com/OParl/resources) erweitert werden. Des wird die selbe Liste auch als JSON-API unter https://dev.oparl.org/api/endpoints zur Verfügung gestellt. Diese API wird neben weiteren noch in Planung befindlichen Nicht-Demoserver-APIs des Entwicklerportals demnächst dort auch prominent dokumentiert sein. Ich wollte das hier nur der Vollständigkeit halber schon mal mit nennen.

Damit ist der ursprüngliche Punkt dieses Issues - eine Liste von OParl-Systemen einzurichten - erledigt.
