### ISSUE TITLE
oparl.org auf https umstellen

### ISSUE THREAD

**Issue by konstin** [OParl/spec#303]
Im Moment wird man von https://oparl.org auf http//:oparl.org umgeleitet.

**Comment by akuckartz** [comment]
:+1:

**Comment by the-infinity** [comment]
Wird erledigt, sobald oparl.org auf die neue OKF-WordPress-Infrastruktur umzieht. Im Moment ist oparl.org auf meinem Blognetzwerk, war eine temporäre Zwischenlösung.

**Comment by the-infinity** [comment]
Done.

**Comment by konstin** [comment]
:tada: 

Im moment beschwert sich aber noch der mixed content blocker in firefox: "Blocked loading mixed active content "http://fonts.googleapis.com/css?family=Dosis&ver=4.3.1"

**Comment by the-infinity** [comment]
Ooops. Fixed.

**Comment by konstin** [comment]
btw wird spec.oparl.org auch auf https umgestellt?

**Comment by lu-j** [comment]
spec.oparl.org wird aktuell noch von einem anderen Server ausgeliefert. Die kostenlosen Zertifikate gelten leider nur für die Domain, aber nicht für Subdomains. Wir schauen mal wie wir das lösen können, spätestens sobald Let's Encrypt verfügbar ist, sollte das aber kein Problem mehr sein :) Die fertige Spezifikation können wir auch über oparl.org bereitstellen, spec.oparl.org ist ja mehr eine Vorschau für den aktuellen Stand.

**Comment by the-infinity** [comment]
Das stimmt nicht ganz. Ich kann auch kostenlose Certs für Subdomains erstellen. Aber den Spaß mit den Certs können wir ja für die Final anbieten, das Generieren via StartSSL ist schon ziemlich nervig (hab gerade ca. 50 Seiten auf StartSSL umgestellt ... was ein Krampf).
