### ISSUE TITLE
Formatierungsfehler in der html-Version

### ISSUE THREAD

**Issue by konstin** [OParl/spec#304]
Probleme in der html-Version, die ich gefunden habe:
 * Das Kapitels "dateizugriff" wird nicht als eigenständiges Kapitel dargestellt
 * Einige der html-Anker (das #kapitelname am Ende der URL) funktionieren nicht. Ideal wäre der Einsatz eines linters, der das automatisiert feststellt, aber leider habe ich keinen finden können.

**Comment by eFrane** [comment]
3c76d5 sollte diese Probleme lösen.
