### ISSUE TITLE
Einheitliche Angabe für `Body:License` bei unbekannter Lizenz

### ISSUE THREAD

**Issue by konstin** [OParl/spec#306]
Es gibt den Fall, dass Informationen und Dokumente in einem RIS bereitgestellt werden, ohne das eine Lizenz angegeben wird. Für diesen Fall sollte ein einheitlicher Wert für `Body:license` festgelegt werden, sodass clients diese Information entsprechend verarbeiten können.

**Comment by akuckartz** [comment]
Wenn es keine Lizenz gibt, warum dann eine angeben?

**Comment by konstin** [comment]
Upps, die Angabe ist ja überhaupt nicht zwingend ...
