### ISSUE TITLE
Beispiele in Anhang verschieben

### ISSUE THREAD

**Issue by eFrane** [OParl/spec#309]
Für den Lesefluss der Spezifikation wäre es meiner Ansicht nach besser, wenn wir die Code-Beispiele im Schema-Abschnitt in einen Anhang verschieben. Sie sind zwar wichtig zur Vollständigkeit des Dokumentes, müssen aber nicht unbedingt in der formalen Auflistung auftauchen.

**Comment by konstin** [comment]
Ich fände es besser, wenn die Beispiele im Fließtext eingebettet bleiben, weil sie bei einigen Einträgen sehr wichtig für das Verständnis sind, z.B. bei der Listenausgabe.

**Comment by eFrane** [comment]
Dort wo sie wichtig zum Verständnis sind, sollten sie auch verbleiben. In der formalen Auflistung der Schnittstelle finde ich sie aber störend, wenn ich diesen Abschnitt aus der Sicht eines Implementierers betrachte.

**Comment by konstin** [comment]
Wie wäre es, bei schwer zu verstehenden Eigenschaften das Beispiel direkt in die Tabelle einzubetten? Damit kann man die Spezifikation von oben nach unten lesen und muss nicht zwischen Tabelle und Beispiel wechseln. Die vollständigen Beispiele kann man trotzdem noch im Anhang zeigen.

**Comment by eFrane** [comment]
Hat sich erledigt.
