### ISSUE TITLE
Dokumentenabruf via URL

### ISSUE THREAD

**Issue by bschalitz** [OParl/spec#31]
Der Standard sollte beim Dokumentenabruf neben dem Streamen (Antwort des Servers 
 *  200 OK) auch 
auch
 *  307 Moved Temporarily :
"Der angeforderte URL wurde verschoben, aber nur temporär. Der Location-Header enthält die neue Position, über die zukünftige Gültigkeit dieses Redirects wird aber nichts ausgesagt. Der Client sollte auch zukünftig den Original-URL besuchen."

vorgesehen. Damit ergibt sich serverseits die Möglichkeit, neben einem Streamen des binären Inhalts optional auch ein Redirect auf einen (Zufalls-) URL auszuführen.

**Comment by konstin** [comment]
Gelöst in Kapitel 2.7 „Dateizu­griffe“
