### ISSUE TITLE
Spezifikation kompakter machen

### ISSUE THREAD

**Issue by lu-j** [OParl/spec#310]
Auf dem Workshop haben wir beschlossen: Die Spezifikation ist aktuell sehr lang und unübersichtlich. Die Texte sollen überarbeitet werden, sodass zuerst die Geschichte und Ziele von OParl behandelt werden und dann möglichst kurz und präzise die technischen Anforderungen für OParl-Server und Clients beschrieben werden. Erklärungen zu Webtechniken und Hinweise zur Implementierung sollen in den Anhang verschoben werden.

Ich schlage folgende neue Struktur vor:

1.  Einleitung (Enthält keine technischen Anforderungen. Wenn man OParl implementieren möchte, kann man dieses Kapitel überspringen.)
2.  Prinzipien und Funktionen der Schnittstelle
3.  Schema
4.  Anhang

Das aktuelle Kapitel "2 Architektur" enthält keine wichtigen Informationen, daher will ich es entfernen. Wie die Schnittstelle funktioniert will ich im Kapitel "Prinzipien und Funktionen der Schnittstelle" beschreiben.

Das aktuelle Kapitel "3 Nutzungsszenarien" soll ein Unterkapitel des Einleitungskapitels werden.

Ich würde gerne Änderungen schon vornehmen. Falls es Widersprüche oder bessere Vorschläge gibt, kann ich gerne alles Rückgängig machen :)

**Comment by the-infinity** [comment]
Just do it! :)

**Comment by konstin** [comment]
+1

In diesem Zusammenhang sollte auch das Datenschutz-Kapitel in den 2. Teil verschoben werden, da dieses Kapitel relevant für die Implementierung ist.

**Comment by the-infinity** [comment]
Das wurde ja bereits vollzogen. Also closed.
