### ISSUE TITLE
Neue Eigenschaft: `possiblyRelated`

### ISSUE THREAD

**Issue by konstin** [OParl/spec#311]
Neben den Objekton, die logisch miteinander verknüpft sind (z.B. Paper:relatedPaper), gibt es auch solche, die inhaltlich ähnlich sind. Solche Dokumente werden Nutzern oft in „könnte sie auch interessieren“-Spalte pränsetiert, weshalb sie auch über OParl abrufbar sein sollten. Die Eigenschaft sollte in allen Objekten angegeben werden dürfen und als Wert ein Array von Objekten des gleichen Typs enthalten.

**Comment by eFrane** [comment]
:+1:

**Comment by lu-j** [comment]
Das automatische Finden von ähnlichen Drucksachen ist eine gute Idee und ein super Anwendungsfall für OParl!
Allerdings wäre ich nicht dafür, diese Eigenschaft direkt in OParl aufzunehmen. Keines der großen RISe unterstützt diese Funktion und es handelt sich nicht um Daten, die direkt von der Kommune veröffentlicht werden, auf solche Daten möchte ich mich aber in OParl 1.0 konzentrieren. 

Allerdings würde sich die Eigenschaft gut als "Herstellerspezifische Erweiterung" eignen, die OParl-Schnittstelle von München-Transparent könnte die Eigenschaft mit Präfix als "muenchen-transparent:possiblyRelated" ausgeben. Ich denke, dass das für eine solche Eigenschaft auch sinnvoll ist, da der Wert dieser Eigenschaft ja nicht eindeutig ist, verschiedene Systeme können (z.B. durch verschiedene Algorithmen) auf verschiedene Ergebnisse kommen.

Wenn die RISe sich in Zukunft aber weiterentwickeln, kann ich mir durchaus vorstellen, dass sie auch solche automatisch berechneten Werte ausgeben können und es sich dann lohnt diese auch in OParl aufzunehmen.

**Comment by konstin** [comment]
Dann werde ich das als Herstellerspezifische Erweiterung umsetzen.

Das issue würde ich offen lassen, um diesen Vorschlag für spätere Versionen von OParl zu dokumentieren.

**Comment by eFrane** [comment]
Ich habe das Issue mal in den nächsten Milestone verschoben.

**Comment by akuckartz** [comment]
Wie wurde dieses Issue gelöst?

**Comment by konstin** [comment]
Garnicht. Ich bin bloß mittlerweile wie @lu-j der Meinung, dass das hinter einen Vendor-Prefix und nicht in die offzielle Spezifikation gehört. Das Attribut enthält keine offiziellen Daten dar, sondern lediglich eine Möglichkeit der Nutzerführung.

**Comment by akuckartz** [comment]
Das ist ja auch eine Lösung ;-)
