### ISSUE TITLE
Probleme mit `Paper:mainFile`

### ISSUE THREAD

**Issue by konstin** [OParl/spec#312]
Es ist oft nicht eindeutig feststellbar, was bei einer Drucksache das wichtigste Dokumente ist. Beispiel: Bei Stadtratsanfragen gibt es eine Anfrage und ein Antwortschreiben. Welches davon ist das mainFile? Bei Anträgen gibt es in München neben diversen anderen Dokumenten einen ursprünglichen Antrag und eine am Ende relevante Beschlussvorlage. 

Auẞerdem stellt das RIS der Stadt nicht dar, bei welchem Dokument es sich um was für einen Typ handelt, weshalb das aus dem Titel geraten werden muss.

**Comment by akuckartz** [comment]
Antrag und Antwort sind verschiedene Vorlagen.

**Comment by konstin** [comment]
In diesem Fall gibt es keine Möglichkeit, das münchner RIS korrekt auf OParl abzubilden.

**Comment by eFrane** [comment]
Intuitiv würde ich sagen die erste Datei in einem Paper ist das mainFile. Trotzdem hat aber auch @akuckartz recht, dass die beschriebene Situation eigentlich in zwei Paper Entities kulminieren sollte. Die können ja durchaus zum selben Agenda Item o. ä. gehören.

**Comment by akuckartz** [comment]
@konstin Stützt sich die Aussage auf eine Kenntnis der im Münchner RIS intern verwendeten Datenstrukturen ?

**Comment by konstin** [comment]
Das eigentliche Problem ist, dass im münchner RIS die zentrale Struktur ein Typ ist, der i.d.R. entweder eine Anfrage oder ein Antrag ist, dem einige Dokumente ohne Hierachie zugeordnet sind. Das ganze auf OParl abzubilden ist mit der momentanen Struktur sehr schwierig.

**Comment by konstin** [comment]
@akuckartz: Mit den Interna des RIS der Stadt kenne ich mich nicht aus, aber ich bin Mitentwickler eines alternativen RIS für München (https://muenchen-transparent.de), das sehr wahrscheinlich OParl für München implementieren wird.

**Comment by akuckartz** [comment]
@konstin Ich werde mich demnächst wegen OpenGovLD / OParl-LD an die Verwaltung der Stadt München wenden und u.a. um Übermittlung von Dokumentation dieser Datenstrukturen bitten. Ergebnisse würde ich euch zugänglich machen.

**Comment by konstin** [comment]
Auch wenn das jetzt etwas vom eigentlichen Thema wegführt: Nach Aussage der Stadt ist es schwierifg, ins bestehende RIS eine Schnittstelle einzubauen. Deshalb ist der Plan im Moment, die Schnittstelle in München Transparent einzubauen, und dann dafür den Segen der Stadt zu bekommen. Wir sind aber natürlich auch für Alternativen offen und freuen uns über alle Informationen, die wir bekommen.

**Comment by lu-j** [comment]
Erstmal vorweg: wir haben die Paper in OParl bisher immer Drucksachen genannt, so gut wie alle Kommunen und RISe verwenden aber den Begriff Vorlage. Von daher würde ich lieber den Begriff Vorlage verwenden und in der Spezifikation "Drucksache" durch "Vorlage" ersetzen.

In den großen RISen kann man eine Datei als Vorlage, also als mainFile markieren, die anderen Dateien sind dann Anlagen. Was genau das mainFile ist, unterscheidet sich zwischen den Kommunen. Wenn ich das richtig gesehen habe, gibt es auch Kommunen, die das mainFile austauschen. Beispiel: zuerst ist der Antrag das mainFile, sobald eine Beschlussempfehlung vorliegt, wird sie zum mainFile, der Antrag wird zur Anlage.

Für Anfragen gibt es von den großen RISen scheinbar keine native Unterstützung. Es gibt Kommunen die ihre Anfragen gar nicht oder nicht alle Arten von Anfragen im RIS veröffentlichen. Hier eine kurze Übersicht, welche Arten von Anfragen ich bisher in den RISen gesehen habe:

**1. Mündliche Antwort auf mündliche Anfrage:**
Meistens findet man im Protokoll nur die Info wer gefragt und wer geantwortet hat (es sei den es wurde ein Wortprotokoll beantragt).

**2. Schriftliche Antwort auf mündliche Anfrage:**
Für die Antwort wird eine Vorlage erstellt, darin wird meistens die Frage nochmal kurz erläutert. Die Vorlage mit der Antwort wird oft in der nächsten Sitzung zur Kenntnis genommen. Die Sitzung wird dann in die Beratungsfolge der Vorlage eingetragen.

**3. Mündliche Antwort auf schriftliche Anfrage:** 
Für die Anfrage wird eine Vorlage erstellt. Die Sitzung, in der die Anfrage mündlich beantwortet wird, wird in die Beratungsfolge der Vorlage eingetragen.

**4. Schriftliche Antwort auf schriftliche Anfrage:**
Hier habe ich schon verschiedene Varianten gesehen. Meistens wird für die Anfrage eine Vorlage erstellt und die Antwort als Anhang hinzugefügt. Dass die Antwort direkt in die Vorlage geschrieben wird, habe ich auch schon ein paar mal gesehen. Einmal habe ich auch gesehen, dass für die Antwort eine eigene Vorlage angelegt wurde (in OParl wäre das ein eigenes Paper-Objekt), beide Vorlagen wurden dann miteinander referenziert.

Es gibt also verschiedene Varianten Anfragen im RIS zu speichern. Für zukünftige OParl-Versionen können wir gemeinsam mit Kommunen und RIS-Herstellern überlegen, ob es möglich ist, Anfragen besser im RIS abzubilden.

Das Münchner RIS kann zwischen Anträgen/Anfragen und Vorlagen unterschieden. In OParl sind das alles Paper-Objekte, der Typ kann mit der Eigenschaft paperType angegeben werden.
Auf den ersten Blick scheint im Münchner RIS die jeweils erste Datei, die Datei zu sein, die bei anderen RISen die Vorlage, also das mainFile wäre, die weiteren Dateien sind dann Anlagen. Ich denke es reicht aus, das erstmal so zu lösen, da das mainFile in den Kommunen sowieso keine eindeutige Bedeutungen hat.

**Comment by konstin** [comment]
> Das Münchner RIS kann zwischen Anträgen/Anfragen und Vorlagen unterschieden. In OParl sind das alles Paper-Objekte, der Typ kann mit der Eigenschaft paperType angegeben werden.
Auf den ersten Blick scheint im Münchner RIS die jeweils erste Datei, die Datei zu sein, die bei anderen RISen die Vorlage, also das mainFile wäre, die weiteren Dateien sind dann Anlagen. Ich denke es reicht aus, das erstmal so zu lösen, da das mainFile in verschiedenen Kommunen sowieso eine unterschiedliche Bedeutung haben kann.

Eine andere Lösung wäre `auxilauryFile` durch eine Eigenschaft zu ersetzen, die alle Dokumente (auch das `mainFile`) zu einer Drucksache/Vorlage enthält, sodass `mainFile` nur noch optional angegeben wird, wenn es auch tatsächlich vorhanden ist.

**Comment by lu-j** [comment]
> Eine andere Lösung wäre auxilauryFile durch eine Eigenschaft zu ersetzen, die alle Dokumente (auch das mainFile) zu einer Drucksache/Vorlage enthält, sodass mainFile nur noch optional angegeben wird, wenn es auch tatsächlich vorhanden ist. 

Gute Idee, ich würde es aber leicht abgeändert lösen: es kann ein mainFile geben, die auxilauryFile sind alle übrigen Dateien (außer dem mainFile). Ich denke so ist es einfacher und so in der Art haben wir es auch bei Meeting gelöst.
Ich habe auch schon in einem RIS eines Beliner Bezirks gesehen, dass es bei manchen Vorlage nur Anlagen gab, war zwar eher eine Ausnahme, zeigt aber, dass es durchaus vorkommen kann.
Ich werde den Text anpassen und darauf hinweisen, dass es nicht immer ein mainFile gibt.

**Comment by akuckartz** [comment]
Nach meinem Verständnis besteht eine Drucksache oder Vorlage aus einer Menge von Dokumenten. Einzelne Dokumente darin können z.B. ein Hauptdokument, ein Antrag, ein Antwortschreiben, eine Beschlussvorlage oder eine Anlage sein (wobei diese möglicherweise nicht zwingend disjunkt sind). Diese Unterscheidung steht in einer engen Beziehung zu der aktuell `paperType` genannten Property von `Paper`.

Interessant ist, dass die Dokumente noch feiner klassifiziert werden können. So gibt es ja recht unterschiedliche Arten von Anlagen. Bisher werden solche Klassifizierungen allerdings kaum durch RISe unterstützt.

**Comment by konstin** [comment]
> Interessant ist, dass die Dokumente noch feiner klassifiziert werden können. So gibt es ja recht unterschiedliche Arten von Anlagen. Bisher werden solche Klassifizierungen allerdings kaum durch RISe unterstützt.

Ich gehe davon aus, dass daran gearbeitet wird, sobald OParl 1.0 fertig ist. Das Problem ist allerdings, dass jede Stadt bzw, Kommune ihre eigene Definition für die verschiedenen Antragstypen hat, was eine Klassifizierung erschwert.

**Comment by the-infinity** [comment]
Sollte durch den Fix von @lu-j erledigt sein.
