### ISSUE TITLE
Kapitel zum Thema "Rate Limits"

### ISSUE THREAD

**Issue by konstin** [OParl/spec#315]
Das Stellen vieler komplexer Anfragen kann dazu führen, dass ein Server überlastet wird, und im schlimmsten Fall für einige Zeit nicht erreichbar. Diese Problematik sollte in einem eigenen Kapitel erläutert werden, in dem auch erklärt werden sollte, wie server-Betreiber das verhindern können und wie server clients mitteilen, dass sie eine Anfrage wegen der Gefahr von Überlastung bzw. wegen rate limits nicht beantworten.

**Comment by akuckartz** [comment]
HTTP error code 503: Service Unavailable.

**Comment by noxer** [comment]
429	Too Many Requests

**Comment by lu-j** [comment]
So wie ich das bis jetzt beobachtet habe, sind die RIS-Server in den meisten Fällen hinter einem Webserver, der dann auch die Fehlermeldung inkl. Statuscode ausgibt, wenn das RIS nicht innerhalb eines Timeouts (z.B. 90 Sekunden) geantwortet hat. Ich denke das wird dann auch passieren, wenn das RIS wegen zu vielen Anfragen überlastet wird. Die RIS-Software wird also vermutlich sowieso nicht immer selbst entscheiden können welche Fehlermeldung und welcher Statuscode ausgegeben wird. Ich vermute rate limiting würde man auch eher über den Webserver oder den Reverse Proxy machen und es nicht im RIS-Server implementieren.

Ich denke Tipps zur Vermeidung von Überlastung speziell für OParl können wir nicht geben. Was wir von unserer Seite tun könnten ist, dass wir festlegen, dass man nur die Änderungen seit einem bestimmten Tag abrufen kann, ohne Angabe einer Uhrzeit. Damit würde die täglich synchronisierenden Clients die selben Anfragen stellen und man könnte die Antwort auf der Serverseite cachen. Ich denke das wird aber nicht notwendig sein. Wenn man täglich synchronisiert dauert es nur wenige Sekunden und sollte weniger Last verursachen als ein durchschnittlicher Besucher der RIS-Weboberfläche. Das erste Synchronisieren wird natürlich viel Last verursachen, aber das ist ja auch nur einmal nötig. Clients müssen immer auf die Antwort vom Server warten um über "nextPage" den Link zur nächsten Seite zu bekommen, daher werden sie nicht viele parallele Anfragen machen und ein rate limiting wird nicht notwendig sein.

Über den Spiegelserver wollen wir auch Dumps anbieten. Ich denke es werden sich viele, die OParl kennenlernen wollen, erst mal einen Dump von unserem Server laden, was dann auch die RIS-Server entlastet. Ich denke die Anzahl der OParl-Anwendungen wird sowieso überschaubar bleiben, sodass wir uns wegen Überlastung keine Gedanken machen müssen.

Wenn es beim Synchronisieren zu einem Fehler kommt, sollte ein Client am Besten den Fehler ausgeben, dann kurz warten und das Synchronisieren erneut starten. Sollte es wiederholt zu Fehlern kommen, sollte er abbrechen. Der Client wird ja in der Regel zum nächsten eingeplanten Synchroniserungszeitpunkt erneut gestartet. Ich denke das ist als Fehlerbehandlung erst mal ausreichend.

**Comment by konstin** [comment]
Das Problem ist, dass bestimmte Anfragen in manchen RISen sehr aufwändig. Beispielsweise mussten wir bei München Transparent extra Pausen beim scraping einfügen, weil bestimmten Abfragen im münchner RIS anscheinend so aufwendig gestaltet sind, dass sonst während des scrapen das RIS für normale Besucher nicht mehr erreichbar wäre. Deshalb würde ich folgenden Punkte in die Spezifikation aufnehmen:
 * Implementierer von OParl-Servern sollten vorher testen, ob OParl Abfragen den Server überlasten können, und ggf. Gegenmaßnahmen ergreifen.
 * Clients sollten mit einem "429 Too Many Requests" vernünftig umgehen können.

**Comment by akuckartz** [comment]
Ich stimme dem ersten Absatz von @lu-j zu. http ist in IETF Standards bereits spezifiziert.

**Comment by konstin** [comment]
Das stimmt, aber es lohnt sich trotzdem, darauf hinzuweisen.

**Comment by akuckartz** [comment]
@konstin Mag sein, aber dann geht es hier nicht  um einen _normativen_ Teil der _Spezifikation_ sondern "nur" um (möglicherweise nützliche) Hinweise an Implementierer. Ich fürchte, dass da bei dem einen oder anderen Hersteller eher ein Buch als ein kurzes Kapitel angemessen wäre. Aber auch das müsste jemand schreiben - oder als Referenz angegeben werden...

**Comment by konstin** [comment]
So wie ich das in Anlehnung an #310 verstanden hatte, sollte die Spezifikation dreigeteilt werden: Im ersten Teil stehen interessante Informationen wie Geschichte, Beteiligte und die Weiterentwicklung, die aber für die Implementierung nicht weiter relevant sind. Im zweiten Teil stehen dann Informationen über verwendete Standards, die man sich zwar vor dem implementieren durchlesen sollte, die aber nicht Teil der eigentlichen Spezifikation sind, wie JSON, HTTP/HTTPS und Datenschutz. Der dritten Teil enthält dann die eigentliche Spezifikation. Da man sich zumindest ein Teil der RIS-Hersteller zu wenig Gedanken über mögliche Überlastungen macht, sollte man das in Teil zumindest erwähnen. Im Zweifelsfall wäre ich auch bereit, den Text dazu zu schreiben.

**Comment by konstin** [comment]
@lu-j hat gesagt, dass er sich mit den RIS-Herstellern in Verbindung setzen wird und sie nach im Moment bereits existieren Performance-Problemen, insbesonders beim Abruf durch Suchmaschinen, fragen wird.

Ansonsten erledigt sich das Problem meiner Ansicht von selbst, da durch die Paginierung kaum parallele Request gestellt werden können und hintereinander gestellte Requests kein Problem seien sollten.
