### ISSUE TITLE
Repositories aufräumen

### ISSUE THREAD

**Issue by konstin** [OParl/spec#322]
Im Moment hat gibt es unter https://github.com/OParl 9 verschiedene Repositories.
 - [x] [OParl/website](https://github.com/OParl/website) enthält lediglich eine einzelne html-Seite und etwas css und javascript. Ich bin deshalb dafür, es zu löschen.
 - [ ] Bei [OParl/validator](https://github.com/OParl/validator) und  [OParl/validator-gui](https://github.com/OParl/validator-gui) fehlt ein vernünftiges readme. Außerdem fehlen dort die Änderungen der Spezifikation während des gesamten letzten Jahres.
 - [x] [OParl/schema](https://github.com/OParl/schema) stammt noch aus jsonld-Zeiten und enthält praktisch keine Inhalte. Ich bin dafür, es zu löschen.
 - [ ] [OParl/reference-server](https://github.com/OParl/reference-server) läuft offensichtlich nicht mehr wie im Readme behauptet unter http://refserv.oparl.org/ und hat auch die Entwicklungen des letzten Jahres verpasst.
 - [x] Bei [OParl/spec-website](https://github.com/OParl/spec-website) von @eFrane fehlt ein readme und eine Lizenz.

**Comment by eFrane** [comment]
OParl/website: 

Da habe ich vor einiger Zeit schon in der Readme eine Anmerkung gemacht, dass dieses Repository zwar obsolet ist, aber auf GitHub verbleiben wird. Vielleicht ist der Punkt der Nachvollziehbarkeit da allerdings nicht ganz so wichtig wie bei anderen Repositories. Insofern wäre ich da umstimmbar.

Die Validator-Projekte und OParl/reference-server: 

Soweit ich weiß, ruht deren Entwicklung nach wie vor aus dem selben Grund, aus dem auch die Entwicklung des Referenzservers unter Oparl/php-server nicht weiter geführt wurde: Es macht wenig Sinn, sich an der Spezifikation orientierende Software zu entwickeln, solange sich die Spezifikation innerhalb kurzer Zeit drastisch verändert. Da wir uns jetzt aber auf eine stabile Version zu bewegen, müssen diese Projekte reevaluiert und eventuell wiederbelebt werden.

OParl/schema:

Hierfür gilt meiner Ansicht nach im Grunde gleiches wie im Falle der Website: Wenn niemand was dagegen hat und es die Nachvollziehbarkeit des Projektes nicht behindert, kann es gelöscht werden, ansonsten sollte ein entsprechender Vermerk gemacht werden, dass es sich um ein obsoletes Repository handelt.

OParl/spec-website:

Die fehlenden Angaben dazu liefere ich sobald wie möglich.

**Comment by konstin** [comment]
Alle veralteten Repositories sind als solche markiert und die anderen werden schrittweise aktualisiert.
