### ISSUE TITLE
Renderfehler in der html-Version

### ISSUE THREAD

**Issue by konstin** [OParl/spec#323]
Siehe http://spec.oparl.org/version/master/OParl-1.0-draft.html#entity-paper -> Consultation

**Comment by the-infinity** [comment]
Das dürfte kein Renderfehler sein, sondern Absicht, da die eingebetteten Objekte nur Unterobjekte der betreffenden Hauptobjekte sind. Ich würde die aber trotzdem als Überschrift deklarieren, sinnvollerweise als Subüberschrift - also mit ###.

**Comment by eFrane** [comment]
Ich habe das mal in Überschriften geändert.
