### ISSUE TITLE
Kapitel 2.6 überarbeiten

### ISSUE THREAD

**Issue by eFrane** [OParl/spec#324]
Die Ausgabemöglichkeiten und die Darstellung von Objekten hat sich verändert. Diese Änderungen müssen in das Dokument übertragen werden.

**Comment by eFrane** [comment]
#291

**Comment by the-infinity** [comment]
Hierzu ggf. die Frage: am Ende können wir listformat ja ganz herauswerfen, oder? Diese zusätzlichen Ausgabemöglichkeiten bringen wenig und sind Quelle für verschiedene Probleme. In #291 ist das ja bereits angesprochen worden.

**Comment by the-infinity** [comment]
Vorschlag in https://oparl.org/spezifikation/online-ansicht/#objektlisten-und-paginierung .
