### ISSUE TITLE
Verbindung von Consultations über mehrere Meetings?

### ISSUE THREAD

**Issue by astro** [OParl/spec#337]
Hi

Wir denken seit langem darüber nach OParl für unsere Scraper-Ergebnisse des Dresdner Ratsinfo-Systems zu adaptieren.

Worauf wir ganz scharf sind, ist "Vorlagen" über mehrere Meetings zu verfolgen. So wie die Daten aus dem Ratsinfo-System kommen, ist dies auch problemlos über die [Vorlagen](http://ratsinfo.dresden.de/vo0042.php)-Nummer und [Antrag](http://ratsinfo.dresden.de/ag0041.php)-Nummer möglich.

Wie kann solch eine Verbindung in OParl dargestellt werden?

**Comment by konstin** [comment]
Die Typ `Paper`, mit dem sowohl Vorlagen als auch Anträge abgebildet werden können, hat eine Eigenschaft namens `consultation`, die alle `Consultation`-Objekte enthält, die wiederum eine Eigenschaft `meeting` besitzen. D.h. in der Praxis, dass ihr für jede Behandlung einer Vorlage in einem Meeting ein `Consultation`-Objekt anlegen müsst. Ich hoffe, dass das deine Frage klärt.

PS: Cool das ihr einen Scraper für euer RIS gebaut habt. Gibt es die gescrapten Daten schon (als Rohdaten oder visualisiert) online?

**Comment by astro** [comment]
Ah, unter "Paper" hatte ich mir etwas anderes vorgestellt, aber es trifft genau zu. Vielen Dank!

Die Daten unseres Scrapers: https://ratsinfo.offenesdresden.de/
Mehr Links gibts auf http://offenesdresden.de/ und Scraper anderer Städte anzupassen wurde auch schon mal von irgendwem begonnen...

**Comment by RobTranquillo** [comment]
Wo kann denn die Vorgangsnummer untergebracht werden? Sie passt ja nicht in consultation oder paper gehört aber zu agendaItem. Die Vorgangsnummer verbindet im Zweifel viele Sitzungen verschiedenster Gremien zu einem Themenkomplex. Wie zB. der OpenData-Antrag aktuell in Dresden.

**Comment by konstin** [comment]
Im Moment werden keine Vorgänge oder Vorgangsnummer abgebildet, sondern es können lediglich mit `Paper:relatedPaper`, `Paper:superordinatedPaper` und  `Paper:subordinatedPaper` Beziehungen angegeben werden.

Es wäre möglich, die Vorgangsnummer zu `Paper` oder zu `Consultation` hinzu zu fügen. Um aber tatsächlich Vorgänge abbilden zu können, müsste man ein Vorgangs-Obkjekt hinzufügen, in dem man dann alle Eigenschaften des Vorgangs speichern kann.

**Comment by eFrane** [comment]
Eine alternative Lösung mit den Mitteln von OParl 1.0 wäre, eine [Herstellerspezifische Erweiterung](http://spec.oparl.org/spezifikation#herstellerspezifische-erweiterungen) an `Paper` oder `Consultation` anzufügen. 

*Randnotiz: Bitte nach Möglichkeit keine alten Issues für neue Fragen verwenden.*

**Comment by akuckartz** [comment]
@RobTranquillo Wird die Vorgangsnummer zusätzlich zu den zur Verfügung gestellten Ausdrucksmitteln benötigt? Zu welchen Zwecken? Was gehört zu einem Vorgang? Was unterschiedet Vorgangsnummern von Aktenzeichen von Drucksache? Beispiele?

**Comment by RobTranquillo** [comment]
Mich verwirrte der Umstand, dass eine VOrlagennummer gleichzeitig eine file und ein Ansammlung von Sitzungen sein kann. Astro hats mir jetzt so erklärt, dass die gleichnamige Vorlagendatei die main file und der Rest auxilary files sind und die betreffenden Sitzungen die consultations unter paper. 

Und sorry für das thread-napping.

**Comment by astro** [comment]
Diese Vorgangs-/Anfragenkennung habe ich bei uns in `Paper.shortName` bzw. noch besser `Paper.reference` untergebracht. Aus der Spec zu `reference`:
> Kennung bzw. Akten­zei­chen der Druck­sa­che, mit der sie in der parla­men­ta­ri­schen Arbeit eindeu­tig refe­ren­ziert werden kann.
