### ISSUE TITLE
Bezeichnung: Subobjekte oder eingebettete Objekte

### ISSUE THREAD

**Issue by konstin** [OParl/spec#338]
Momentan wird an einigen Stellen von Subobjekten und an anderen von eingebetten Objekten gesprochen. Die Bezeichnung sollte einheitlich auf Subobjekte geändert werden, da die Objekte nicht immer eingbettet sein müssen.

**Comment by the-infinity** [comment]
Fixed mit https://github.com/OParl/spec/commit/c6736313c6bdb4431fa8f98a3c6109d9454bde9f
