### ISSUE TITLE
Die Links im Kapitel zu Datum und Zeit fehlerhaft

### ISSUE THREAD

**Issue by konstin** [OParl/spec#341]
Die im Kapitel zu Datum und Zeit angegebenen links, http://www.w3.org/TR/xmls­chema-2/#date und http://www.w3.org/TR/xmls­chema-2/#dateTime, sind in der html-Fassung keine links und außerdem existiert die verlinkten Dokumente nicht.

**Comment by akuckartz** [comment]
https://www.w3.org/TR/xmlschema-2/#date und https://www.w3.org/TR/xmlschema-2/#dateTime können dereferenziert werden.

**Comment by konstin** [comment]
Größtenteils gelöst in b143ae62152762af719791441cc8981b377cc448
