### ISSUE TITLE
Listen und Paginierung - was schränkt `limit` ein?

### ISSUE THREAD

**Issue by robbi5** [OParl/spec#344]
In 2.5.5 Filter wird definiert, dass ein Client mit dem `limit`-Parameter die Länge einer Liste begrenzen kann.
In 2.5.4 Paginierung steht:

>`totalElements`: Gibt die Gesamtanzahl der Objekte in der Liste an. Diese Zahl kann sich unter Umständen bis zum Aufruf der nächsten Listenseiten ändern.
>
>`elementsPerPage`: Gibt die Anzahl der Objekte pro Listenseite an. Dieser Wert muss auf allen Listenseiten bis auf die letzte gleich sein.

Welches der beiden wird nun von `limit` eingeschränkt? Die Gesamtanzahl der Objekte oder nur die Anzahl pro Seite?

**Comment by eFrane** [comment]
Es wird - wie bei Paginierungs-limit üblich - die Anzahl der Elemente pro Seite limitiert.

**Comment by robbi5** [comment]
Ah, danke :)

Dann macht es vielleicht Sinn, `limit` nach oben in 2.5.4 Paginierung zu verschieben - so sind dort alle Dinge, die die Paginierung betreffen und bei Filter alle Dinge, die die Gesamtanzahl der Objekte betreffen.

**Comment by eFrane** [comment]
:+1:

**Comment by konstin** [comment]
Ich habe `limit` in `elementsPerPage` umbenannt, womit die Bedeuting eindeutig sein sollte. Der Filter `elementsPerPage` sollte aber im "Filter"-Kapitel bleiben.
