### ISSUE TITLE
Inconsistencies between type tables and example code

### ISSUE THREAD

**Issue by torfsen** [OParl/spec#350]
There are multiple places in the specification where the information in a type's field table is inconsistent with the corresponding example code:

- [`Organization.location`](https://oparl.org/spezifikation/online-ansicht/#entity-organization) has a defined type of `object (Location)` but the value in the example is of type `url (Location)`
- [`Meeting.location`](https://oparl.org/spezifikation/online-ansicht/#entity-meeting) has a defined type of `object (Location)` but the value in the example is of type `url (Location)`
- [`Consultation.organization`](https://oparl.org/spezifikation/online-ansicht/#consultation) has a defined type of `array of url (Organization)` but the value in the example is of type `url (Organization)`

**Comment by eFrane** [comment]
It might be valuable to replace the static, non-checked examples by examples from one an existing OParl endpoint. As there are currently Politik bei Uns, Muenchen Transparent, and the OParl Dev-Site reference implementation, I would vote to extract data from the latter one as that is guaranteed to be random and more importantly without any possibility copyright claims or unauthorized reuse.

**Comment by akuckartz** [comment]
If I understand this correctly than this is a contradiction within the specification.

**Comment by konstin** [comment]
It is rather a bug as it was only forgotten to update the examples. This will be fixed soon.

**Comment by konstin** [comment]
Closing in favor of #356.

I've written a script to automatically find all those errors. This will prevent further errors of that kind from happen in the future.

**Comment by konstin** [comment]
Fixed in 351cd6274b99960b9b22afd3997f90d79b6cd104
