### ISSUE TITLE
Paper.underDirectionof naming

### ISSUE THREAD

**Issue by grindhold** [OParl/spec#352]
the Paper object specifies an attribute called "underDirectionof". Shouldn't it rather be "underDirectionOf"? There is proper snakeCase everywhere else.

**Comment by eFrane** [comment]
That's very much a misnaming in the spec, yes.

**Comment by grindhold** [comment]
found in plaintext spec  OParl-1.0.txt from the website.
line 2323

**Comment by eFrane** [comment]
This is already fixed in upstream. Please compare to https://dev.oparl.org/spezifikation#entity-paper.
