### ISSUE TITLE
Build-Anleitung für nicht Experten

### ISSUE THREAD

**Issue by konstin** [OParl/spec#361]
Im Readme fehlt eine Schritt für Schritt Anleitung für das Bauen der Spezifikation. Für Ubuntu und Debian solten die Pakete angegeben werden. Außerdem sollte untersucht werden, ob und wenn ja wie das Bauen auf Windows funktioniert.

**Comment by eFrane** [comment]
Würde umformulieren in irgendwas wie Build-Anleitung für Menschen die gerne mitmachen wollen. Weil für alle anderen stellen wir ja Downloads etc bereit.

**Comment by konstin** [comment]
So war das auch gedacht, mir fällt bloß keine bessere Formulierung ein.

**Comment by eFrane** [comment]
Diese Anleitung findet sich unter [building.md](https://github.com/OParl/spec/blob/master/building.md)
