### ISSUE TITLE
Person -> Location muss ein internes Objekt sein, keine URL

### ISSUE THREAD

**Issue by the-infinity** [OParl/spec#373]
... das widerspricht der Systematik, alles intern auszugeben.

**Comment by sterni24** [comment]
und sollte auch unter 3.1 in der Location-Auflistung erwähnt werden.

**Comment by the-infinity** [comment]
Beides gefixt in https://github.com/OParl/spec/commit/da25779b67a71daeaacdcd9c6251dbcdd76707e9 .
