### ISSUE TITLE
Rückreferenz Organization -> Consultation fehlt

### ISSUE THREAD

**Issue by the-infinity** [OParl/spec#376]
Consultation->organization bzw Consultatin->meeting gibts, andersrum nicht.

**Comment by sterni24** [comment]
Beim Recherchieren zu diesem Thema ist mir folgendes aufgefallen:
- dies steht in AgendaItem
![image](https://user-images.githubusercontent.com/4255890/32245386-e41d2b82-be7b-11e7-8d0a-03a957303495.png)
- und dies unter Consultation
![image](https://user-images.githubusercontent.com/4255890/32245298-9bacee32-be7b-11e7-8f0b-297ad570cffe.png)

Müsste das nicht gleich lauten? Hier würde ich die Inhaltsbeschreibung von AgendaItem bevorzugen. 

In der Tat könnte eine Beziehung Organization > Consultation Sinn ergeben, zumal es Consultation ohne Beziehung zu AgendaItem bzw. Meeting geben kann. Ein Rückverweis müsste auch für Meeting -> Consultation definiert werden. Siehe #381.

**Comment by akuckartz** [comment]
Bei diesen Rückverweisen handelt es sich um redundante Informationen, korrekt?

**Comment by sterni24** [comment]
(Rück-)Verweise von Organization -> Consultation schließen die Verweise von Meeting -> Consultation (bisher nicht vorhanden) und AgendaItem -> Consultation mit ein.
