### ISSUE TITLE
Es können aktuell nicht mehrere Paper an einem AgendaItem beraten werden

### ISSUE THREAD

**Issue by the-infinity** [OParl/spec#377]
... da AgendaItem -> Consultation und Consultation -> Paper jeweils 1:1 Relationships sind.

**Comment by konstin** [comment]
Sind Fälle bekannt, in denen mehrere Paper zu einem AgendaItem gehören?

**Comment by akuckartz** [comment]
Siehe auch die Diskussion in #244

**Comment by the-infinity** [comment]
Stimmt, ist offensichtlich ein Duplikat. Ist mir nur beim Template-Bauen aufgefallen. :)

**Comment by akuckartz** [comment]
Wobei allerdings das Ergebnis in #244 in Widerspruch zu der Diskussion dort stand und steht.

**Comment by konstin** [comment]
Das Ergebnis war, dass eine 1:1 Beziehung für alle beteiligten Server-Anbieter ausreicht. Das ist in OParl 1.0 umgesetzt.

Sollte sich zeigen, dass diese Annahme nicht (mehr) korrekt ist, wird eine spätere OParl-Version dementsprechend angepasst. Es ist vorgesehen, diese Annahme in der Zukunft im Detail zu überprüfen.
