### ISSUE TITLE
Personenstruktur

### ISSUE THREAD

**Issue by mrtopf** [OParl/spec#38]
Moin!

Nur als Hinweis, was ALLRIS alles so ausspuckt, hier das Beispiel für unseren OB:

        <element>
            <kplfdnr>57</kplfdnr>
            <kppartei>CDU</kppartei>
            <kpgdat>2441079</kpgdat>
            <kpsdat>0</kpsdat>
            <aktiv>1</aktiv>
            <antext1>Oberb&#252;rgermeister</antext1>
            <antext3>Sehr geehrter Herr Oberb&#252;rgerm</antext3>
            <adname>Philipp</adname>
            <advname>Marcel</advname>
            <adtit/>
            <adename/>
            <adstr>Hasslerstra&#223;e</adstr>
            <adhnr>22-24</adhnr>
            <adplz>52066</adplz>
            <adort>Aachen</adort>
            <adoteil/>
            <ademail>oberb&#252;rgermeister@mail.aachen.de</ademail>
            <ademail2/>
            <adwww1>www.aachen.de</adwww1>
            <adwww2/>
            <adtel>0241-4327200</adtel>
            <adtel2/>
            <adtel3>432-7200</adtel3>
            <adtel4/>
            <adtel5/>
            <adtel6>176171</adtel6>
            <adfax>0241-4328008</adfax>
            <adfax2/>
            <link_kp>kp020.asp?KPLFDNR=57options=8</link_kp>
        </element>

Die Frage ist wahrscheinlich, ob man alle möglichen Felder (wie 6 Telefonnummern) optional aufnimmt oder man sich beschränkt. Generell wäre ich aber schon dafür, alle Informationen des Systems auch herauszugeben. Dazu müsste man aber wahrscheinlich schauen, was andere Systeme noch für Felder haben (vielleicht gibt ja auch eines noch pro Telefonnummer ne Beschreibung an). 

kppartei muss übrigens dabei keine Partei sein, sondern kann auch Verein, Polizeipräsidium etc. sein.

**Comment by konstin** [comment]
Zur momentanen Definition von Person würde ich die folgenden Veränderungen Vorschlagen:
 - `familyName` und `givenName` werden von optional auf empfohlen gesetzt, da diese u.a. für das Sortieren von Personen sehr wichtig sind.
 - `title`sollte entfernt werden, da akademische Titel sehr unterschiedlich notiert werden können und in der Praxis kaum Bedarf für diese Information bestehen dürfte.
 - `email` und `phone` werden als arrays definiert.
 - Eine neue Eigenschaft für Profile in Sozialen Netzwerken, Abgeordnetenwatch, Homepage u.ä. wird eingeführt.
 - Eine optionale Eigenschaft `description` wird eingeführt, die einen (kurzen) Text zur Person enthält. Dazu wird eine Eigenschaft `descriptionSource` angelegt, die die Quelle des Textes angibt und bei Angabe von `description` zwingend ist.
 -  `formOfAddress` und `status`  sollten überarbeitet werden:
   - Es wird leider nicht klar, warum sowohl die männliche als auch die weibliche Form angegeben werden soll. Denn wenn ein client daraus eine sinnvolle Anrede bauen möchte, muss er erst erst `gender` abfragen und dann aus dem String von `formOfAddress` bzw. `status` den richtigen Teil extrahieren, wobei er noch den Sonderfall von nur einer Form abfangen muss.
   - Außerdem wird bei `formOfAddress` die Reihenfolge von männlicher und weiblicher Form nicht festgelegt nicht festgelegt.
   - `status` wird im Text dazu als array angegeben, im Beispiel handelt es sich aber um einen String

**Comment by akuckartz** [comment]
@konstin Der Wertebereich für`formOfAddress`bestand ursprünglich aus `skos:Concept`-Objekten. Die Darstellung "männlich | weiblich" macht ohne SKOS in der Tat wenig Sinn.

**Comment by eFrane** [comment]
Im großen und ganzen finde ich diese Überarbeitungen gut, nur würde ich `title` nicht entfernen, da die Angabe des akademischen Grades in offiziellen/öffentlichen Bereichen durchaus nicht unüblich und hin- und wieder sogar von Beteiligten erwünscht ist. Sicher besteht, wie @konstin schon bemerkt dafür in der Verwendungspraxis von OParl nicht viel Sinn – zumindest kann ich den auch (noch) nicht sehen – nichts desto trotz würde ich die Möglichkeit der individuellen Angabe als String belassen. 

Kleine Randnotiz: Da es so viele unterschiedliche Titel und Abschlüsse gibt, kann die Angabe in diesem Feld gar nicht sinnvoll rationalisiert werden, es sei denn, wir sammeln die üblichen Formulierungen auf der ganzen Welt, was, mal wieder, den Fokus dieser Spezifikation übersteigt.

**Comment by konstin** [comment]
Gibt es für `title` Anwendungsfälle? Schließlich gibt es in der Anrede ja schon die relevanten Titel.

**Comment by the-infinity** [comment]
Closed in https://github.com/OParl/spec/commit/685bbf545b64bf9c9951d93173368aef53ed26b6 weil schadet nicht.
