### ISSUE TITLE
AgendaItem und Consultation zusammenführen

### ISSUE THREAD

**Issue by konstin** [OParl/spec#381]
Bei AgendaItem und Consultation handelt es sich im Grunde um ein Objekt, dass auf zwei aufgeteilt wurde. Deshalb sollten die beiden in OParl 2.0 in einen einzigen AgendaItem Typ zusammengelegt werden.

**Comment by akuckartz** [comment]
Ich rege an, erst einmal zu prüfen inwieweit dies tatsächlich zutrifft. Möglicherweise trifft es zu, aber nur aufgrund von bisherigen Festlegungen zu Kardinalitäten (siehe #244 und #377).

**Comment by konstin** [comment]
Das war auch der Grund für das bisherige Design. Ich habe nun aber in der Arbeit mit realen Daten nur Fälle gesehen, in denen AgendaItem und Consultation tatsächlich zwei Teile desselben Objektes waren.

**Comment by eFrane** [comment]
Wenngleich sich in den bisher vorhandenen Daten die Trennung zwischen Consultation und AgendaItem als wenig sinnvoll erweist ist es wahrscheinlich in der Tat nicht angebracht, anhand der wenigen bisher vorhandenen Daten zu schlussfolgern, dass die bisherige Trennung aufgelöst werden muss.

Wir sollten uns eher auf die verbleibenden Probleme für ein Release von Version 1.1 fokussieren und dann mit mehr und vielfältigeren Realdaten Analysen vornehmen, ob u.a. diese Änderung sinnvoll ist.

Für mich spricht momentan auch so einiges für eine Zusammenlegung, da der Hauptzweck der Consultation bisher am Ende des Tages ein Boolean von "dieser Tagesordnungspunkt wurde besprochen" ist. Das ist nicht besonders hilfreich. Möglich ist aber, dass entweder bisherige Realdaten oder auf dem OParl Datenmodell aufbauende RIS Consultations als Folge von AgendaItems nutzen (unter Umständen mit Hilfe von Vendorattributen) und damit dieser Entity wieder mehr Sinn geben.

Whatever, :+1: für das Vertagen des Problems bis wir oder/und zukünftige Kontributoren es tatsächlich beurteilen können.

**Comment by sterni24** [comment]
Argumente gegen eine Zusammenführung:
- es gibt Fälle, in denen Vorlagen ohne Termin als Mitteilungsvorlage veröffentlicht werden
- es gibt Fälle, in denen terminierte Vorlagen bereits vor Aufstellung einer Tagesordnung veröffentlicht werden
- es gibt Vorlagen mit Terminen als Beratungsfolge, die nur teilweise mit einer Tagesordnung verknüpft sind.

**Comment by konstin** [comment]
Ich versuche gerade die Beziehung der Beispiele zu den OParl-Objekten nachzuvollziehen. 

> es gibt Fälle, in denen Vorlagen ohne Termin als Mitteilungsvorlage veröffentlicht werden

Heißt das, dass eine Cosultation zu einem Paper veröffentlicht wird, in der es dann heißt, dass die Vorlage nur eine Mitteilung ist?

> es gibt Fälle, in denen terminierte Vorlagen bereits vor Aufstellung einer Tagesordnung veröffentlicht werden

Wird die dann zuerst eine Consultation erstellt, zu der dann wiederum später ein AgendaItem erstellt wird? Und wenn ja, welchen Vorteil hat es, die Consultation zuerst zu veröffentlichen? Lässt sich die Vorlage allein nicht trotzdem anzeigen?

> es gibt Vorlagen mit Terminen als Beratungsfolge, die nur teilweise mit einer Tagesordnung verknüpft sind.

Diesen Punkt verstehe ich leider garnicht. Wie unterscheidet sich eine Beratungsfolge von einer Tagesordnung?

**Comment by bschalitz** [comment]
Das Objekt Consultation  ist im RIS Sprachgebrauch ein Beratungsfolgeschritt und das AgendItem der Tagensordnungspunkt. 

Mit der Beratungsfolge legt die Verwaltung fest, in welchen Gremien die Vorlage (Paper) beraten werden soll. Es gibt je einen Beratungsfolgeschritt je Gremium, dass zu dieser Sache tagen soll.
Mitteilungsvorlagen haben keine Beratungsfolge. 

Sonderfall: Eine Vorlage wird in einer Sitzung nicht abschließend beraten sondern vertagt, dann kommt die Vorlage in einer nächsten Sitzung wieder auf die Tagesordnung. Das kann auch mehrfach erfolgen.
--> Eine Vorlage  verweißt mit einem Beratungsfolgeschritt auf zwei Tagensordnungspunkte.

Sonderfall: in einer gemeinsamen Sitzung wird eine Vorlage von zwei Gremien (Beratungsfolgeschritten) beraten.
--> Eine Vorlage verweißt mit zwei Beratungsfolgeschritten auf einen Tagesordnungspunkt.

Wird die Vorlage nur einmal von einem Gremium behandelt. Sieht es wie eine 1:1 Beziehung aus. Aber selbst dann entwickelt sich das ganze zeitlich. An der Vorlage ist eventuell schon vermerkt, wo die Vorlage noch behandelt werden soll, ohne das diese Sitzungen (in der Zukunft) schon vollständig geplant oder eingeladen und ihre Tagesordnungen veröffentlich wurden.

**Comment by sterni24** [comment]
@konstin 
>es gibt Fälle, in denen terminierte Vorlagen bereits vor Aufstellung einer Tagesordnung veröffentlicht werden
>>Wird die dann zuerst eine Consultation erstellt, zu der dann wiederum später ein AgendaItem erstellt wird? Und wenn ja, welchen Vorteil hat es, die Consultation zuerst zu veröffentlichen? Lässt sich die Vorlage allein nicht trotzdem anzeigen?

Ja, und das liegt an der zeitlichen Abfolge einer Sitzungsvorbereitung. Hierzu Fälle aus der Praxis:
- Eine Vorlage wird mit einem oder mehreren Beratungsterminen (=Beratungsfolge) versehen. In diesem Zustand kann sie schon frühzeitig veröffentlicht werden. Hierzu gibt es also Cosultations, jedoch keine AgendatItems. 
- Eine Tischvorlage mit einem Termin wird unmittelbar vor der Sitzung veröffentlicht. Hier gibt es ebenfalls eine Consultation, jedoch kein AgendaItem.
>es gibt Vorlagen mit Terminen als Beratungsfolge, die nur teilweise mit einer Tagesordnung verknüpft sind.
>>Diesen Punkt verstehe ich leider gar nicht. Wie unterscheidet sich eine Beratungsfolge von einer Tagesordnung?

Beispiel: Für eine Vorlage mit mehreren Beratungsterminen wird für den 1. Termin eine Tagesordnung erstellt. Damit ist ein AgendaItem vorhanden. Für die weiteren Termine werden die Tagesordnungen erst später erzeugt, weil die Ladungsfristen noch nicht erreicht sind. Die noch nicht zugeordneten Termine (Consultation) werden der Vollständigkeit halber beim Paper angezeigt.

Ergänzend zu @bschalitz:
>Sonderfall: Eine Vorlage wird in einer Sitzung nicht abschließend beraten sondern vertagt, dann kommt die Vorlage in einer nächsten Sitzung wieder auf die Tagesordnung. Das kann auch mehrfach erfolgen.
--> Eine Vorlage verweist mit einem Beratungsfolgeschritt auf zwei Tagesordnungspunkte.

Bei Vertagungen oder auch Rückverweise in Fachausschüsse und erneute Beratung wird in unserem System jeweils ein weiterer Termin (Consulation) angelegt. 

>Sonderfall: in einer gemeinsamen Sitzung wird eine Vorlage von zwei Gremien (Beratungsfolgeschritten) beraten.
--> Eine Vorlage verweist mit zwei Beratungsfolgeschritten auf einen Tagesordnungspunkt.

Bei gemeinsamen Sitzungen wird unterschiedlich verfahren. Es gibt entweder ein (gemeinsames) Meeting oder zwei Meetings zu dem selben Zeitpunkt am selben Ort. Dies entscheidet auch darüber, ob in der Vorlage ein oder zwei Consultations und damit auch ein oder zwei AgendaItems angelegt werden.

Hinweis: Die Sonderfälle von @bschalitz ließen sich in OParl nicht abbilden, da es sich zwischen Consultation und AgendaItem um eine 1:1 Beziehung handelt.

**Lange Rede, kurzer Sinn: Wir sollten alles so belassen, wie es in OParl 1.0 spezifiziert ist.**

**Comment by konstin** [comment]
Vielen Dank für die ausführlichen Antworten! 

Auf Grund dieser Fälle werden wir die beiden Objekte weiterhin getrennt lassen.
