### ISSUE TITLE
OParl 1.1

### ISSUE THREAD

**Issue by sterni24** [OParl/spec#391]
Wie ist der aktuelle Stand?

**Comment by konstin** [comment]
Die Spezifikation ist inhaltlich fertig. Wir werden in den nächsten Tagen noch einen finalen release candidate mit einer (noch zu bestimmenden) Deadline für Feedback veröffentlichen, nach der wir die finale Version 1.1 veröffentlicht wird.

**Comment by eFrane** [comment]
Mit

> Die Spezifikation ist inhaltlich fertig

meinte @konstin vor allem anderen, dass wir keine weiteren Issues für 1.1 bearbeiten werden, es sei denn, in der im Laufe der kommenden Woche beginnenden letzten Pre-Release Feedbackrunde von entsteht noch mal dringender Handlungsbedarf. Allerdings werden auch mit Blick auf dir vorangegangen Release Candidates und natürlich auch aus Semver-Perspektive sicher keine größeren Änderungen mehr vorgenommen.

Da der weitere Entwicklungsverlauf nach Version 1.1 noch nicht im Detail geplant ist (noch eine Minorversion für 1.x, Planungsbeginn 2.x, …?) gibt es zur Zeit ein paar Issues, die nicht konkret verplant sind.

**Comment by akuckartz** [comment]
Ich sehe nicht, was einer Lösung von #372 im Wege stehen könnte. Immerhin ist das Issue mit dem Label "Hohe Priorität" versehen.

**Comment by konstin** [comment]
Wir haben einen offiziellen finalen Entwurf: https://oparl.org/2018/01/29/entwurf-fuer-oparl-1-1/ und https://github.com/OParl/spec/releases/tag/v1.1-rc-3.

Sollten keine unerwarteten größeren Probleme auftauchen wir OParl 1.1 am 12. Februar veröffentlicht; Bis dahin kann gerne noch Feedback eingebracht.
