### ISSUE TITLE
OParl 1.1 finaler Entwurf - Anpassungen

### ISSUE THREAD

**Issue by sterni24** [OParl/spec#392]
# Spezifikation OParl 1.1
## 1.8. Autoren
Ich würde hier eine Trennung vorschlagen:
> Folgende Personen haben an OParl 1.0 mitgewirkt:
...
> Folgende Personen haben an OParl 1.1 mitgewirkt:
...
## 2.8 Gelöschte Objekte
Der gesamte Absatz sollte überarbeitet werden, weil in OParl 1.0 die Voraussetzung zur Löschung von Objekten nicht gegeben war. Ich würde hier noch auf folgende Dinge hinweisen bzw. unter 4. ein eigenes Kapitel **Update-Mechanismus** einfügen.
> Grundsätzlich muss unterschieden werden, ob eine OParl-Anfrage der einfachen Ausgabe in einem Drittsystem dient oder ein externer Datenbestand, wie bei der OKF, aufgebaut werden soll.
> In der einfachen Ausgabe werden nur aktuelle Daten ausgegeben. Gelöschte Daten werden hierbei unterdrückt. 
> Bei der Pflege eines externen Datenbestandes können die Daten mit Hilfe der Filter ***created_since*** bzw. ***modified_since*** abgerufen werden. Bei der ***modified_since*** wird die **created**-Eigenschaft ausgegeben, falls kein **modified**-Wert vorhanden ist. Gelöschte Datensätze enthalten die zusätzliche Eigenschaft ***deleted: True***. Um einen konsistenten Datenbestand sicherzustellen, sind zwingend alle Objektlisten mit denselben Filterangaben abzufragen und zu verarbeiten. Die Ausgabe von internen Objektlisten kann hierbei entfallen.
## 3.6 LegislativTerm, 3.9 Membership, 3.11 AgendaItem, 3.13 Consultation
In diesen Kapiteln fehlen die Angaben **created**, **modified**, **deleted**.
## 4.1.1 OParl 1.1
Bitte den 2. Absatz inhaltlich noch einmal durcharbeiten. Hier sind unvollendete Halbsätze und Rechtschreibfehler enthalten. Ebenso müsste es heißen, 
> dass created, modified und deleted bei allen Objekten existieren
# Json-Schema
Die Objekte AgendaItem, Consultation, LegislativTerm, Membership sind unvollständig. Hier fehlen ebenfalls die Angaben **created**, **modified** und **deleted**.

**Comment by konstin** [comment]
Danke für die guten Hinweise! Ich kümmere mich am Donnerstag darum.

**Comment by konstin** [comment]
Alle Punkte bis auf die Aufteilung des Autoren-Kapitels sind behoben. Das Kapitel ist aber auch ohne Trennung korrekt und daher nicht kritisch für 1.1, deshalb bleibt dieser Punkt offen für weitere Diskussion.

**Comment by sterni24** [comment]
Das Autoren-Kapitel ist zwar nicht kritisch, jedoch ohne Trennung nicht korrekt. Bitte führen Sie die Änderung entsprechend durch.

Wo finde ich die aktuelle, angepasste Spezifikation?

**Comment by sterni24** [comment]
>Das Autoren-Kapitel ist zwar nicht kritisch, jedoch ohne Trennung nicht korrekt. Bitte führen Sie die Änderung entsprechend durch.
>Wo finde ich die aktuelle, angepasste Spezifikation?

PS.: für die Code-Hygiene in den angepassten Schemen: **web** vor **deleted**

**Comment by sterni24** [comment]
@the-infinity Die in #393 verlinkte Spezifikation ist vom 29.01.2018 und leider nicht aktuell. Die Punkte, die unter https://github.com/OParl/spec/commit/e35cbe9c9aa43015d22d6d00de1c6c72aface925 von @konstin behoben wurden, sind nicht vollständig. Die Schemen .json wurden zwar angepasst, die Objektbeschreibungen im Kapitel 3 nicht. 

**Ich bitte an dieser Stelle noch einmal dringend darum, den Umgang mit dem Update-Mechanismus konkret und ausführlich zu beschreiben, wie oben unter 2.8 in einer ersten Formulierung angeregt.**

Die Annahme von @konstin, 
>Da sich nun jedoch herausgestellt hat, dass `created` und `modified` bei allen Objekten existieren, können auch für alle Objekte Listen angeboten werden.

in Kombination mit `deleted` ist noch von keinem weiteren RIS-Hersteller weder bestätigt noch dementiert worden. Mal schauen, was da noch kommt!

Ich bitte auch darum, jeweils das Datum der **letzten Aktualisierung** auf dem Deckblatt auszugeben und nicht das Datum der geplanten Veröffentlichung *12. Februar 2018*.

**Comment by akuckartz** [comment]
Mehrere Ausführungen in dem Abschnitt "Gelöschte Objekte" sind nicht eindeutig, z.B.:
* Was ist ein "gültiges" Objekt? 
* Was bedeutet "einfach" gelöscht?
* Zu dem Attribut "deleted" steht dort (und in dem ganzen Dokument) nur "Wenn ein Objekt gelöscht wird, muss das Objekt das zusätzliche Attribut deleted: true bekommen". Was ist mit anderen Attributen als "modified", "id", "type", "created": Dürfen die alle entfernt werden oder sind sie möglicherweise weiterhin obligatorisch?
* Die Formulierung "Wenn ein Objekt gelöscht wird ... muss das Objekt das zusätzliche Attribut ... bekommen" enthält einen Widerspruch: Ist das Objekt danach gelöscht oder existiert es noch?
* Weder in dem Abschnitt noch im Rest des Dokuments taucht das Wort "Update" auf. Das ist nach der Diskussion in #375 (und auch dem Ergebnis #380) etwas überraschend.

**Comment by konstin** [comment]
@akuckartz Wenn du das Kapitel zur Objektlöschung diskutieren möchtest, dann eröffne dafür bitte ein neues Ticket und kapere nicht das Ticket von jemand anderem.

**Comment by akuckartz** [comment]
@konstin Der wesentliche offene Punkt in diesem Issue von @sterni24 betrifft laut https://github.com/OParl/spec/issues/392#issuecomment-362848090 das Kapitel 2.8 Gelöschte Objekte und den Update-Mechanismus. Aber da es so gewünscht ist: #395

**Comment by konstin** [comment]
Zwischenstand: Es fehlt OParl/dev-website/issues/72 und der Paragraph zum Update-Mechanismus.

**Comment by sterni24** [comment]
Wann können wir mit der Fertigstellung der vollständigen Spezifikation (inkl. Änderungen im Kapitel 1.8) rechnen?

**Comment by konstin** [comment]
Da ich noch mindestens zwei Wochen komplett ausgelastet bin muss OParl und Release leider noch etwas warten. Ein Datum gibt es noch nicht, da wir für das Kapitel zum Updatemechanismus sicher noch Feedbackrunden brauchen werden.

**Comment by konstin** [comment]
OParl/dev-website#72 ist gelöst und in 44e14fda21b4e475f92fc3ce6a2b52be714e0d44 habe ich eine Erklärung für den Update-Mechanismus und die gelöschten Objekte geschrieben. Damit wären für mich alle großen Punkte gelöst.

**Comment by konstin** [comment]
Ich habe mit den Änderungen einen 4. Release Candidate erstellt: https://github.com/OParl/spec/releases/tag/v1.1-rc-4
