### ISSUE TITLE
"Entwurf für OParl 1.1" - Wo?

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#393]
Dem Text "Entwurf für OParl 1.1" (https://oparl.org/2018/01/29/entwurf-fuer-oparl-1-1/) vom 29.01.2018 ist nicht zu entnehmen, unter welcher URL dieser Entwurf zugänglich ist. Im Abschnitt "Aktuelle Entwicklungsversion" auf der Seite https://github.com/OParl/spec wird auf Dokumente mit Versionsangabe 1.0 verwiesen.

**Comment by the-infinity** [comment]
Der Entwurf ist im Artikel verlinkt: https://github.com/OParl/spec/releases/download/v1.1-rc-3/OParl-v1.1-rc-3-de.zip . Weitere Fassungen sind hier auf Github unter Releases zu finden: https://github.com/OParl/spec/releases .
Ich hab die Links aber mal deutlicher eingeblaut, damit die besser zu finden sind.

**Comment by akuckartz** [comment]
Danke!
