### ISSUE TITLE
HTTP-Statuscode für gelöschte Objekte

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#394]
Im Abschnitt "Gelöschte Objekte" steht:
> Als HTTP-Statuscode **muss** weiterhin 200 verwendet werden.

Dies steht nach meiner Einschätzung in Widerspruch zu RFC 7231. Siehe https://github.com/OParl/spec/issues/379#issuecomment-341881290

**Comment by konstin** [comment]
Ein Statuscode wie 410 ist dann korrekt, wenn der Server unter der url keine Daten mehr ausliefern kann. Das würde aber der Spezifikation widersprechen, in der festgelegt ist, dass der Server auch bei gelöschten Objekten ein gültiges Objekt ausliefern muss.

Weiterhin handelt es sich bei gelöschten Objekten nicht um einen Fehler ("Client Error 4xx"), sondern um einen wichtigen Teil des Update-Mechanismus. 200 hat in der Praxis auch den Vorteil, dass man mit http-Bibliotheken einen Fehler leicht von einem gelöschten Objekt unterscheiden kann.

**Comment by akuckartz** [comment]
Der HTTP-Status 410 impliziert nicht, das keine Daten ausgegeben werden können.

**Comment by konstin** [comment]
>Der HTTP-Status 410 impliziert (ebenso wie die anderen 4xx-Codes) nicht, das keine Daten ausgegeben werden können, [...]

Das ist bekannt. 

Weiterhin heißt es in Kapitel 6.5.:

>  The 4xx (Client Error) class of status code indicates that the client seems to have erred.

Bei gelöschten liegt kein Fehler vor, weder auf Client- noch auf Serverseite.

Sowie in Kapitel 6.5.9.

>  It is not necessary to mark all permanently unavailable resources as "gone" or to keep the mark for any length of time -- that is left to the discretion of the server owner.

OParl verlangt, dass gelöschte Objekte markiert und unbeschränkt erhalten verbleiben.

**Comment by akuckartz** [comment]
> Client seems to have erred

ist *nicht* gleichbedeutend damit, dass der Client einen "Fehler" gemacht hat (oder der Server). Deutsche Übersetzung laut Google: "scheint sich geirrt zu haben"

So bedeutet ja 404 auch nur, dass das Objekt nicht oder nicht mehr existiert. Und 410 bedeutet, dass es einmal existiert hat und nun nicht _mehr_ existiert.

> OParl verlangt, dass gelöschte Objekte markiert und unbeschränkt erhalten verbleiben.

Für solche Fälle ist 410 gedacht. Das Zitat aus 6.5.9 besagt nur, dass HTTP keine - jedenfalls keine _unbeschränkte_ - Markierung fordert. Wenn es keine Markierung gibt (oder keine mehr gibt) dann ist 404 die durch HTTP vorgesehene Antwort.
