### ISSUE TITLE
Anmeldemaske für Zugriff auf nicht-öffentliche Informationen

### ISSUE THREAD

**Issue by Beloli** [OParl/spec#404]
Über [das Ratsinfomanagement von SD.NET](https://gronau.ratsinfomanagement.net/) wird es Personen mit Zugangsdaten ermöglicht, nicht-öffentliche Informationen zu politischen Themen einzusehen. Voraussetzung dafür ist natürlich eine entsprechende Rechtevergabe, die über das Programm SD.NET verwaltet wird.

Die Schnittstelle spiegelt aktuell nur Informationen wieder, die in SD.NET mit einer öffentlichen Kennzeichnung versehen werden. Wünschenswert wäre, dass auch die Schnittstelle eine Anmeldemaske und somit einen Zugang zu den nicht-öffentlichen Informationen gewährt.

Wäre soetwas umsetzbar? Falls dies eine umfangreichere Programmierung nach sich ziehen würde, wären wir um eine Nachricht dankbar. Dann würden wir vorübergehend die Oberfläche unseres alten Ratsinfomanagements durch die Firma Sternberg an unser neues Weblayout anpassen und vorerst sowohl oParl für die öffentlichen Unterlagen, als auch das RIM der Firma Sternberg für die nicht-öffentlichen Unterlagen parallel nutzen.

**Comment by the-infinity** [comment]
OParl ist aktuell nur für öffentliche Informationen ausgelegt. Man kann natürlich das OParl Datenmodell auch für nichtöffentliche Informationen nutzen, und wir wissen auch von Fällen, wo dies gemacht wird. Dies ist dann aber Entscheidung von dem Hersteller des jeweiligen RIS, und diese müssten das auch programmieren.

Es wäre natürlich schon vorstellbar, dass man ein abstraktes Rechtemodell vorsieht, welches bei entsprechenden Credentials andere OParl-Ausgaben hat. Da wir aber kein Industrie-Dienstleister sind, sondern eben ein ehrenamtliches Team, welches offene Daten mag, haben wir das zunächst als Prio B wahrgenommen. Die Signalwirkung wäre aus meiner Sicht zumindest eine Falsche, da der Weg zu "alle eigentlich öffentlichen Daten gibt es nur mit Credentials, und dann muss der Nutzer der öffentlichen Daten irgendwelche Zusatzverträge unterzeichnen" ziemlich schnell geht. Daher wird zumindest aus meiner Sicht zunächst der Fokus auf öffentliche, auth-freie APIs bleiben.

**Comment by Beloli** [comment]
Vielen Dank für die schnelle und informative Antwort! Wäre sicherlich interessant zu wissen, bei welchen Kommunen so eine Programmierung des RIS bereits vorgenommen wurde.
