### ISSUE TITLE
Tagesordnungspunkt - Zeitpunkt u. Verschlagwortung

### ISSUE THREAD

**Issue by awbonn** [OParl/spec#47]
Um Videoaufzeichnungen von Ratssitzungen mit der Tagesordnung taggen zu können, wäre die Erfassung des Zeitpunktes interessant:

- Tagesordnungspunkt Zeit/Anfang
- Tagesordnungspunkt Zeit/Ende 

Als Vorbereitung für späteres LOD:

- Verschlagwortung der Tagesordnungsthemen nach LeiKa, SKOR oder Dbpedia.

**Comment by lu-j** [comment]
Auf dem Workshop haben wir beschlossen, dass es möglich sein soll den Start- und Endzeitpunkt für einen Tagesordnungspunkt anzugeben. Ich denke der Praxis wird direkt ein Zeitstempel, also Datum und Uhrzeit gespeichert. Ein passender Name wäre startDateTime/endDateTime oder startTimestamp/endTimestamp. Aktuell gibt es noch keine konsistene Bennnenung für Zeit- und Datumsangaben in OParl, für dieses Problem möchte ich aber ein eigenes Issue eröffnen.

**Comment by akuckartz** [comment]
@lu-j :+1:

**Comment by the-infinity** [comment]
Gelöst mit 6e54e24c.
