### ISSUE TITLE
Definitionen für MUSS, SOLL und KANN

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#71]
Verweis auf RFC 2199:

Key words for use in RFCs to Indicate Requirement Levels
http://www.ietf.org/rfc/rfc2119.txt

(Diese deutsche Übersetzung ist fürchterlich und unbrauchbar:
http://www.normes-internet.com/normes.php?rfc=rfc2119&lang=de )

**Comment by lu-j** [comment]
Aktuell ist in Kapitel 1.6.1 "SOLL" mit "EMPFOHLEN" gleichgesetzt. Das englische "SHOULD" heißt übersetzt aber "SOLLTE", was bei einer Gleichsetzung mit "EMPFOHLEN" viel mehr Sinn ergibt.

Ich habe in der Spezifikation schon häufig "SOLL" gelesen und fälschlicherweise gedacht, es wäre eine zwingende Anforderung. Daher will ich jedes "SOLL" in "SOLLTE" oder besser in "SOLLTE nach Möglichkeit" ändern, oder gleich das Wort "EMPFOHLEN" benutzten.

**Comment by konstin** [comment]
Im moment findet sich in der Spezifikation 34 SOLL bzw. SOLLEN, während SOLLTE bzw. SOLLTEN nicht genutzt wird. Theoretisch könnte man das mit Suchen&Ersetzen Lösen, aber meiner Ansicht nach passt das strengere SOLL an den meisten Stellen besser als SOLLTE.

**Comment by lu-j** [comment]
Ich habe SOLL mit SOLLTE ersetzt.
@konstin: In fast allen Fällen war mit SOLL nur EMPFOHLEN gemeint und nicht ZWINGEND. Es gibt jetzt MUSS (=ZWINGEND), SOLLTE (=EMPFOHLEN) und KANN (=OPTIONAL). SOLL gibt es nicht mehr, damit es nicht mit SOLLTE verwechselt wird ;) Gibt es Eigenschaften, die du von EMPFOHLEN auf ZWINGEND ändern willst?

**Comment by konstin** [comment]
Im Moment fallen mir nur body:system und body:shortname ein. Das hat aber sowieso eher niedrige Priorität, da zwingende Eigenschaften zwar nicht sonderlich viel bringen, aber die Gefahr bergen, dass bestimmte RISe OParl nicht mehr implementieren können.

Von mir aus wäre der issue damit erledigt.

**Comment by eFrane** [comment]
Da body.system eine OParl-interne Eigenschaft ist sollte die doch sowieso zwingend sein, oder?

**Comment by the-infinity** [comment]
body.system ist ja dadurch gesetzt, dass system auf body verweist. Wir haben ja ansonsten auch die Backrefs nicht zwingend gemacht.
Da das eigentliche Problem aus @konstin s Sicht behoben ist und auch das ursprüngliche Problem geklärt wurde, indem SOLL / KANN / MUSS erheblich vereinfacht wurde, schließe ich das Issue.
