### ISSUE TITLE
API-Fehlermeldungen

### ISSUE THREAD

**Issue by marians** [OParl/spec#89]
Wir sollten noch eine Vorstellung davon entwickeln, wie die API im Fall von Fehlern (HTTP Status Code >= 400) reagieren soll.

Beispiele:

* Fehlerhafte Anfrage (400)
  * Benötigter URL-Parameter nicht vorhanden
  * Wert eines URL-Parameters, z.B. Datumsbereich, ungültig
* Ressource nicht vorhanden (404)
* HTTP-Methode nicht erlaubt
* Ressource nicht mehr vorhanden (410)
* Nicht implementiert (510)

Eine vernünftige Fehlermeldung besteht einerseits daraus, dass diese und andere Status Codes im HTTP Response entsprechend ihrer Bedeutung eingesetzt werden.

Darüber hinaus halte ich es für sinnvoll, in der Spezifikation auch festzulegen, wie der Server dem Client darüber hinaus gehende Informationen ausgeben soll. Die Basis wäre ein Objekttyp "OParlError" (oder wahlweise "OParlException"). Hier ein einfaches Beispiel:

```json
{
    "@type": "http://oparl.org/schema/1.0/OParlError",
    "message": "Parameter start_date has invalid value"
}
```

Der obige Fehler sollte im Zusammenhang mit einem HTTP Status Code 400 ausgegeben werden. Client-Implementierer könnten selbst entscheiden, wie sie mit dem Fehler umgehen und ob sie beispielsweise die "message" einem Nutzer anzeigen oder nicht.

Falls die maschinenlesbare Unterscheidung bestimmter Fehler benötigt wird, kann der Objekttyp erweitert werden. Beispielsweise könnte ein "OParlRangeExceededError" dazu dienen, anzuzeigen, dass beim Paginieren einer Liste das Ende überschritten wurde.

**Comment by konstin** [comment]
Gelöst in 9e46c0f3a4f77e2a877509d0aba3f47fb1de90af
