### ISSUE TITLE
Erweiterung um schreibende Zugriffe

### ISSUE THREAD

**Issue by akuckartz** [OParl/spec#99]
Etwas für die "Ferne Zukunft" (sollte aber in den Ausblick des Dokuments ;-)

Auch hier sollte das Rad nicht neu erfunden, sondern bestehende Spezifikationen und Techniken aus der _Linked Data_-Welt verwendet werden. Dazu gehören insbesondere die _Linked Data Platform_ des W3C und _Hydra_.

Ich schreibe dazu gerne etwas für das Dokument.

**Comment by akuckartz** [comment]
Da ich dieses Issue eröffnet hatte: Da #237 geschlossen wurde hat es für mich keine Relevanz mehr und kann von mir aus geschlossen werden. Ich verfolge schreibende Operationen in OpenGovLD weiter.

**Comment by konstin** [comment]
Schreibende Zugriffe sind auch ohne JSON-LD möglich. Dieser Issue bleibt für den Fall auch weiterhin geöffnet, dass diese Funktion benötigt wird oder jemand sich die Arbeit macht, das zu spezifizieren.

**Comment by konstin** [comment]
Schreibende Zugriffe sind weit außerhalb des Anwendungsbereich des OParl-Standards. Eine solche Funktion sollte in einem eigenen, unabhängigen Projekt entwickelt werden.

**Comment by akuckartz** [comment]
Gut zu wissen. Dann verweise ich auf dieses Issue: https://github.com/OpenGovLD/specs/issues/18 (Da hat sich zwar länger nichts getan, aber das kann sich jederzeit ändern.)
